### ISSUE TITLE
Cluster deprovisioning

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1005]
Add an `IHostingManager.DeprovisionAsync()` method and a `bool IHostingManager.CanDeprovision` property to the interface and the hosting manager implementations.  The deprovision method should remove all resources created for the cluster.  I believe all hosting managers except for **BareMetal** can support this and event bare metal should eventually be able to remove router rules when we support that.

It would be good to implement #1000 at the same time.  This allows users to BYOIP (bring your own public IP address) to the cluster.  The basic idea is that users may have a significant investment in specific public IPs (i.e. they're manually configured in DNS or whitelisted elsewhere).  So we want to be able to use addresses the user already has but be very sure that they're not deleted when the cluster is deprovisioned.

The idea is to add cloud cluster definition properties that allow the user to specify the resource IDs of  the existing address he/she wants to use.  We'd tag these with the usual cluster tags (but we won't rename them) and then we'd add an additional **neon:external = true` tag, indicating that the resource is used by cluster but is not owned by it.

When the cluster is deprovisioned, we'll examine this tag for the public addressess.  If this isn't present or is **false**, we'll delete the addresses as usual.  If this tag is **true**, we'll remove all cluster related tags but we won't remove the addresses.

**Comment by marcusbooyah** [comment]
Tracking this in #1281
