### ISSUE TITLE
Temporal health check fails when debugging Neon.Temporal

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#1015]
I have been trying to debug Neon.Temporal using the Debug Prelaunch method with the Temporal proxy.  I kept seeing intermittent errors on the proxy side when creating the Temporal Namespace and Workflow clients.  The error I was seeing was:
```
failed to build namespace temporal client.	{"error": "health check error: last connection error: connection closed"}
```

The health check that the SDK does on client creation was failing.  Some documentation about the gRPC health check [here](https://github.com/grpc/grpc/blob/master/doc/health-checking.md).

I initially thought that this might be an issue with the `client.Options` used to create the 2 clients, but I removed them and used the default constructors.  I was still receiving the errors.  I thought it might be an issue with the temporal test fixture but this was not the case either because I was able to cleanly execute the temporal-go tests on the fixture.

My next test was to do a default client creation in the Main of the temporal-proxy and just debug that without running the Neon.Temporal tests in parallel.  Client creation was successful.  I did the same test while running the Neon.Temporal tests in parallel and client creation failed with the same gRPC health check error.

This led me to believe that the issue might have something to do with temporal running alongside the Neon.Temporal tests.  To verify this, I ran temporal-go Helloworld sample with the Neon.Temporal tests running in the background and was able to reproduce the error.

**Comment by jefflill** [comment]
You're getting pretty good at writing bug reports with actual words!  That University English is paying off.

**Comment by johncburns1** [comment]
One potential workaround here is to disable health checks during client creation.  This is a client option.  I tested this out and it seems to work as expected.  The Namespace and Workflow clients are created successfully and workflows are registered.

**Comment by jefflill** [comment]
That seems reasonable, especially in debug mode.

**Comment by johncburns1** [comment]
> That seems reasonable, especially in debug mode.

Yes probably.  My only concern is that this issue might exists outside of a debug environment (somewhat verified with the temporal-go samples testing that I did).  I guess we could do our own health checks to the temporal server.

**Comment by jefflill** [comment]
**CLOSING:** Temporal is deprecated
