### ISSUE TITLE
Neon.SignalR: scalable without Azure?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1017]
One of our sister projects is going to rely on server-side .NET Blazor apps.  The problem is that the deployment solutions supported by Microsoft are somewhat limited.  Their **SignalR Redis** based solution has only been tested on a single Redis instance so is a single point of failure and this solution also requires the inbound load balancer to be configured with stick sessions.  There are two problems with this:

1. Istio (the Kubernetes ingress solution in neonKUBE), implements sticky sessions by hashing the source IP/port to one of the available target servers.  This works, but if a server is added or removed from the set most every existing connection will map to a different server, effectively dropping most client connections.

   This is really quite bad for a dynamic environment like Kubernetes where people will be doing rolling upgrades.  So if you had a 4 pod Blazor server cluster, a rolling upgrade would go like this:

   a. Blazor pod0 is stopped.
   b. Istio rehashes all client connections to the remaining three pods.
   c. Blazor pod0 is restarted with the new container image.
   d. Istio rehashes all client connections again across the four pods.
   e. Blazor pod1 is stopped.
   e. Istio rehashes all client connections to the remaining three pods.
   f. Blazor pod1 is restarted with the new container image.
   g. Istio rehashes all client connections again across the four pods.

      The same thing will be repeated for the remaining two pods meaning the client's will likely see 8 disconnects over the course of performing the rolling update on the 4 pods.  It would have been better to shut all pods down at once and restart them all together.

2. Every client will maintain a connection to one of the Blazor pods at all times, even when the app is idle.  This is by design, but means that for busy sites, the 64K connection limit per network interface may become a limiting factor.

Microsoft also has **Azure SignalR**.  This addresses both problems by essentially being a two-way proxy between the clients and the Blazor app servers.  Azure terminates the client connections in it's infrastructure with the Blazor app servers needing only one or two connections to the Azure SignalR service.  It looks like Azure SignalR is based on the Azure Service Bus which handles the routing under the covers.  There are a couple 3rd party solutions: one is open source but looks inactive, and the other is pricy at $895/year for a 4 core server.  Both of these require sticky sessions so they are still pretty broken.

I'm thinking we should probably implement our own solution on par with Azure SignalR: **Neon.SignalR**  We could bill this as:

**neonKUBE: the best way to host Blazor app servers outside of Azure!**

- [x] Based on NATS
- [ ] Docker container image that includes our code as well as NATS for easy deployment
- [x] Each Blazor server would create a NATS queue when it starts that would be used to receive inbound traffic from clients.
- [x] Neon.SignalR servers would monitor the available servers and route inbound client traffic via each servers input queue.
- [x] Neon.SignalR would create one or more NATS queues for broadcasts (aka the backplane).
- [x] We'd also create a Neon.SignalR library that included classes the Blazor app servers would use to integrate and probably most of the server implementation as well.
- [x] We'd still need to solve the inbound client connection limit issue, but on the **Neon.SignalR** pods.  We can mitigate by just deploying more pods.

This seems quite doable on the surface.  I'm putting this on the backlog for now.

**Comment by marcusbooyah** [comment]
This is done
