### ISSUE TITLE
Temporal worker and workflow/activity registration order of operations

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#1018]
I was running into some pretty puzzling issues with workflows decision tasks not being picked up once the workflows had been started.  The Temporal UI provided me with the insight that there were no pollers (workers) listening on the task queue that the workflows were running on.  After a bit I noticed the message below in the debug output:
```
2020/10/21 20:42:34 INFO  No workflows registered. Skipping workflow worker start Namespace test-namespace TaskQueue tests WorkerID unit-test
2020/10/21 20:42:34 INFO  No activities registered. Skipping activity worker start Namespace test-namespace TaskQueue tests WorkerID unit-test
```
When attempting to start a worker in Temporal before any Workflows/Activities have been registered, the worker just does not actually start.  This brings up an issue of order of operations.  Our current startup workflow is:
 1. Create namespace client,
 2. Create default namespace,
 3. Create workflow client,
 4. Create worker with workflow client,
 5. Start worker,
 6. Register workflows/activities with worker.

We need to alter this workflow such that step **5** occurs after step **6**.  So we need to talk about what this looks like.  The pattern I am seeing in the samples is to create the worker, register workflow/activities with the worker, and then start the worker.  So essentially decouple the creation and start of worker.  At the moment there are 2 worker related operations, `StartWorker()` and `StopWorker()`.  Maybe we want `NewWorker()`, `StartWorker()`, and `StopWorker()`.  

Temporal also introduced the idea of the `worker.Run()` method, which is a blocking call that listens on a channel for a OS interrupt.  This could be interesting to mess around with for workflow services.

The current workaround that I have used for testing is to just move the `worker.Start()` call in the temporal proxy into the `ExecuteWorkflow()` call.  This is not a super great fix but it allows for testing to proceed.

**Comment by jefflill** [comment]
YEP: This is a problem.  Back in Cadence, registration happened on the client (which was weird) and then after you finished registering workflows and activities, you'd start the worker and it would pick up the registrations from the client.  This was broken because it implied that you could only have one worker per client and I believe on the gp-proxy side, you could only have one worker per process (if I'm remembering correctly), which is the main reason why we started separate go-proxy processes for each connection.

I like adding a `TermporalClient.NewWorker()` method.  It looks like the GO client has a static `Worler.New()` [function](https://pkg.go.dev/go.temporal.io/temporal@v0.26.0/worker#New) that does the same thing but I think it makes more sense to be a client method.

**Comment by jefflill** [comment]
Ah, we already have a `TemporalClient.NewWorkerAsync()` method.  I'll bet that I just need to update the unit tests.

**Comment by jefflill** [comment]
Hmmm, it actually looks like the .NET code is doing the right thing.  Here's and example from the `Test_EndToEnd` constructor:
```
var settings = new TemporalSettings()
{
    Namespace              = TemporalFixture.Namespace,
    ProxyLogLevel          = TemporalTestHelper.ProxyLogLevel,
    CreateNamespace        = true,
    Debug                  = TemporalTestHelper.Debug,
    DebugPrelaunched       = TemporalTestHelper.DebugPrelaunched,
    DebugDisableHeartbeats = TemporalTestHelper.DebugDisableHeartbeats,
    ClientIdentity         = TemporalTestHelper.ClientIdentity,
    DefaultTaskQueue       = TemporalTestHelper.TaskQueue,
};

if (fixture.Start(settings, stackDefinition: TemporalTestHelper.TemporalStackDefinition, reconnect: true, keepRunning: TemporalTestHelper.KeepTemporalServerOpen) == TestFixtureStatus.Started)
{
    this.fixture     = fixture;
    this.client      = fixture.Client;
    this.proxyClient = new HttpClient() { BaseAddress = client.ProxyUri };

    // Create a worker and register the workflow and activity 
    // implementations to let Temporal know we're open for business.

    var worker = client.NewWorkerAsync().Result;

    worker.RegisterAssemblyAsync(Assembly.GetExecutingAssembly()).Wait();
    worker.StartAsync().Wait();
```
The problem is that we have a `NewWorkerRequest` message but we don't have a separate `StartWorkerRequest` message.  I'll add `StartWorkerRequest/Response` and the semantics will now be:

* `NewWorkerRequest` creates a new worker but doesn't start it.
* `StartWorkerRequest` actually starts the worker.

**Comment by johncburns1** [comment]
Cool and I need to do the same on my side as well because ATM NewWorker and StartWorker are coupled in the proxy.

**Comment by jefflill** [comment]
The `Worker.Run()` thing is interesting but we already handle this via [NeonService](https://doc.neonkube.com/T_Neon_Service_NeonService.htm) and [ProcessTerminator](https://doc.neonkube.com/T_Neon_Service_ProcessTerminator.htm) at a lower level.

So, we've already generalized this for all service types.

**Comment by jefflill** [comment]
The .NET side now sends a separate `StartWorkerRequest` message with the `WorkerId` I received from the proxy in the `NewWorkerReply`.  I also committed a potewntial fix for #1019 

Ball is back in your court!

**Comment by johncburns1** [comment]
I'll get on it.

**Comment by jefflill** [comment]
I've noticed some additional issues with workflow/activity registration.  There were some gaps where `workerMutex` wasn't be honored and activities weren't being registered.

...working on fixes

**Comment by jefflill** [comment]
I pushed these fixes to **master**.  I'm still not able to run unit tests due to Temporal connection issues.  Should I be running these in **DEBUG** mode?  It looks like I am able to connect to the proxy though.

**Comment by johncburns1** [comment]
I will have too look more into what the deal with that is.  You may need to rebuild the executables.  The issue is that when the tests are running, for some reason client health checks are failing so temporal cannot create namespace or workflow clients in setup.  I fixed this issue by disabling those health checks.  I have had success with running the tests with that feature disabled.  I had a toggle to only disable the health checks when DebugPrelaunch is enabled on the proxy side.  I made a change to always disable health checks but I guess this is not working.

I will look into this more.  I have not run the tests not in debug mode yet so I am not sure about what the behavior looks like.

**Comment by jefflill** [comment]
I did do a clean build.

**Comment by johncburns1** [comment]
Yeah I just tried it.  That does not seem to be the issue.  It's probably an issue with the proxy.  The proxy process looks like it terminates and then the connection fails.

**Comment by johncburns1** [comment]
So I bet there is some sort of fatal error happening on the proxy side that goes unhandled.  Maybe related to some of the changes that were made.  I am going to have to fix that before we can really proceed with anything else.

**Comment by johncburns1** [comment]
I found the issue I believe.  Temporal proxy is not building correctly on neonKUBE project build.  I deleted the proxy files that were there and then did a clean build and build is now failing.  So I think that proxy .gz that has been being used to build is a relic.  Which is somewhat good new because it could mean that the issue is not super sinister.

**Comment by johncburns1** [comment]
@jefflill I decided to manually compress the new proxy executables so that the solution would build and the tests would run.  Ran some tests and it looks like there is still a bit of an issue with activity registration.  Activity registration fails on the Neon.Temporal library side with:
```
 Message: 
    System.AggregateException : One or more errors occurred. ([TestTemporal.Test_EndToEnd+ActivityWithNoResult] is not an interface.)
    ---- Neon.Temporal.ActivityTypeException : [TestTemporal.Test_EndToEnd+ActivityWithNoResult] is not an interface.
  Stack Trace: 
    Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    Task.Wait()
    Test_EndToEnd.ctor(TemporalFixture fixture) line 105
    ----- Inner Stack Trace -----
    TemporalHelper.ValidateActivityInterface(Type activityInterface) line 506
    TemporalHelper.GetActivityTarget(Type activityInterface, String methodName) line 1042
    Worker.RegisterActivityImplementationAsync(Type activityType) line 121
    Worker.StartAsync() line 210
```
This is the first activity in the assembly to be registered so I made the assumption that this error is not isolated to any specific activity.  I did not test this though.

**Comment by jefflill** [comment]
OK: I believe I've fixed the the activity registration issue.  It was minor: I was passing the value wrong value as a parameter.

I've been seeing occasional proxy errors and I'm assuming these are due to Temporal server not being ready for longer than the connection timeout.  Rather than increasing the timeout, I've added a check in `TemporalFixture` what waits up to 120 seconds for Temporal to start listening on its RPC socket before connecting the client.  You can see this commit here:

https://github.com/nforgeio/neonKUBE/commit/ee3788bb96a3b3238f51e0eb13bb6d82ccb8f5d8

**Comment by johncburns1** [comment]
This is fixed.
