### ISSUE TITLE
Neon.Temporal mutex deadlock

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#1019]
There is a deadlock occurring in `Neon.Temporal.Worker.Workflow`.  The deadlock is caused by the mutex lock `workerMutex`.  The deadlock occurs on line 266 of `Neon.Temporal.Worker` in the `GetWorkflowRegistrationAsync()` function.  The function attempts to acquire `workerMutex` even though it was already acquired by the function that called it (line 355 of `Neon.Temporal.Worker.Workflow` in the `OnInvokeAsync()`).  The side effect is that an invoke reply is never sent back to the executing workflow so the workflow locks up after the first decision task and times out.

**Comment by jefflill** [comment]
Fixed
