### ISSUE TITLE
IPVS

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1052]
Upgrade setup to use IPVS for kube-proxy.

Helpful links:
https://docs.projectcalico.org/networking/use-ipvs
https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/

**Comment by jefflill** [comment]
Putting this on the backlog.  We should really look into this before we publicly support cloud and real on-premise clusters but we don't need this for neonDESKTOP previews.

**Comment by marcusbooyah** [comment]
We're going to make this a priority now since it's required to get WSL2 working well without a custom kernel build.

**Comment by marcusbooyah** [comment]
DONE
