### ISSUE TITLE
Investigate: synk (container image security checking)

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1069]
**SYNK:** Perhaps this could be used as an advanced security feature for neonKUBE.  I just noticed this when it showed up in a Docker Desktop upgrade.

https://github.com/snyk/snyk

We should at least be doing this when building our container images non both neonKUBE and neonCLOUD.

**Comment by marcusbooyah** [comment]
@jefflill might be interesting: https://kubernetespodcast.com/episode/140-security-and-snyk/

**Comment by jefflill** [comment]
This costs $200/month for up to 5 users, so $1200/year.  Seems a bit pricey.

Trivy looks like it might be a better solution anyway:

https://github.com/aquasecurity/trivy
