### ISSUE TITLE
neon-cluster-manager DB credentials are hardcoded and insecure

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1085]
I was going to copy/paste some code from **neon-cluster-manager** and noticed a couple issues:

- [ ] @marcusbooyah: You define `Service.connString` as a hardcoded string with an insecure password.  You should create the database user with a random password when creating the cluster and then loading that password via a secret k8s configuration passed to the service.  I think you should be able to do this using the following steps while setting up the cluster:

    * Generate a random password
    * Persist the secret to the cluster configuration (this will require #1084)
    * Create the database and user (you shouldn't be using the `postgres` user because its the **superuser**)
    * You grant only the permissions required
    * Persist the connection string as a k8s secret
    * Modify the **neon-cluster-manager** to read the configuration
&nbsp;
- [x] I noticed that the `Service` class (that I renamed earlier as a simplifying convention) is `partial` but that the other parts of the definition were hard to find because their file names weren't prefixed by **"Service.**.  I've been using the convention for `partial` classes is that the file with the constructor will be have the base name **Service.cs** in this case and that the remaining files will be named with the base name, followed by a dot and a name that identifies what's implemented inside.

    I went ahead and modified the other files to be named **Service.Kibana.cs**, **Service.LogPurger**, and **Service.Setup**.  This makes it much easier to grok what's going on.

**Comment by jefflill** [comment]
I've completed the #1084 implementation by adding these methods to `ClusterDefinition:`

* `void SetSetupState(string key, string value)`
* `string GetSetupState(string key)`
* `void RemoveSetupState(string key)`
* `void ClearSetupState()`

We can use these to manage setup related state that needs to be persisted across cluster setup restarts.  Let's standardize on the convention where these state keys are named with a prefix like:

**neon-cluster-manager.citus-user=cluster-manager**
**neon-cluster-manager.citus-password=kymn6rEKAM8P**

Note that these methods are thread-safe but don't persist the cluster definition to disk.  You should call `ClusterLogin.Save()` on the login that owns the cluster definition to do this immediately after setting important state.  This will ensure that the state will be available when the user needs to restart cluster setup.

Note that we special cased this for things like node passwords but I realized that we're going to need something more general.

**Comment by marcusbooyah** [comment]
DONE
