### ISSUE TITLE
CoreDNS not starting - network not ready

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1089]
I've been seeing an intermittent issue where the CoreDNS pods won't start and end up in a pending state until restarted. This happens early in setup. So far it seems to only happen on Hyper-V based deployments. Restarting the CoreDNS pods manually fixes the issue.

Currently after installing Calico we wait until all pods get to a "running" state. We should try to detect this and restart CoreDNS if necessary.

**Comment by marcusbooyah** [comment]
DONE

**Comment by jefflill** [comment]
Reopening.  I'm seeing this on Azure.

**Comment by marcusbooyah** [comment]
FIXED now
