### ISSUE TITLE
Cadence/Temporal concurrent activity task capability question

### ISSUE THREAD

**Issue by iain-cyborn** [nforgeio/neonKUBE#1097]
We intend to replace our use of SWF and are looking are Cadence/Temporal as an option and at Neon.Cadence/Neon.Temporal since most of our codebase is C#.

In our existing SWF workflows we have decisions that schedule multiple tasks which run concurrently and events let us know when they are all complete so that was one of the things I have tried to emulate in a test program to evaluate capabilities. I took the approach of using a Parallel.For e.g.

Parallel.For(0, workflowPackage.Value, async i =>
{
	inputString = JsonConvert.SerializeObject(workflowPackage);
	byte[] parallelResult = await activityC.RunTestActivity(Encoding.Default.GetBytes(inputString));
	parallelResults[i] = parallelResult;
});
Interface definition is
[ActivityInterface(TaskList = "parallel-tasks")]
public interface ITestActivityC : IActivity
{
	[ActivityMethod]
	Task<byte[]> RunTestActivity(byte[] args);
}
Implementation starts
[Activity(AutoRegister = true)]
class TestActivityC : ActivityBase, ITestActivityC
{
	public async Task<byte[]> RunTestActivity(byte[] args)

but that Parallel.For fails
Neon.Cadence.WorkflowParallelOperationException: 'Workflows cannot perform multiple operations in parallel.  Are you missing an [await]?'
This exception was originally thrown at this call stack:
    [External Code]
    Temporal.Experiment1.TestWorkflow.RunTestWorkflowAsync.AnonymousMethod__0(int) in TestWorkflow.cs

(note that some of the naming is a result of changing from Neon.Temporal to Neon.Cadence for the sake of immediate testing)

Now that could be a result of just not working well with Parallel.For and there are other methods of multi-threading that can be tried but before I embark on that it's probably worth checking if the Neon.Cadence/Neon.Temporal libraries are capable of supporting what I want to do.

**Comment by jefflill** [comment]
Your sample code above is a bit difficult to to follow. but it looks like you have a workflow that needs to execute several instances of an activity in parallel and then wait for all of the activities to complete.  This is supported by the Cadence client (and eventually the Temporal client when we get it working).  You are correct though about the .NET Cadence/Temporal clients being incompatible with the `Parallel` and other standard threading related classes.

Explicit threading is not generally supported in workflow implementations using the .NET clients.  We've focused on using **Tasks**  instead since they are especially suited to workflow implementations where instantiating explicit threads will be expensive and not terribly scalable.

We do support your scenario via `IActivityFuture`, `IActivityFuture<T>`, `IWorkflowFuture`, and `IWorkflowFuture<T>` along with methods to create workflow and activity stubs that return a future rather than waiting for the operation to complete.  The idea is to:

1. Create future stubs for the activity/workflow methods you want to run in parallel
2. Start the methods and remember the futures
3. The methods will all be running in parallel now
4. Wait for all of the futures to complete, taking note of any results

Here's an example from our unit tests:
```
        [WorkflowInterface(TaskList = CadenceTestHelper.TaskList)]
        public interface IWorkflowParallel : IWorkflow
        {
            [WorkflowMethod]
            Task<List<string>> RunAsync(int activityCount);
        }

        [ActivityInterface(TaskList = CadenceTestHelper.TaskList)]
        public interface IDoSomethingActivity : IActivity
        {
            [ActivityMethod(Name = "DoSomething")]
            Task<string> DoSomethingAsync(int arg);
        }

        [Activity(AutoRegister = true)]
        public class DoSomethingActivity : ActivityBase, IDoSomethingActivity
        {
            public async Task<string> DoSomethingAsync(int arg)
            {
                // Activity methods can pretty much do anything including
                // starting new processes and threads, communicating with
                // other services, reading/writing files, interacting with
                // GPUs, etc.
                //
                // In this example, we're just pausing execution for a
                // random delay between 0-2 seconds.

                var delay = NeonHelper.PseudoRandomTimespan(TimeSpan.FromSeconds(2));

                await Task.Delay(delay);

                return $"[arg={arg}]: Delayed for: {delay}";
            }
        }

        [Workflow(AutoRegister = true)]
        public class WorkflowParallel : WorkflowBase, IWorkflowParallel
        {
            public async Task<List<string>> RunAsync(int activityCount)
            {
                // This workflow runs the requested number of activities in parallel
                // and then waits for them to complete, appending the activity result
                // to the [results] list.
                //
                // We're going to use an [ActivityFutureStub<T>] to accomplish this.
                // These stubs return an [IAsyncFuture<T>] which you can use to await
                // the activity completion and result via a call to [IAsyncFuture<T>.GetAsync()].

                var results = new List<string>();
                var futures = new List<IAsyncFuture<string>>();

                // Start each activity and remember its future.  This doesn't wait
                // for the activity to complete, so all of the activities will 
                // essentially be started in parallel.

                for (int i = 0; i < activityCount; i++)
                {
                    var stub = Workflow.NewActivityFutureStub<IDoSomethingActivity>("DoSomething");
                    
                    futures.Add(await stub.StartAsync<string>(i));
                }

                // Wait for each activity future to complete and append each activity
                // result to the results list.

                foreach (var future in futures)
                {
                    results.Add(await future.GetAsync());
                }

                return results;
            }
        }

        [Fact]
        [Trait(TestCategory.CategoryTrait, TestCategory.NeonCadence)]
        public async Task Workflow_Parallel()
        {
            await SyncContext.ClearAsync;

            var stub = client.NewWorkflowStub<IWorkflowParallel>();

            var results = await stub.RunAsync(10);

            Assert.Equal(10, results.Count);

            for (int i = 0; i < 10; i++)
            {
                Assert.Contains($"[arg={i}]", results[i]);
            }
        }
```
...and here's a discussion of this in the documentation: [Neon.Cadence: Getting Started](https://doc.neonkube.com/Neon.Cadence-GettingStarted-Parallel.htm)

---

***Possible Future Changes:**

That all being said, I'm not entirely happy with the `IActivityFuture` and `IWorkflowFuture` design.  It's a bit weird for the clients to invent new future types when `Task` and `Task<T>` are futures themselves.  I'd really like to eventually have the stub methods be able to return a standard `Task` that can be awaited later.  We can't support that right now due to an early low-level design decision but we may be able to do this after we convert the GO implementation of the Cadence/Temporal proxy in-process and/or do a native gRPC implementation.

We're going to give the in-process implementation a shot for Temporal after we get the basics working and then we'll see about doing plain old tasks (POT) :).  We'd also retain the futures implementation for backwards compatibility.

**Comment by iain-cyborn** [comment]
Yes, that's exactly what I want to do, so I'll try it out.

**Comment by iain-cyborn** [comment]
The NewActivityFutureStub worked as expected and that will be the way to go for re-implementing most of our existing SWF workflows.

However there is one that I am not able to emulate with my Cadence test program. In the existing project using the AWSSDK for SWF, we have a workflow that will concurrently schedule a variable number of activity tasks but only a sub-set need to complete before the next activity task of the workflow is scheduled. For example we might schedule 5 of the concurrent activity task but only 3 need to complete before moving on to next activity task and using AWSSDK for SWF our decision poller can schedule the next activity task after 3 ActivityTaskCompleted events from the concurrent activity tasks. The remaining 2 concurrent activity tasks still continue to run but our decision maker doesn't care about their ActivityTaskCompleted events once the next activity task has been scheduled. Basically taking the results of the 3 quickest concurrent activity tasks and discarding the remaining.
With the Cadence library that doesn't seem to be an option, because
foreach (var future in futures)
{
	results.Add(await future.GetAsync());
}
just gets the activity task outputs in the order they were scheduled irrespective of what order the ActivityTaskCompleted events occur in.
Will the possible future changes (Cadence or Temporal libraries) allow something like this?

In the meantime, our desire to replace SWF is pressing enough that we are going to continue with adopting Cadence (now, hopefully Temporal soon) and change that workflow to only schedule the minimum number of the concurrent activity task and accept the fact that we might not be getting the shortest duration concurrent activity tasks that we could.

**Comment by jefflill** [comment]
Sorry for the delay getting back to you (I went for a drive in the mountains yesterday).

What you're describing is currently a gap in our client implementation.  We need to add an API that can wait on multiple different kinds of things: child workflows, activities, signals, etc. and return when one of these happen.  This API would need to return an indication of which thing completed and also record this to the workflow history so things will work properly if the workflow is rescheduled and needs to be replayed.  We've been planning on adding this to the Temporal client but not back-porting this to Cadence.

@johncburns1 and I have been making some progress on the Temporal port the last few weeks going from no unit tests passing to about half of them passing now.  We don't have an ETA on a first preview yet (this is a part-time thing for us).  Once we get the Temporal client working as well as the Cadence client, this feature will be the next priority and after that, better workflow unit testing support.

I don't really have a good workaround for this situation.  It's conceivable that that you could wrap your activities into child workflows and then have the parent listen on a synchronous signal the the child workflows call after their activities complete, just before the child workflow returns.  You'd put your decision logic in the synchronous signal handler.  This would be super ugly though and I wouldn't recommend it.

**Comment by jefflill** [comment]
FYI: We're currently pushing hard to get the .NET Temporal client to preview quality.  I'm hoping to have something by early January.

**Comment by jefflill** [comment]
Here's some early thinking on how this might work: https://github.com/nforgeio/neonKUBE/issues/1105

**Comment by jefflill** [comment]
**CLOSING:** Temporal is deprecated.  We're waiting for an official client.
