### ISSUE TITLE
Temporal Unit Test Failures

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1101]
I've fixed a couple tests and I'm doing a pass thru the current unit test failures to try categorizing them and chipping away at the causes.  Note that I've added the `FactAttributes.cs` file with additional unit test attributes in an attempt to categorize various tests and also to provide an easy way to enable/disable tests.  These replace the `[SlowFact]` attributes you added.

To enable unit tests, simply comment the `Skip = null;` line in the attribute constructor.

Re-debugging all of these tests isn't super fun, but I figure we can chip away at different problem categories one at a time and hopefully there won't be too many underlying causes.  We'll just have to gut through these.

--

- [x] **[Fact_Failing_BadWorkerId]:** It looks like a lot of the test failures are due to zero worker ID values being passed in messages from the proxy.  The .NET side is expecting valid positive worker IDs for these messages:

    `WorkflowInvokeRequest`
    `WorkflowSignalInvokeRequest`
    `WorkflowQueryInvokeRequest`
    `ActivityInvokeLocalRequest`
    `ActivityInvokeRequest`
    `ActivityStoppingRequest`

- [x] We're seeing a couple exceptions in generated stubs:
    - [x] `NullReferenceException`
    - [x] `TargetException`
&nbsp;
- [x] **Test_EndToEnd.WorkflowStub_Start_Untyped:** This test is hanging while waiting for a `WorkflowGetResultReply` message from the proxy.  I need to verify first that the workflow actually completed.
    ```
    [Fact_Failing_Untyped]
    [Trait(TestCategory.CategoryTrait, TestCategory.NeonTemporal)]
    public async Task WorkflowStub_Start_Untyped()
    {
        await SyncContext.ClearAsync;

        // Use an untyped workflow stub to execute a workflow.

        TestWorkflowStub_Execute.Reset();

        var stub      = client.NewUntypedWorkflowStub("TestWorkflowStub_Execute::hello", new WorkflowOptions() { TaskQueue = TemporalTestHelper.TaskQueue });
        var execution = await stub.StartAsync("Jeff");

        Assert.NotNull(execution);
        Assert.Equal("Hello Jeff!", await stub.GetResultAsync<string>());  // <--- TEST HANGS HERE

        // Verify that we're not allowed to reuse the stub.

        await Assert.ThrowsAsync<InvalidOperationException>(async () => await stub.StartAsync("Jeff"));
    }
    ```
    **NOTE:** The workflow never starts.

- [ ] @johncburns1: Several (17) **message round-trip tests** are failing
- [ ] @johncburns1: Interop tests
- [ ] @jefflill: All of the **replay tests** are failing: the workflow method is never called.
    &nbsp;
    **JEFF UPDATE:** I'm trying to execute the **Test_Replay.Nop** test which starts a workflow with a single enum parameter: **Nop**.  The weird thing is that the Temporal portal displays this parameter as **base-64 encoded??**
![image](https://user-images.githubusercontent.com/4908431/101989812-bfa4c500-3c57-11eb-8377-71a30ce8cacb.png)

    I wonder if Temporal changed how parameters are encoded which is why the portal isn't able to decode the base-64 encoded parameters.  The interop tests will clarify this.
    &nbsp;
    **JEFF UPDATE 2:** All of the replay tests passing now except for the two **MutableSideEffect** tests (I fixed the others by setting the default task queue in the client settings).
- [x] @jefflill: 12 of 32 **StubManager tests** are failing.
    **FIXED:** I just needed to tweak a faked worker initialization.
- [ ] @johncburns1: All of the **SyncSignal** tests are failing with a `NullReferenceException`.  This appears to be a JSON message property issue.  The description I get back from a `DescribeWorkflowExecution()` has all NULL properties.
- [x] @johncburns1: Local activity worker ID (you may have already fixed this one).  The .NET side is now passing the `WorkerId` for `ActivityExecuteLocalRequest` messages.  You'll need to pass this ID back to me when you send the `ActivityInvokeLocalRequest` to actually execute the activity.
- [ ] The two **Settings** tests are hanging.  There's a decent chance this is JSON property related.  Let's come back to these after resolving the other JSON issues.

**Comment by johncburns1** [comment]
I was missing `WorkerID` on signal, query, and activity stopping requests.  I added them.  I still need to test.

**Comment by jefflill** [comment]
@johncburns1: FYI: I've started looking at the non-end-to-end tests and fixing those.  I'm adding these as TODO items above as I find them.

**Comment by johncburns1** [comment]
@jefflill All inputs and outputs to the workflow are base64 encoded.  This is how it was in Cadence as well.

**Comment by jefflill** [comment]
**CLOSING:** Temporal is deprecated.  We're waiting for an official client.
