### ISSUE TITLE
WaitAll, WaitAny: aka "multi-select"

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1105]
I've been thinking about the Temporal multi-select feature **WaitAny** and I figure it's time to write something down and we'll also discus her sister: **WaitAll**.

Both of these features will require some changes:

- [ ] Add `public string Name` and `internal long Id` properties to `IAsyncFuture`.  We'll use the ID for identifying futures between the .NET client and the GO temporal-proxy,  The Name property can be set by the user to make it easy to identify which future was selected by `WaitAny`.  temporal-proxy will never see this name.

- [ ] We'll implement **WaitAll** as:
    ```
    Task<<IEnumerable<IAsyncFuture>>> IWorkflow.WaitAllAsync(<IEnumerable<IAsyncFuture>> futures, TimeSpan timeout = default);
    ```
    I believe that `timeout` will be very useful to users and it will be worth some extra effort:
    - [ ] `Timeout <= TimeSpan.Zero` will mean no (infinite) timeout.
    - [ ] The method will accept zero or more futures (zero is a NOP) and will wait for all of them to complete up to the timeout and will return the set of futures that actually completed.
    - [ ] The .NET side will set an `internal bool IAsyncFuture IsCompleted` property to `true` for completed futures so that we'll never wait on any of these again (temporal-proxy will never be asked to wait on a proxy that's been reported as completed by the proxy).
    - [ ] We'll need to add the future ID and workflow ID to the futures related messages like: `ActivityStartRequest`, `ActivityLocalStartRequest`, `WorkflowFutureRequest`, and `WorkflowQueueReadRequest`.
&nbsp;
- [ ] We'll implement **WaitAny** as:
    ````
    Task<IAsyncFuture> IWorkflow.WaitAny(<IEnumerable<IAsyncFuture>> futures, TimeSpan timeout = default);
    ````
    This has similar semantics to **WaitAll** except that its waiting for one of a set of futures to complete (or NULL).
- [ ] We'll probably want to add optional `name` parameters to future creation methods as a convenience.

---

This should be pretty straightforward on the .NET side.  The temporal-proxy side will need:

- [ ] A table for each worker that maps future IDs to futures (note that the .NET side will manage the IDs like everything else).  The proxy will create and add a future record to this table when it receives messages like `ActivityStartRequest` so the proxy will know what each future is doing.

    **NOTE:** I'm not entirely sure how we'll remove the futures from this table.  My current thinking is that the .NET side will keep track of all of the futures created during a workflow's execution and then I'll send the proxy a new message like `ClearWorkflowFutures` with the IDs for all of the futures to be removed just before the workflow completes.

    This will work fine for workflows that complete normally, but I'm worried that workflows that timeout or are terminated will never release these mappings in the proxy, resulting in potential memory leaks.  Perhaps there's a better way to detect when workflows are rescheduled on a different worker or are terminated.  [this](https://community.temporal.io/t/when-a-workflow-is-cancelled-how-is-the-ongoing-execution-handled/62/3) looks like a way to detect when a workflow is cancelled but I remember in Cadence there wasn't a way to know when a workflow was terminated and I don't know how we'd detect when a workflow is rescheduled on a different worker.

   One potential workaround might be to periodically check with Temporal server to verify that the workflows we think are running on our worker are actually still scheduled there by Temporal and if not, removing the workflow and its related futures.  Perhaps we can call `Client.ListOpenWorkflow()` periodically for every worker that has outstanding workflow executions and the worker would remove any workflows that are not in the list returned.  The GO documentation states **"Note: heavy usage of this API may cause huge persistence pressure."** but we could make the poll interval something relatively long like **5-15 minutes** (configurable), so I think we'll be OK.  This will also handle cleanup of terminated workflows.

    The .NET side will handle the polling but we'll need to implement `ListOpenWorkflowRequest/Reply` messages so the client will be able to get this info from the proxy. 

    **NOTE:** We'll probably be able to drop this polling when we do a native gRPC implementation,

**Comment by jefflill** [comment]
I did some research on the GO `Client.ListOpenWorkflow()` API and it doesn't look like it's going to do what we want.  We want to query for the workflows currently open on a specific worker but this is (sensibly) abstracted away for these high-level APIs.  We may need to ask for some help from the Temporal GO client team.

I think what we'd want is to be able to register some kind of notification handler that the GO client calls when a workflow that has been scheduled on a worker is rescheduled elsewhere or is terminated (I believe we already handle cancellation, right).  We have one other ask from Temporal: disabling their handling of the stacktrace query so we can answer it and return the .NET stack instead of the GO stack.

**Comment by ericsampson** [comment]
This might be a question more suited for neonLIBRARY, but...

I noticed that the Azure Durable Task Framework / Functions use `WhenAll` and `WhenAny` for the purposes that you are describing instead of the non-task-returning/blocking `WaitAll` and `WaitAny`.
So I'm wondering if that would be a better choice for the methods that you describe above, as they return Task<> just like `WhenAll` and `WhenAny`.

Cheers!

**Comment by jefflill** [comment]
Yeah, the specification for this feature is still in progress.  These methods as designed use `IAsyncFuture` implementations right now rather .NET Tasks due to how the .NET Temporal client currently communicates with the proxy implemented in GO which actually communicates with the Temporal Server.  These async futures are required to maintain the idempotentcy (if that's a word) required of Temporal workflows.  These methods do return Tasks so they can be awaited and `WaitAny()` returns the completed async futures so the developer can know which tasks were completed and then take the appropriate action.

There's a decent chance that we'll be able to drop these async futures and replace them with tasks before we ship because we're thinking about hosting the GO code in process with the .NET client and communicate with it via shared memory rather than over the network.  This will give us tighter control over the order of operations without the async future concept.

We'll still be providing these wait methods in `Workflow` and workflows will be required to use these as opposed to any .NET primitives so that replaying a workflow from history will work (e.g. if Temporal rescheduled the workflow on a different worker machine due to a failure or something).  We could align the names to better align with .NET like `IWorkflow.WhenAny()` etc. but we'll see.

**Comment by ericsampson** [comment]
Ah ok, I didn't realize that it was communicating with a go proxy, I'm new to the project. 

Is there a plans in the future to skip the use of embedded Go, and just talk directly using .NET gRPC ?

**Comment by jefflill** [comment]
Replying to a very old comment:

We don't have plans to go native gRPC any time soon but we are going to convert the GOLANG proxies into shared libraries which will clean things up quite a bit.

I'm going to close this issue and track the changes in: #1295
