### ISSUE TITLE
Cluster setup failing

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1109]
Cluster setup is still failing after syncing.  I re-ran the large cluster setup several times without success.  It looks like there were various different time out problems for the first runs bit the last two look like they're probably the same coding issue (a parsing error).

[Failed-Setup.zip](https://github.com/nforgeio/neonKUBE/files/5699466/Failed-Setup.zip)

**Comment by marcusbooyah** [comment]
`home-large` and `home-small` should be mostly working now. We are still seeing throttling issues though when pulling images from docker hub.

**Comment by jefflill** [comment]
Marcus got this working.

**Comment by jefflill** [comment]
I'm going to close this.  We'll create a new optimization issue to consolidate things like this with todo check boxes for things like this after we get image pre-positioning working.
