### ISSUE TITLE
Convert from Docker to CRI-O

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1111]
Docker is being deprecated in favor of Containerd or CRI-O.  We need to convert:

https://analyticsindiamag.com/kubernetes-parting-ways-with-docker-what-does-it-really-mean/

**Comment by marcusbooyah** [comment]
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

**Comment by jefflill** [comment]
This a decent overview of the Docker components and how they relate to Kubernetes:

http://alexander.holbreich.org/docker-components-explained/

From my read, it looks like **dockerd** communicates with **containerd** to actually manage/run container images so I believe we'll still be installing Docker on the cluster nodes and that we'll still be able to use the **docker-cli** on the nodes for managing containers.

**Containerd vs. CRI-O:**

This link discusses this: https://medium.com/cri-o/container-runtimes-clarity-342b62172dc3

The main takeaway is that **CRI-O** is much more tightly coupled to Kubernetes and it likely to be more stable over time since it's not trying to handle other scenarios like **containerd** does.  **containerd** is compatible with **docker-cli** but **CRI-O** is **not**.

It looks like **podman** (https://podman.io/whatis.html) is the client tool to be used for managing **containerd** and it's supposed to be a **drop-in replacement for the docker-cli**, implementing most features (but not things like DockerCompose) and apparently it can also manage Kubernetes pods as well.

We'll have to think about which one we should support since changing our mind in the future will probably be difficult: i.e. how would we **upgrade a cluster from containerd to CRI-O transparently?**

My gut feel is that we should go with CRI-O because it has less overhead (shims) and because it's Kubernetes native which means it will probably be supported for a very long time or perhaps forever.  It's entirely possible that Kubernetes could drop support for **containerd** in the future like they're deprecating Docker support now.

**Comment by jefflill** [comment]
We've agreed that CRI-O is the best way to be deeply compatible with Kubernetes going forward.

One problem is that we've been relying on Docker Engine to forward logs from containers to our **neon-log-host** service.  This is already a bit broken because it prevents Kubernetes from ever seeing these logs so they'll never appear in the Kubernetes dashboard.  The big problem though is that CRI-O doesn't have any way to forward logs, so we'll need to figure out an alternative.

- [ ] Install CRI-O instead of Docker Engine on nodes as the container runtime.
- [ ] Figure out a new logging strategy.
    - [ ] I'll bet that **neon-log-host** will end up reading local log files.  [this](https://thenewstack.io/logging-for-kubernetes-what-to-log-and-how-to-log-it/) basically confirms this.  This article discusses using sidecars to capture logs but that seems complex to me and would mean that an additional process will be started for every pod which seems like a lot of overhead compared to having one process per node tailing log files.
    - [ ] We'll want to capture logs from Kubernetes components as well.  These may end up in the systemd log but perhaps not.  We'll need to verify and ensure that we're parsing these so they'll be nice.
        - [ ] kube-apiserver
        - [ ] kube-scheduler
        - [ ] etcd
        - [ ] kube-proxy
        - [ ] kublet
        - [ ] kubernetes events
        - [ ] kubernetes audit logs
        - [ ]

**Comment by jefflill** [comment]
We've decided to switch to go all-in on Grafana metrics/logging so the remaining TODOs are no longer relevant.
