### ISSUE TITLE
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1123]
While preparing node images, we're seeing a kernel warning/error when it's parsing system settings.  This happens while configuring CRI-O:
```
sysctl --system

* Applying /etc/sysctl.d/10-console-messages.conf ...
kernel.printk = 4 4 1 7
* Applying /etc/sysctl.d/10-ipv6-privacy.conf ...
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2
* Applying /etc/sysctl.d/10-kernel-hardening.conf ...
kernel.kptr_restrict = 1
* Applying /etc/sysctl.d/10-link-restrictions.conf ...
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/10-magic-sysrq.conf ...
kernel.sysrq = 176
* Applying /etc/sysctl.d/10-network-security.conf ...
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.all.rp_filter = 2
* Applying /etc/sysctl.d/10-ptrace.conf ...
kernel.yama.ptrace_scope = 1
* Applying /etc/sysctl.d/10-zeropage.conf ...
vm.mmap_min_addr = 65536
* Applying /usr/lib/sysctl.d/50-default.conf ...
net.ipv4.conf.default.promote_secondaries = 1
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument   <<-------
net.ipv4.ping_group_range = 0 2147483647
net.core.default_qdisc = fq_codel
fs.protected_regular = 1
fs.protected_fifos = 1
* Applying /usr/lib/sysctl.d/50-pid-max.conf ...
kernel.pid_max = 4194304
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /usr/lib/sysctl.d/protect-links.conf ...
fs.protected_fifos = 1
fs.protected_hardlinks = 1
fs.protected_regular = 2
fs.protected_symlinks = 1
* Applying /etc/sysctl.conf ...
```
This appears to be a **systemd** problem and doesn't look serious:

https://github.com/systemd/systemd/issues/17156

I'm putting this on the backlog so we can follow up on the outcome.

**Comment by jefflill** [comment]
I'm going to go ahead and close this.  I'm entirely sure where this setting is actually defined:
```
net.ipv4.conf.all.promote_secondaries
```
We're not setting this during cluster node initialization and I don't see this in `/etc/sysctl.conf either.  This setting determines what happens when a network interface has multiple IP addresses assigned and the primary interface is removed.  This is trying to configure all interfaces to promote any secondary addresses to primary when the primary is removed.  There appears to be some differences with how `systemd` and `sysctl` handle the **all** or **"*"** syntax in the value and the an issue has been submitted for one team to address this.  We don't currently assign multiple IPs to interfaces, so this shouldn't be a problem before it's fixed.

The systemd/systemd#17156 bug has been closed and it appears that this fix will probably appear as a package update.

**Comment by zogness** [comment]
This has not been fixed.  I grepped for "net.ipv4.conf.all.promote_secondaries" in /etc on Ubuntu 20.04.3 LTS and grep found nothing.

**Comment by jefflill** [comment]
Thanks for the heads-up.  I don't believe this really impacts neonKUBE.
