### ISSUE TITLE
Create: neon-startup service

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1126]
The HAProxy container deployed to cluster nodes to provide HA access to Etc does not restart automatically on node restart after we converted to CRI-O.  We suspect that CRI-O is not honoring the **restart-always** option (perhaps by design).

 The solution is to create a new **neon-startup** systemd service that is configured to start after CRI-O.  Note that **kublet** and any other Kubernetes base services seem to run as _static pods_ by default rather than as systemd services, so we won't be able make those services dependent on the new **neon-startup** service.

**Comment by jefflill** [comment]
Looks like we can use a static pod for this:

https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/cluster-administration/static-pod/

**Comment by jefflill** [comment]
@marcusbooyah: Is this still necessary or can we close it?

**Comment by marcusbooyah** [comment]
This is done. We're using it for the registry too.
