### ISSUE TITLE
Describe Queue List Test Failing

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#1127]
The `Base_DescribeTaskQueue` end-to-end test is intermittently failing because the pollers may not be available yet.  We might need to explore adding a wait in the tests to ensure that poller info is available at the time of request.  The test works when I add a breakpoint and wait about 5 seconds before calling Temporal server with the `client.DescribTaskQueue()` method.

**Comment by jefflill** [comment]
**CLOSING:** Temporal is deprecated.  We're waiting for an official client.
