### ISSUE TITLE
Inconsistent cluster namespaces, etc?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1155]
It seems like some of the namespace names should be changed, the logic being that user's should see a small number of **_system_** namespaces in addition to **_default_** and their own.

How about this?

- [x] `istio-operator --> neon-ingress`
- [x] `istio-system --> neon-ingress`
- [x] `kubernetes-dashboard --> neon-system`
- [x] `monitoring --> neon-monitor`
- [x] `openebs --> neon-storage`

The idea is to consolidate all of these services into a **neon-*** namespace because they are all part of our distribution and also to drop specific technology from the names like **istio** or **openebs**, because it's very possible that we'll we may replace some of this tech in the future.

**NOTE:** I initially thought we could roll this into the **neon-system** namespace but some of these have a lot going on.

- [x] Also, is it possible to rename these **cluster roles** to be consistent with the others:

    `psp-neon-metrics-prometheus-prometheus-node-exporter --> neon-metrics-prometheus-prometheus-node-exporter-psp`
    `openebs-cstor-csi-provisioner-role -->  neon-storage-openebs-cstor-csi-provisioner-role`

    BTW: What does the **-psp** suffix stand for?

- [x] We should also discuss whether we should change all instances of `metrics --> monitor` since we're folding **metrics + logs** into **monitoring**.  This means that `neon-logs-promtail` should probably also be renamed to `neon-monitor-promtail`.

- [x] I'm also guessing that the **"-ku-"** in roles like **neon-metrics-prometheus-ku-prometheus** is short for "kubernetes** and that we use "**-kube-** in other cases.  We should probably standardize on **-kube-** for this.

- [ ] One other thing, do we really need to repeat word like **prometheus** as in **neon-metrics-prometheus-ku-prometheus**?

**Comment by jefflill** [comment]
Let's put this one off until after we can do a demo.  This will probably be destabilizing.

**Comment by jefflill** [comment]
Removing from the backlog because we want to finalize these naming changes before we build Loopie's next cluster.

**Comment by marcusbooyah** [comment]
It's not possible to remove the prefixed `prometheus-` from the `StatefulSet` created by the operator, but I did clean up the other things somewhat.

**Comment by marcusbooyah** [comment]
DONE
