### ISSUE TITLE
cadence-proxy ArgumentOutOfRangeException in DescribeWorkflowExecutionAsync

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1163]
We're seeing this at Loopie. @jefflill thinks that it may be a serialization issue.

> [ERROR] [version:unknown] [module:Neon.Cadence.WorkflowBase] [index:365] System.ArgumentOutOfRangeException: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks')\n   at System.DateTime..ctor(Int64 ticks)\n   at Neon.Cadence.Internal.InternalPendingActivityInfo.ToPublic()\n   at Neon.Cadence.Internal.InternalDescribeWorkflowExecutionResponse.ToPublic()\n   at Neon.Cadence.CadenceClient.DescribeWorkflowExecutionAsync(String workflowId, String runid, String domain)\n   at WFOrderMonitor.WorkflowOrderMonitor.MonitorOrderWorkflows() in C:\\Users\\Grant\\loopie\\Workflows\\wf-order-monitor\\WorkflowOrderMonitor.cs:line 85\n   at Neon.Cadence.WorkflowBase.OnInvokeAsync(CadenceClient client, WorkflowInvokeRequest request)

**Comment by johncburns1** [comment]
Is there more context? What value is being passed to cause the issue? From the error it looks like the `DateTime` value being serialized is either too large or too small.  I'm sure that you already looked at that.  Might need a little more context to replicate.

**Comment by jefflill** [comment]
**CLOSING:** Cadence is deprecated.  We're waiting for an official Temporal client.
