### ISSUE TITLE
Cluster setup still failing with 4 core nodes

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1167]
@marcusbooyah: I'm still seeing cluster setup failures with nodes configured with 4 cores (the default).

I thought we needed 2 cores or even less now.  This needs to work.  You should probably reduce the number of nodes in your test clusters to 4 so you'll see this behavior.

Needing more than 4 cores is a problem for my DL360 because it has only 8 cores and XenServer appears to be kind of reserving 4 cores for itself, so I can't create a 8 core VM.

**Comment by marcusbooyah** [comment]
This was related to Istio needing too much CPU and is now fixed.
