### ISSUE TITLE
GitHub deployment API

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1178]
@marcusbooyah: We need an API to minimally manage container packages as we discussed:

* List packages
* Delete packages
* Make packages public

I've laid out an API for this in the **Neon.Deployment** library called `GitHub`.  This is a static class where the users will need call `GetCredentials()` first to load and cache the required GitHub credentials (the PAT and user login) and then call one of the APIs present from the `GitHub.Packages` property (these are defined in `GitHubPackageApi`.

I've defined these APIs so they'll be easy to call from Powershell scripts etc.  They all accept an optional selection pattern, so it'll be easy to do things like delete all or just some of the container images:
```
// Deletes all packages
GitHub.Packages.Delete("neonkube-dev");
GitHub.Packages.Delete("neonkube-dev", "*");

// Deletes only the k8s packages
GitHub.Packages.Delete("neonkube-dev", "k8s*");

// Deletes a specific package
GitHub.Packages.Delete("neonkube-dev", "busybox");

You can use the `NeonHelper.FileWildcardRegex(string)` method to generate a `RegEx` from a string with "*" and "?" wildcard characters that work like filesystems do.  The idea is that you'll probably implement these by listing all of the packages and then filtering them by applying this regex to the package names.

```

**Comment by marcusbooyah** [comment]
This is done
