### ISSUE TITLE
Test_Packages

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1188]
- Convert the tests to use the new package repo.  You can assume that your tests are the only thing referencing these.
- Add a constructor that removes all packages so the repo will start out in a known state
- I don't see you pushing any packages to the package registry.  Your tests should probably create and publish several docker containers.  These container images don't need to actually do anything so I'd recommend finding a very small image somewhere (alpine or perhaps even smaller) and then your tests can
- Pull the small image into the local docker cache
- Save the image to a temporary file (using Neon.IO.TempFile to manage it)
- Load the image back into your local docker cache using different image names
- Push these images to the neon-test package registry
- Then run your tests.
- Note that you'll need to do the pushing in each test unless you want to do this initialization in the constructor (which I wouldn't recommend)
- I don't see any tests with the "?" wildcard

**Comment by jefflill** [comment]
We're going to drop this hacked implementation and continue to watch for new GitHub REST APIs for this.
