### ISSUE TITLE
Question: State of Neon.Temporal

### ISSUE THREAD

**Issue by tsujp** [nforgeio/neonKUBE#1192]
I see that Neon Temporal is not production ready -- what is required currently for it to reach that state? I'd be willing to contribute where I can but am unsure of what the delta is between it's current state and production readiness.

**Comment by martaver** [comment]
I'd love it if this issue was pinned and we had a few short updates on this as progress unfolds!

**Comment by Woland2k** [comment]
any update on the state?

**Comment by marcusbooyah** [comment]
@Woland2k We are deprecating this project in favor of the official .NET Temporal client found [here](https://github.com/temporalio/sdk-dotnet)

**Comment by jefflill** [comment]
**CLOSING:** Temporal is deprecated.  We're waiting for an official client.
