### ISSUE TITLE
Neon.Service metrics tweaks

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1221]
We have a bit of work to do here:

- [ ] ASP.NET metrics
    - [ ] Our documentation recommends the user turn off regular .NET metrics when they enable ASP.NET metrics.  This is probably incorrect.
    - [ ] We need a snippet that shows how to configure ASP.NET metrics
    - [ ] Update these neonKUBE services to follow the convention.  They're currently exposing metrics on port 81 but this should be on the same port as the web host, port 80:
        - [ ] **neon-dashboard**
        - [ ] **neon-sso-session-proxy**

- [x] Health metrics: 
    - [x] NeonService has the concept of health status which can be exposed as a file that can be monitored by the Kubernetes scheduler.  We should exposes  built-in metric counter that counts the number of times the app has transitioned from healthy to unhealthy.
    - [x] Let's also implement a built-in **runtime** (seconds) counter

**Comment by marcusbooyah** [comment]
DONE
