### ISSUE TITLE
Push node images to Harbor after setup

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1223]
The node image cleaner should be disabled until this is complete as well.

**Comment by jefflill** [comment]
I'll take this one on.  I'm planning on generating another script to handle this, like we did for importing images to CRI-O and then cluster setup will run the script on the first manager (only).

@marcusbooyah: questions:

1. I assume that I'll be able to **push these images** like this, correct?
   ```
   podman push neon-registry.node.local:PORT/IMAGE:TAG
   ```
   What port is Harbor listening on, **5000?**

2. Do I need to **log podman into Harbor?**

**Comment by marcusbooyah** [comment]
DONE
