### ISSUE TITLE
[build]: service warnings

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1235]
I've noticed three build warnings (these have been present for a few months):

![image](https://user-images.githubusercontent.com/4908431/124803447-fbfa8400-df0d-11eb-913b-728972d45ef1.png)

I think you can just delete the field **k8s** field for the first warning.  The other warnings indicate that the field is referenced but is never assigned.

**Comment by marcusbooyah** [comment]
These are no longer present
