### ISSUE TITLE
Container image garbage collection

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1238]
In the old hive days, we used have a script based service that would periodically prune local Docker images so these don't accumulate forever.  kubelet handles this for Kubernetes:

https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/

We should enable this after we push all of the images to Harbor.

**Comment by marcusbooyah** [comment]
Looks like this has reasonable defaults and is enabled
