### ISSUE TITLE
Headend REST refactor

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1260]
We'll need to do a pass on the Headend service definition before we ship anything.

I just noticed that the **/cluster/domain** API uses **GET** rather than **POST**.  HTTP **GET** operations are normally cache-able by web proxies so we could seen unexpected behavior.  Also, this really should be **POST** to be consistent with the REST standard.

We should also think about how users will interact with this service long term.  With the current design, we'll create a new domain and certificate every time a user creates a cluster.  We'll probably need a way to reuse the domain by assigning an new IP when users redeploy a cluster.  This will probably require being able to name a domain instance and neonCLOUD user accounts

We should also think about how we arrange the REST endpoints since; perhaps something more like:
```
/cluster
    /setup
        /domain:
            GET: lists all user domains or retrieves a specific domain by name
            POST: creates a new domain
            PUT: updates a domain
    /telemetry
        POST: receives telemetry from clusters
/app
    /telemetry
        POST: receives telemetry from the app
```
We'll also need to think about how we're going to version the REST API.

**Comment by marcusbooyah** [comment]
DONE
