### ISSUE TITLE
Support for SearchAttributes and ContextPropagator in Neon.Cadence and Neon.Temporal

### ISSUE THREAD

**Issue by gpaglia** [nforgeio/neonKUBE#1268]
Hello,
looking at the Cadence/Temporal Java/Go APIs against the Neon corresponding ones I have noticed that the following capabilities seem to be missing in the Neon .NET client implementation:

- SearchAttribute support both at Workflow creation time and from within the workflow itself, to enable ElasticSearch-based queries on custom workflow tags/parameters
- ContextPropagator support to propagate information to child workflows or activities

So I would like to know:

- If my understanding is correct (for Neon.Cadence and/or Neon.Temporal), and, if so, if there is any workaround to achieve the same functioality (e.g.: I have seen that actually one can add the SearchAttributes via the CLI, so I suspect there should be a way, in any case, to add those additional attributes bypassing the .NET client if there is actually a limitation there)
- If there is a plan to catch-up on these functions, within Neon.Cadence and/or Neon.Temporal
- How far the Neon.Temproal client is (timewise) from practical usability (I mean a funcionally complete beta at least)

Thanks a lot,

Gianni

**Comment by jefflill** [comment]
**CLOSING:** Temporal is deprecated.  We're waiting for an official client.
