### ISSUE TITLE
cStor and cluster configuration

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1270]
The current cluster cStor configuration logic is a bit broken right now.

Currently within a cluster definition, node definitions include a boolean **OpenEBS** property that is supposed to indicate that OpenEBS and a cStor block device should be provisioned on nodes where this property is set to true.  For normal clusters, we automatically select some nodes to host OpenEBS when the cluster definition doesn't set **OpenEBS=true** for any node.

- [x] The first problem is that we really don't want to provision OpenEBS cStor for single node clusters deployed by neonDESKTOP due to the multi-GB memory required and the new ready-to-go images can't support more than one node image anyway.  We currently hack around this by checking the cluster name and not deploying cStor for these cases.

- [x] The second problem is that the **OpenEBS** node definition property doesn't really make a lot of sense anyway.  This evolved from our old neonHIVE Ceph feature (abandoned years ago).  For that project, users needed to specify which nodes would have Ceph deployed at the host level including a BlueStore block device.

    OpenEBS is deployed as normal Kubernetes services/pods so all we really need is a way for users to specify which nodes will host a cStor block device (if any) since we're always deploying OpenEBS even when there's no cStor devices.  I think we should probably rename this property to **OpenEbsStorage** and default this to **false**.

- [x] Define a new enum named **OpenEbsEngine** that define **cStor** and **None** and then add a new **Engine** property to **OpenEbsOptions**.  This property will default to **None**.  For now, this will control whether OpenEBS/cStor will be deployed but we may also want to support [Jiva](https://docs.openebs.io/v090/docs/next/jiva.html) or other engines (if any) in the future.

    It looks like Jiva is intended for smaller clusters and has less overhead than cStor which probably scales better and has more features.  It may be interesting to look into Jiva as an alternative to cStor for small and perhaps even the ready-to-go built-in clusters.

- [x] Cluster definitions should verify that no nodes have **OpenEbsStorage=true** when **OpenEbsOptions!=OpenEbsEngine.None**

- [x] We should remove the cluster definition logic that automatically selects some nodes to host cStor devices when the user doesn't specify any because this doesn't make sense any more.  Remove the **NeonHelper.EnsureOpenEbsNodes()** method.

- [x] We need to remove the cluster name hacks and just use the presence of nodes with ****OpenEbsDevice=true** during cluster setup.

    - [x] Centralize code for checking for a neonDESKTOP built-in cluster by adding a **ClusterDefinition.IsDesktopCluster**.  This is much cleaner than comparing cluster names throughout the project.

**Comment by jefflill** [comment]
Related: #1263

**Comment by jefflill** [comment]
@marcusbooyah: I've committed and pushed these changes to master.  Could you please have a look at the commit to make sure I didn't miss anything or do anything stupid:

https://github.com/nforgeio/neonKUBE/commit/fcf9712ef74736fe85bdcdc2c5467a5dee705ab2

I've tried creating a single node cluster without deploying a cStor and cluster setup is hanging while waiting for the Citus database.  I'll bet that this is probably related to cStor not being there.  You'll have to have a look at this too:

![image](https://user-images.githubusercontent.com/4908431/135886153-25f45964-e451-42c6-9e9c-ce16a22b5c72.png)

**Comment by marcusbooyah** [comment]
This is working now.
