### ISSUE TITLE
Dynamic compilation issues are back

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1276]
We're seeing issues with dynamic code generation again and this is breaking the unit tests for ModelGen, Cadence, and Temporal.  We addressed this several months ago by targeting multiple frameworks for many assemblies and that seemed to fix things.

I'm not entirely sure what has changed in the meantime; perhaps we upgraded to new framework and didn't notice because CI has been down for a while.  I've been going back and fixing the CI issues and noticed this.

I believe [this post](https://github.com/jaredpar/basic-reference-assemblies#what-is-wrong-with-using-typeofenumerableassembly) may finally explain what's going on here.  The ModelGen, Cadence, and Temporal and projects all target .NET Standard 2.0 as well as the net48, netcoreapp3.1 and net5.0 but the code in ModelGen always uses a hacked copy of the .NET Standard 2.0 reference assembly when compiling models.  You'd think this would work (and it used to) but perhaps it doesn't work when we're building a non .NETStandard assembly.

This guy works on Roslyn and has published a nuget package with the current reference assemblies and this also adds some extensions to make them easy to reference:

https://www.nuget.org/packages/Basic.Reference.Assemblies
https://github.com/jaredpar/roslyn-codedom

So here's what I need to do:

- [x] Remove the .NETStandard 2.0 target framework from these projects:
    - [x] Neon.Cadence
    - [x] Neon.ModelGen
    - [x] Neon.Temporal

- [x] Reference the **Basic.Reference.Assemblies** package in these projects, update the dynamic compilation code to use the reference assembly that matches the current build (via conditional compilation)
    - [x] Neon.Cadence
    - [x] Neon.ModelGen
    - [x] Neon.Temporal

- [x] Most of the library assemblies can probably revert back to targeting just .NETStandard2.0 or 2.1

- [ ] Run/fix the unit tests
    - [x] ModelGen
    - [ ] Cadence
    - [ ] Temporal

**Comment by jishf** [comment]
Hey team - @iain-cyborn and I actually ran into this issue with Neon.Cadence last week too.

It happened for us with a NET5.0 service deployed as a self-contained, single-file build, when attempting to start a workflow:

```
System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.StandardFileSystem.OpenFile(String filePath, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
   at Neon.Cadence.Internal.StubManager.GetWorkflowStub(Type workflowInterface, Boolean isChild)
   at Neon.Cadence.Internal.StubManager.NewWorkflowStub[TWorkflowInterface](CadenceClient client, WorkflowOptions options, String workflowTypeName)
   at Neon.Cadence.CadenceClient.NewWorkflowStub[TWorkflowInterface](WorkflowOptions options, String workflowTypeName)
   at Cyborn.Ionburst.WorkflowManager.Service.RunGetWorkflow(BasicStoreWorkflow workflowPackage, ApplicationSettings settings)
```

Reverting to a non-single-file build as a workaround fixed things and seems stable enough for what we're doing at the moment, as our usage is still heavily experimental, but it's good to know it's a known issue! 

As far as I can remember, our service worked as a single-file build on .NET Core 3.1 - which really didn't help!

**Comment by jefflill** [comment]
Thanks for the update.  I'll publish the nugets after I figure out a fix.

**Comment by jefflill** [comment]
@iain-cyborn: It's interesting that you ran into this too using our published nugets (which obviously haven't changed).  I wonder if this was caused by a Visual Studio update.  We haven't upgraded .NET SDKs recently.

**Comment by jefflill** [comment]
@johncburns1: I've fixed the original dynamic compilation issue by using the .NETStandard2.0 reference assembly from the [Basic.Reference.Assemblies](https://www.nuget.org/packages/Basic.Reference.Assemblies) for the ModelGen, Cadence and Temporal libraries and was able change these (and other) projects to target just .NetStandard2.0.  This will reduce the nuget packages sizes because we won't have 3-4 copies if the binaries any more.

Unfortunately, both the Cadence and Temporal unit tests are failing.  I investigated Cadence and found that `CadenceClient` isn't able to establish a connection to **cadence-proxy**.  I configured DEBUG mode and see:

1. `CadenceClient` launch **cadence-proxy**
2. The **cadence-proxy** CMD window displays
3. The proxy sends a **LogRequest (Initialization info)** message to the client and then it looks the proxy exits
4. The client receives the message and tries to reply but the proxy is not longer running so that fails

This all is a bit odd.  I don't believe the proxy code for either Cadence or Temporal has changed at all in several months and other than the dynamic compilation changes above, the C# side hasn't really changed recently either.

**Can you please have a look?**

Note that you'll need to run through the developer setup instructions for both the neonKUBE and neonCLOUD repos, including re-running the **build-env.cmd** batch files.  We've been adding support for 1Password secrets for CI/CD and other things.

**Comment by jefflill** [comment]
I believe the dynamic compilation issues are fixed.  I ended up creating a new **Neon.CSharp** library with a `CSharpHelper.RuntimeReferenceAssemblies` that implements the logic to return the correct reference assemblies for the current runtime environment.

This allows the **Cadence**, **Temporal**, and **ModelGen** assemblies to remain .NETStandard2.0.

I'm going to close this and continue tracking any remaining Cadence/Temporal proxy connection issues bact at #1199.
