### ISSUE TITLE
cluster setup: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1290]
I noticed this when rebuilding the Hyper-V ready-to-go image but it probably impacts normal setup as well.

We should probably address things like this before release especially because it looks like setup won't work when we upgrade to Kubernetes v22+.  It's probably worth reviewing the setup logs for other warnings like this.
``
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh

cd /lib/neonkube/helm

helm install openebs --namespace neon-storage -f openebs/values.yaml --set-string apiserver.image.organization="neon-registry.node.local" --set-string helper.image.organization="neon-registry.node.local" --set-string localprovisioner.image.organization="neon-registry.node.local" --set-string policies.monitoring.image.organization="neon-registry.node.local" --set-string snapshotOperator.controller.image.organization="neon-registry.node.local" --set-string snapshotOperator.provisioner.image.organization="neon-registry.node.local" --set-string provisioner.image.organization="neon-registry.node.local" --set-string ndm.image.organization="neon-registry.node.local" --set-string ndmOperator.image.organization="neon-registry.node.local" --set-string webhook.image.organization="neon-registry.node.local" --set-string jiva.image.organization="neon-registry.node.local" --set apiserver.replicas=1 --set provisioner.replicas=1 --set localprovisioner.replicas=1 --set snapshotOperator.replicas=1 --set ndmOperator.replicas=1 --set webhook.replicas=1 ./openebs

START=`date +%s`
DEPLOY_END=$((START+15))

until [ `helm status openebs --namespace neon-storage | grep "STATUS: deployed" | wc -l` -eq 1  ];
do
  if [ $((`date +%s`)) -gt $DEPLOY_END ]; then
    helm delete openebs || true
    exit 1
  fi
   sleep 1
done
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/cb0f4d70-dedb-443e-a6f5-475b48225a02/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-313aa00c-3d6b-489c-888a-db1fd3815c02" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-313aa00c-3d6b-489c-888a-db1fd3815c02" ; fi'
END [OK]
STDERR
    W1026 18:01:00.668089   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.668321   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.708303   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.708567   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.709074   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.709409   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.709579   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.710145   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.710348   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.710755   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.711026   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.711116   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.711317   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.716312   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:00.777664   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.791780   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.798981   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.819749   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.853540   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.882351   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.915820   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.952173   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.980374   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:02.996111   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:03.004658   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:03.015904   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:03.035593   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:03.044672   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:03.055051   25641 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
    W1026 18:01:03.894043   25641 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
    W1026 18:01:03.998158   25641 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
END [OK]
END-BUNDLE
----------------------------------------
S
``

**Comment by marcusbooyah** [comment]
DONE
