### ISSUE TITLE
openebs-provisoner crashing due to bad health probe?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1325]
I'm seeing **openebd-provisoner** crashes on a new Hyper-V cluster.  I rebuilt the container and hyper-v node images yesterday.  It looks like this may be due to an invalid health probe:
![image](https://user-images.githubusercontent.com/4908431/144102115-dc48b51f-608c-425f-9d9e-deee3e85f383.png)

![image](https://user-images.githubusercontent.com/4908431/144102155-8b7f8a9e-d95a-4b6d-8720-70b5efe0b3a1.png)

Pod logs include some possible errors but I'm betting these are normal:

![image](https://user-images.githubusercontent.com/4908431/144103249-e12def64-b823-4cfa-867d-3848e2e92512.png)

**Comment by marcusbooyah** [comment]
fixed
