### ISSUE TITLE
Minio: Unable to set [superadmin] policy

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1354]
Cluster setup is currently failing when configuring the minio **superadmin** policy:

![image.png](https://images.zenhubusercontent.com/604e69b902390ddc4494fba9/07a51b24-133b-449b-a4b0-88de46ea3176)

This is happening in `KubeSetup.Operations.InstallMinioAsync()`

I've commented out the failing code and added a **$todo(marcusbooyah)** command.

**Comment by marcusbooyah** [comment]
Fixed
