### ISSUE TITLE
Order the code signing certificate

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1369]
We need to purchase a code signing certificate for signing our app installers.

**Comment by jefflill** [comment]
It looks extended validation (EV) certs cost @319/year from COMODO and are maybe $70 cheaper from cut-rate providers.

https://comodosslstore.com/code-signing/comodo-ev-code-signing-certificate

There are some twists other than proving your company ownership:

* Although the ability to sign code is limited to the certificate lifespan (1-3 years), code signed by a certificate will be good indefinitely as long as we use a **timestamp** service while signing: [link](https://cheapsslsecurity.com/blog/what-is-time-stamping/)

* Private keys are delivered on a smartcard with a reader.  It is not possible to extract the provate key from this card.  This means that the card must be physically attached via USB to the computer signing the code, which will make CI/CD a bit tricky.

  It looks like it's possible to forward USB ports from the client workstation via remote desktop, but this would mean that only one person could remote in an do signing.  It looks like it is possible to do Hyper-V pass-thru from the host to a client VM, but that looks a bit tricky: [link](https://redmondmag.com/articles/2018/05/17/usb-passthrough-in-hyperv.aspx)

  Alternatively, we could deploy a small dedicated Windows machine to WowRacks dedicated to code signing.

**Comment by marcusbooyah** [comment]
DONE
