### ISSUE TITLE
I BROKE SSO: Internal cluster service port conventions?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1373]
I'm refactoring the neonKUBE services by removing the service map related code: #1372

I notice that the ports dashboard related services seem a bit confusing.  For example, **neon-sso-session-proxy** is assigned port **11000** and it's metrics are on **11001**.  I know that we're exposing this service as a nodeport on **11000** but does that mean that the service needs to be listening as a Kubernetes on this port?  Couldn't we configure this like:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: neon-sso-session-proxy
    meta.helm.sh/release-namespace: neon-system
  creationTimestamp: "2022-01-01T02:06:24Z"
  labels:
    app.kubernetes.io/instance: neon-sso-session-proxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neon-sso-session-proxy
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: neon-sso-session-proxy-0.1.0
  name: neon-sso-session-proxy
  namespace: neon-system
  resourceVersion: "3279"
  uid: 1a36f5b1-ba3e-4910-a902-8b29adeb63c1
spec:
  clusterIP: 10.253.198.230
  clusterIPs:
  - 10.253.198.230
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 11001           # <--- Why isn't this 80?
  - name: http-metrics
    port: 11002
    protocol: TCP
    targetPort: 11002           # <--- Why isn't this 81?
  selector:
    app.kubernetes.io/instance: neon-sso-session-proxy
    app.kubernetes.io/name: neon-sso-session-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

I assume that the Istio VirtualService is handling the node port exposure, so why have the service listen on different ports, now that service maps are gone.  It seems much simpler to just assume that services are listening within the container on HTTP port 80 and do the same at the Kubernetes service level (unless there's a good reason do do otherwise).

As for metrics, I need to do a bit of docmentation about how to use the built-in ASP.NET metrics on the same port as the web host and then we can get rid of the separate metrics port: #1221

**Comment by jefflill** [comment]
So it looks like I've screwed SSO up with these changes (SORRY!):

![image](https://user-images.githubusercontent.com/4908431/147843306-8a528383-ebb4-4f4e-af97-7469f5492be9.png)

I messed with this for an hour, so I'm going to throw this over the wall so you can have a look tomorrow so I can move on.  You'll have to let me know what I did wrong.

**Comment by marcusbooyah** [comment]
I FIXED SSO
