### ISSUE TITLE
Friends & Family release check-list

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1386]
Things to complete before a friendly release

- [x] neonDESKTOP
- [x] neon-cli and neonDESKTOP installer updates
    - [x] ready-to-go binaries
- [x] Cluster needs to work in 8GB RAM
- [x] minio
    - [x] configure bucket limit
    - [x] purge older data when bucket is to close to full (neon-cluster-operator?)
- [x] Extra credit:
    - [x] make neon-dashboard look nicer
    - [x] code signing certificate

**Comment by marcusbooyah** [comment]
DONE
