### ISSUE TITLE
groups: cannot find name for group ID 1337

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1389]
I've been noticing this warning/error when I exec into pods:

![image.png](https://images.zenhubusercontent.com/604e69b902390ddc4494fba9/e51f598c-8c88-4ceb-9edd-2c515544f232)

This seems to be coming from Istio deployments:

![image.png](https://images.zenhubusercontent.com/604e69b902390ddc4494fba9/79692c7c-f2ac-4872-acc0-78dbc4089e4b)

User 1337 doesn't exist on nodes which is why this is probably happening.

Should we create this user and group on the nodes or remove the runAsGroup/runAsUser elements from these deployments or is it OK to leave this alone?

One concern is that end-users will probably see this when they exec into their (Istio enabled) pods and the may become a time waster for users as well as a support overhead for us, even if the effect on the pod is benign.

**Comment by marcusbooyah** [comment]
Changed this to container user: 1000
