### ISSUE TITLE
Overlay neon-cli with new "kubectl" commands

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1413]
I just realized that it's very possible for neon-cli to implement new kubectl commands like:
```
neon config set-namespace foo
```
which is much nicer than
```
neon config set-context --current --namespace neon-system
```
This would be super easy to do but we'd want to somehow get this into the kubectl help.  One idea would be to duplicate the kubectl help to better integrate this into neon-cli which we'll track here:

#1345

**Comment by marcusbooyah** [comment]
DONE
