### ISSUE TITLE
Browser state getting in the way

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1418]
For now I made the bottom bar taller so that it doesn't get in the way, but it would be nice if we could remove this or something.

![image](https://user-images.githubusercontent.com/11889627/150005875-92b4e51c-47b7-4daa-97ec-b6efddb96de4.png)

**Comment by codelastnight** [comment]
I moved the buttons to the right side for a cleaner hot fix. I'm not sure if we can remove the link thing unless we change it directly in the browser itself.

**Comment by marcusbooyah** [comment]
DONE
