### ISSUE TITLE
REFACTOR: installer builds

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1420]
- [ ] We're currently publishing these apps as multi-file ready-to-run and then mixing them in the same setup target directory to reduce the size of our installers.  I'm not entirely sure this is a great idea.  Let's publish these as AOT single files for the installers but leave these as multi-file with no AOT for normal builds.

    - [ ] neonDESKTOP
    - [ ] neonCLI

- [ ] **pubcore** needs to support `--single-file` and `--ready-to-run` options

- [ ] It's confusing for the installers to be written the the **$env:NC_BUILD** folder (we actually have a conflict between **neon-assistant.exe** the installer and **neon-assistant.cmd** a CMD.EXE based shortcut to the **neon-assistant** binary already.  Let's relocate the installers to a new "$env:NC_BUILD\Installer" folder.

- [ ] Update **neoncloud-release.ps1** to pickup the install binaries from the new installers folder.

**Comment by marcusbooyah** [comment]
DONE
