### ISSUE TITLE
Cluster name review and tweaks?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1441]
Now that we're getting close to shipping, let's do a final review of names in the cluster.  I believe that we've been through deployment and namespace related names enough already, but we should also look at names for other things like secrets, volumes, etc.  This issue is a first cut at this.

---

### secrets

- [ ] **neon-monitor/citus:** we don't deploy any more.  Should this be named **postgres** or perhaps **neon-system-db**?  It's also unclear what this is for.  I assume contains the database login credentials.  This should be renamed to something like **neon-system-db-credentials**.
    - [ ] We should rename this secret to follow whatever convention we choose: **standby.neon-system-db.credentials.postgresql** and I'd probably prefer to add the **standby** to the end, replace any dots with dashes as our naming convention and remove the "postgres" references.  This doesn't seem to add much clarity and would be confusing if we ever switch to YugaByte, back to citus or something else.
- [ ] **neon-monitor/cortex:** unclear purpose
- [ ] **neon-monitor/loki:** unclear purpose
- [ ] **neon-store/minio:** unclear purpose
- [ ] **neon-storage/sh.helm.release.v1.openebs.v1:** what does the **"sh."** prefix mean?
- [ ] **neon-system/glauth:** unclear purpose
- [ ] **neon-system/kiali:** unclear purpose
- [ ] **neon-system/minio:** unclear purpose
- [ ] **neon-system/registry:** unclear purpose

What does the **sh.** prefix mean for all of these and are the version numbers actually necessary (they may be)?  I'm assuming that these are all created by the Harbor operator so they'll probably stay this way.

- [ ] **neon-system/sh.helm.release.v1.dex.v1**
- [ ] **neon-system/sh.helm.release.v1.glauth.v1**
- [ ] **neon-system/sh.helm.release.v1.kiali-operator.v1**
- [ ] **neon-system/sh.helm.release.v1.kubernetes-dashboard.v1**
- [ ] **neon-system/sh.helm.release.v1.minio.v1**
- [ ] **neon-system/sh.helm.release.v1.neon-cluster-operator.v1**
- [ ] **neon-system/sh.helm.release.v1.neon-dashboard.v1**
- [ ] **neon-system/sh.helm.release.v1.neon-node-agent.v1**
- [ ] **neon-system/sh.helm.release.v1.neon-redis.v1**
- [ ] **neon-system/sh.helm.release.v1.neon-sso-session-proxy.v1**
- [ ] **neon-system/sh.helm.release.v1.neon-sso.v1**
- [ ] **neon-system/sh.helm.release.v1.neon-system-db.v1**
- [ ] **neon-system/sh.helm.release.v1.node-problem-detector.v1**
- [ ] **neon-system/sh.helm.release.v1.registry-harbor.v1**
- [ ] **neon-system/sh.helm.release.v1.reloader.v1**

Here are some more non-specific secrets:

- [ ] **neon-system/operator-tls:** Is this secret used by all operators or a specific operator?
- [ ] **neon-system/operator-webhook-secret:** Same question here
- [ ] **neon-system/webhook-server-cert:** Implies that there's a central server handling all webhooks

...and finally:

- [ ] Why is **registry-trivy-reports** **PENDING**?  Is this a problem?

---

### services

- [ ] **neon-system/operator:** **_"One operator to rule them all!"_**  This probably explains the **operator** secret above.

    I thought this was the **neon-cluster-operator**, but it's actually a service for the **minio operator**?

- [ ] I notice that we're still exposing **Minio via a nodeport**.  We should no longer be doing this right, because we're routing dashboard though Istio Ingress, right?

```
kind: Service
apiVersion: v1
metadata:
  name: minio-nodeport
  namespace: neon-system
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 30006           # <--- should be doing this?
  selector:
    v1.min.io/tenant: neon-system
  type: NodePort
```

**Comment by marcusbooyah** [comment]
done
