### ISSUE TITLE
Deprecated Kubernetes API versions

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1442]
I took a closer look at cluster installation logs and have found several uses of deprecated api versions in custom resources.  These will no longer work when we move to Kubernetes v22+.

- [ ] `apiextensions.k8s.io/v1beta1 --> v1`
- [ ] `rbac.authorization.k8s.io/v1beta1 --> v1`
- [ ] `cert-manager.io/v1alpha2 --> v1`

I thought this was just going to be a search/replace thing but it looks like we may need to upgrade OpenEBS and edit some Helm templates as well.  So, let's defer this until we're actually upgrading to Kubernetes 23+

**Comment by marcusbooyah** [comment]
DONE
