### ISSUE TITLE
Hyper-V node prepare failed

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1451]
I just tried deploying a 3 node cluster on Hyper-V and the second worker VM was not running after cluster prepare.  I started the node manually and it started OK but the sysadmin password hadn't changed nor was the static IP address configured.

Unfortunately, we don't retain the prepare logs after setup starts.  The problem is that I've been copying and pasting the **neon-cli** commands into Cmdr and have them run in sequence.  cluster prepare must have failed by the setup command executed next anyway, removing the prepare logs.

- [x] Have cluster prepare create a `prepare-ok` file in the log folder when that operation succeeded and have cluster setup ensure that this file exists before proceeding.

I'm going to leave this open and watch for more cases like this.

**Comment by marcusbooyah** [comment]
Closing
