### ISSUE TITLE
Deprecate TlsCertificate?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1453]
Now that we've moved on to .NET 6+, we probably don't need `TlsCertificate` any more.  This was a hack that required an external tool to create and inspect certificates.  It would be much better to do this with just C# code, which is possible now.

I'm not sure how much `TlsCertificate` is being used.  One approach would be to retain it but re-implement the methods using pure C#.  

This blog post may help:

https://www.codeproject.com/Articles/5315010/How-to-Use-Certificates-in-ASP-NET-Core

**Comment by marcusbooyah** [comment]
Duplicate
