### ISSUE TITLE
Upgrade to Kubernetes 1.24+

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1457]
We've been on the 1.21 release for several months now.  We should upgrade to 1.23+ before releasing the first preview.

Looks like 1.24 is scheduled for **4/19/2022** and **1.24.0-beta.0** will be released in a few days on **3/30/2022**.  I think we should upgrade to the beta soon so we'll have some time to work through any kinks since we'll probably be releasing neonkube previews by late April.

https://github.com/kubernetes/sig-release/tree/master/releases/release-1.24

**Comment by marcusbooyah** [comment]
DONE
