### ISSUE TITLE
Prefix dashboard and other future public cluster domain names with "neon-" (or something)

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1467]
The idea here is that avoid conflicts with services that users may publish.  For example, we're currently using **https://dashboard.UUID.neoncluster.io** for the cluster dashboard.  I could easily see users wishing they could use this for **their** dashboard.  We should rename our URI for this to be **https://neon-dashboard.UUID.neoncluster.io** and then advise users that they should avoid subdomains prefixed by **neon-** to avoid conflicts.

- [x] Change this for all dashboards
- [ ] Update neon-desktop
- [x] Our cluster dashboard needs to be at: **neon-dashboard.UUID.neoncluster.io** not at **UUID.neoncluster.io**.  This allows users to use the root domain for their dashboard or whatever.
- [x] Other virtual services that need to be renamed:
    - [x] grafana --> neon-grafana
    - [x] registry --> neon-registry
    - [x] kiali --> neon-minio
    - [x] sso --> neon-sso

**Comment by marcusbooyah** [comment]
DONE
