### ISSUE TITLE
Optional cluster components for smaller host devices

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1492]
A basic premise for neonKUBE has been that we want a cluster running on a laptop to work exactly the same as it would when deployed to the cloud.  We've been working hard towards this goal for the past couple of years, but unfortunately this is not going to work for smaller host machines, like laptops with less than 16GiB of RAM and even on a machine that big, neonKUBE will be pegging 2 cores and leaving 6 GiB or less for Windows and other user applications.

The big contributors to this problem are Cortex and Minio with these requiring close to 1 GiB RAM each and Cortex consuming CPU when ingesting metrics.  @marcusbooyah has been working towards helping mitigate the metrics overhead but even with this, we're probably going to be stressing smaller host machines.

The idea is add a some _à la carte_ options for users so they can choose to omit some components.  I thing we should model this as a set of menu combinations as opposed to being purely à la carte because there will be dependencies between optional components and this will help make customer support easier by reducing the number of component combinations.

Here's a first cut at some menu combinations:

Slim
-----
This will be our lowest overhead cluster and should be pretty competitive with MiniKube on smaller machines.  I'm hoping this will be able to run with 2-4 GiB with minimal CPU.  This configuration could pair really well with Grafana Cloud.

Minio: **NOT INCLUDED**
Harbor: **NOT INCLUDED**
Loki: **NOT INCLUDED**
Cortex: **NOT INCLUDED**
Grafana: **NOT INCLUDED**

Combo
--------
This augments **Slim** by adding **Minio** (and optionally Harbor).  Hopefully this will run well with 4-5GiB RAM on smaller machines.

Minio: **INCLUDED**
Harbor: **OPTIONAL**
Loki: **NOT INCLUDED**
Cortex: **NOT INCLUDED**
Grafana: **NOT INCLUDED**

Supreme (full meal deal)
------------------------
This includes everything (with Harbor being optional) and is suitable for larger machines with 16 GiB RAM and a reasonable number of CPU cores.

Minio: **INCLUDED**
Harbor: **OPTIONAL**
Loki: **INCLUDED**
Cortex: **INCLUDED**
Grafana: **INCLUDED**

This seems like a reasonable tradeoff and we will probably end up having uses wish to disable things they're not using, even for production clusters and running well on a 16 GiB or even 8 GiB laptop would be glorious!

**Comment by marcusbooyah** [comment]
done
