### ISSUE TITLE
neoncloud.io: coming soon marketing site and logos

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1499]
Let's get started on a simple static marketing website at: **neoncloud.io**

Background:
-------------
**neoncloud.io** will be our primary marketing website and will be where users will sign up for accounts and will download the neon-desktop application (and optionally as a standalone neon-cli tool).

**portal.neon.cloud.io** is where users will manage their account and clusters.  This will be a Blazor site that we'll start working on this in a few weeks after we've spec'ed it out and have implemented some or all of the backend.

The product branding will be neon-kube and neon-cloud.  neon-kube refers to the underlying technology as well as the clusters users deploy.  neon-cloud refers to the place where users manage their clusters.  neon-desktop will also be a thing, but let's consider that to be under the neon-kube wing; I don't think that needs separate branding.

Tasks:
------

- [ ] Gatsby/WPEngine based
- [ ] Hosted as GitHub Pages
- [ ] Logos
    - [ ] neon-kube logo (a stylized cube)
    - [ ] neon-cloud logo (a stylized cloud, perhaps with a cube inside)
    - [ ] neon-forge logo (lower priority)
- [ ] Pages
    - [ ] Home/coming soon page

**Comment by marcusbooyah** [comment]
v1 is live at https://neonkube.io
