### ISSUE TITLE
Optional cluster features: and make some components optional (save 407 MiB?)

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1511]
Let's make some of the cluster components optional by adding a new record to the cluster definition.  I think we can probably reduce the RAM usage by quite a bit by removing some of the Harbor components that will probably not be used much, especially by small clusters.

I pulled the related RAM usage for Harbor related pods and it looks like we could save maybe 228 MiB by leaving out a few unimportant components:

![image.png](https://images.zenhubusercontent.com/604e69b902390ddc4494fba9/a3555aee-b854-433a-82a0-5dffe0684ec9)

This is probably worth doing.

[https://app.zenhub.com/files/92753252/89c631e9-0fdf-4fef-9f8b-1a5937e5ea5a/download](https://app.zenhub.com/files/92753252/89c631e9-0fdf-4fef-9f8b-1a5937e5ea5a/download)

**Comment by jefflill** [comment]
@marcusbooyah: I've added `FeatureOptions` to the cluster definition and default the optional components described above to not be installed.

You can use this to customize cluster setup.

**Comment by jefflill** [comment]
Let's make tempo/kiali and node-problem-detector optional too.  That saves asnother 179 MiB for a total of 407 MiB.

![image](https://user-images.githubusercontent.com/4908431/161784511-97aa7524-58b4-4170-ba15-01b67883e2ec.png)

We should also consider making **service mesh optional** too (linked to kiali?).  I wonder if that the source of lots of our metrics traffic?

**Comment by marcusbooyah** [comment]
This is done
