### ISSUE TITLE
Cluster dashboard issues

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1519]
- [x] Dashboard menu doesn't always close on Firefox.

    I'm not sure what the pattern it.  It seems to stay up most of the time after clicking a dashboard and clicking outside the menu (even in the bottom dashboard area itself) doesn't close the menu.

- [x] Remove the settings gear icon.  We don't currently have any settings.  We'll bring this back when we do (probably after we integrate neonCLOUD).

- [ ] We should also reduce the height of the bottom frame by unstacking the vertical Dashboard (label)/Name.  It doesn't make sense to take away this space from the user frame.

- [ ] Minio Dashboard:
    - [ ] (minor): I wonder if we should disable the **Storage/Drives** panel is possible.  This seems like a really bad idea for neonKUBER clusters.
    - [ ] **Invalid Credentials** I saw this the morning after your ski day and the dashboard didn't do much.  I wonder of the jwt expired or something.

- [ ] Harbor Dashboard SSO requires another user login.  I remember you telling me about this sometime back.  We will need to fix this eventually (perhaps by modifying the harbor dashboard code?)

**Comment by marcusbooyah** [comment]
Closing as duplicate.

#1597 covers Harbor
#1631 for bottom bar

Minio - let's revisit this.

SSO has seen a few fixes recently
