### ISSUE TITLE
Neon.SSH No override for static class SSHCredentials for FromUserPassword to use passphrase

### ISSUE THREAD

**Issue by TomT15** [nforgeio/neonKUBE#1521]
![image](https://user-images.githubusercontent.com/47607041/162447843-5ae64abe-e6c0-4fa7-b9f6-9aa7ce388b37.png)
instead of having an overload for the following:
![image](https://user-images.githubusercontent.com/47607041/162447940-e9cd08ec-4b15-4402-87ff-1e7e6b7e4fc9.png)

Maybe im missing something and could just replicate the code using renci, but the reason for moving away from renci is because the of the vulnerability. Any suggestions to get around this would be appreciated.

**Comment by TomT15** [comment]
also could use the following:
![image](https://user-images.githubusercontent.com/47607041/162448421-1e0b2d18-6a84-440e-aa09-ff352f31a919.png)

**Comment by TomT15** [comment]
Sorry... removing due to being commented in the wrong repo

**Comment by jefflill** [comment]
**FIXED:** Thanks for the contribution and sorry this has been languishing so long.

I've added an optional `passPhrase` parameter to the method.  Note also that we've pulled non-NEONKUBE libraries out of the neonKUBE repo to a new neonSDK repo in preparation for our neonKUBE release over the next month or two.  You can find the new neonSDK repo here: https://github.com/nforgeio/neonSDK

This change will be released as v3.0 nuget packages, probably in a few weeks (we need to fix some Cadence related unit tests).
