### ISSUE TITLE
Exception when client is null at Work.Activity

### ISSUE THREAD

**Issue by ViniciusSouza** [nforgeio/neonKUBE#1528]
After the client is disposed there was a thread that was still running and received an activity `InternalMessageTypes.ActivityStoppingRequest` from the temporal-proxy and because the client was null an Exception was throwed.

During the Client disposal if finishes the temporal-proxy process that send the StoppingRequest activity.

**Comment by jefflill** [comment]
@ViniciusSouza: I've merged these changes into master and will publish the nuget packages in a few days (we haven't done that in several months).

Note that we've deprecated the current Temporal implementation.  The current approach has been to use the GOLANG Temporal client as a proxy to the Temporal Server but this is really convoluted and imposes some fundamental limits we're not happy with.  The better approach is to build on the Rust API but this is going to be more work than we have time for right now.

We'll eventually need Temporal on .NET for ourselves but we're secretly hoping that the Temporal team implements an official .NET client.
