### ISSUE TITLE
etcd is being deployed on worker nodes

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1536]
@marcusbooyah: I'm trying to debug some issues with provisioning a 1-master 2-worker cluster to AWS and noticed that we're deploying 3 etcd pods as a daemon set, one on the master as well as each of the workers.

This doesn't make sense to me.  etcd pods should be constrained to just the master nodes, right?

**Comment by marcusbooyah** [comment]
Etcd has gone away withlatest loki/mimir update
