### ISSUE TITLE
Cluster setup failures: neon-sso-oauth2-proxy and neon-sso-session-proxy

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1569]
I'm seeing some cluster setup reliability problems:

![image.png](https://images.zenhubusercontent.com/604e69b902390ddc4494fba9/5707eed3-47a1-4f4c-95d6-46e2321c86b3)

I didn't see anything in the neon-sso-oauth2-proxy logs:

![image](https://user-images.githubusercontent.com/4908431/169741240-756c8e37-c655-47ea-9db4-8c661d729687.png)

**Comment by jefflill** [comment]
This doesn't happen every time we setup a cluster, perhaps 1 out of 5 attempts.

**Comment by marcusbooyah** [comment]
this works now
