### ISSUE TITLE
neon-dashboard: reload cluster info periodically

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1573]
@marcusbooyah: It looks like **neon-dashboard** loads the **cluster-info** configmap once when it starts and then never reloads it.  There's a couple problems with this:

1. The configmap may not actually exist yet.  This doesn't happen right now, but we don't want fragile and not handle this situation.

2. The dashboard will never see changes to the cluster info or even worse, two different dashboard service replicas might display different information, based on when the services started.

I recommend changing this by:

- [ ] Converting `Service.ClusterInfo` into a private field.
- [ ] Adding a private `AsyncMutex clusterInfoMutex;` field for thread safety
- [ ] And then adding a `Service.GetClusterInfoAsync()` method that returns the current information, fetching and caching it for a brief period (a few seconds).
- [ ] Hardening the home page to deal with `null` cluster information

Something like:

```
private ClusterInfo         clusterInfo;
private AsyncMutex          clusterInfoMutex      = new AsyncMutex();;
private DateTime            clusterInfoExpiresUtc = DateTime.MinValue;
private readonly TimeSpan   clusterInfoCacheTime  = TimeSpan.FromSeconds(5);

/// <summary>
/// Returns the current cluster information from the <see cref="KubeConfigMapName.ClusterInfo"/>
/// configmap for from a briefly cached value.
/// </summary>
/// <returns>The current <see cref="ClusterInfo"/> or <c>null</c> if the cluster information isn't currently available.</returns>
public async Task<ClusterInfo> GetClusterInfoAsync()
{
    using (await clusterInfoMutex.AcquireAsync())
    {
        var utcNow = DateTime.UtcNow;

        if (clusterInfo == null || utcNow > clusterInfoExpiresUtc)
        {
            // We don't have the cluster info yet or what we have has expired,
            // so attempt to fetch the value.  We're going to log any errors
            // and return NULL when the fetch fails.

            try
            {
                var configmap = await Startup.K8s.ReadNamespacedConfigMapAsync(KubeConfigMapName.ClusterInfo, KubeNamespace.NeonStatus);

                clusterInfo           = (new TypeSafeConfigMap<ClusterInfo>(configmap)).Config;
                clusterInfoExpiresUtc = DateTime.UtcNow + clusterInfoCacheTime;

                return clusterInfo;
            }
            catch (Exception e)
            {
                Log.LogError($"Cannot read configmap: {KubeConfigMapName.ClusterInfo}", e);

                return clusterInfo = null;
            }
        }
        else
        {
            return clusterInfo;
        }
    }
}
```

Other Refactoring
---

I know you just hacked out this initial version of **neon-dashboard** but it needs to be refactored a bit to avoid engineering debt:

- [ ] Looks like the `Startup.Svgs` field isn't being used and can be deleted
- [ ] It seems like the `Startup` class is doing too much right now.  Some of this initialization needs to relocate to your `NeonService` implementation:
    - [ ] Relocate the `Startup.K8s` property to your `NeonService` implementation.
    - [ ] Relocate all of the configmap loading to the service class as well, and expose these as properties.  The static `Program.Service` property holds the current service instance, so your `Startup` class can reference these properties vie `Program.Service.PROPERTY.
    - [ ] Be sure to convert synchronous calls to `Task.Result` or `Task.Wait()` into real async calls (see note below)

Task.Result and Task.Wait()
---

As a general rule, it's a best practice to never call `Task.Result` or `Task.Wait()` (like is happening in `Startup` right now), which means async operations should really be avoided in constructors:

https://montemagno.com/c-sharp-developers-stop-calling-dot-result/

One pattern to mitigate this is to implement a static async method like `public static Task<MyClass> MyClass.CreateAsync()` that implements the async parts before or after creating the instance.

The other pattern is to have the async part handled by another class (like in your service as I'm suggesting here).

Handle when clustermaps can't be retrieved.
---
We need our code to be resilient.  The current implementation will just throw exceptions and crash the service,

- [ ] At minimum, we should catch these exceptions and log something more useful, such as which configmap caused the failure.
- [ ] Ideally, the dashboard service would keep running in a degraded state and keep trying to read these configmaps so it can initialize itself properly.  This may be a bit tricky with your SSO initialization.

We should discuss the last one.

**Comment by marcusbooyah** [comment]
DONE
