### ISSUE TITLE
NeonService: log warning when settings cannot be parsed

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1601]
I don't believe we're doing this right now.  These APIs are generically typed to be able to parse different types of values like integers, booleans, doubles, enums, TimeSpans, etc. and include a default value to be used when the setting is missing or invalid.

We'll let missing values continue to be be handled as they are now but we should log a warning like this for bad values:

```
Setting [NAME=VALUE] is not a valid [System.TimeSpan].  Using the default [XYZ] value instead.
```

**Comment by marcusbooyah** [comment]
DONE
