### ISSUE TITLE
cluster-operator: recreate local harbor container registry CRD when missing

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1610]
It's possible for users to accidentally delete all `V1ContainerRegistry` resources, including the one referencing the local Harbor.  Doing this would mean that all nodes will no longer be able to pull from Harbor.

I was thinking about dealing with in the **neon-node-agent**'s container registry controller, but this seems better suited to **neon-cluster-operator** as part of it's cluster management role.  In this case, **neon-cluster-operator** would detect this and recreate the local container registry resource.

**Comment by marcusbooyah** [comment]
done
