### ISSUE TITLE
neon-cluster-operator needs a custom resource to manage settings

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1612]
- [x] V1NeonClusterOperator resource
    - [x] CA update schedule: CRON format?
    - [x] Security patch schedule: CRON format?
    - [x] Status where the operator can persist when it last performed operations, etc.
- [x] Detect missing harbor images and create nodetasks to have nodes push these
- [x] Add Priority class to Harbor pods: #1414

**Comment by marcusbooyah** [comment]
done
