### ISSUE TITLE
nuget-dev.neoncloud.io: needs a SSL certificate

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1621]
I just upgraded to Visual Studio 17.3 preview 2 and I'm seeing deprecation warnings when pulling packages from our private nuget repo.  Apparently, insecure access to package repos won't be allowed sometime in the future.

- [x] Update this service to have a Lets Encrypt certificate
- [x] Update the neonCLOUD **README.md** to change the package repo URI to HTTPS: https://nuget-dev.neoncloud.io/v3/index.json
- [x] Update our local Visual Studio package manager settings

@marcusbooyah: It seems like we have somewhat of a gap in our _"it just works"_ story for SSL.  My understanding is that we'll have to manually update our DNS by adding a record that Let's Encrypt will use to verify that we actually own the **neoncloud.io** domain, right?

It sure would be nice if this could happen automatically via API calls to the user's DNS provider.  We could combine this with automatically creating DNS entries for for services as well.

For some reason, I thought that GoDaddy didn't have and API for this, but they do:

https://developer.godaddy.com/doc/endpoint/domains

We should discuss.  This would be a cool future feature.

**Comment by marcusbooyah** [comment]
Here's a list of existing out of tree DNS providers: https://github.com/topics/cert-manager-webhook.

**Comment by jefflill** [comment]
**DONE**
