### ISSUE TITLE
Migrate to Dragonfly

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1633]
We can replace Redis and Memcached with Dragonfly: https://github.com/dragonflydb/dragonfly

**Comment by marcusbooyah** [comment]
Dragonfly does not yet support clustering - need to wait for that.

**Comment by jefflill** [comment]
**CLOSING:** It looks like this still doesn't support true clustering (after a year), just an emulated mode.

https://www.dragonflydb.io/docs/managing-dragonfly/clustermode

I'm going to close this; we have bigger fish to fry.  We can revisit if we run int performance issues.
