### ISSUE TITLE
Fully qualified cluster domain reference to Harbor in hello-world demo manifest?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1637]
@marcusbooyah: I notice that you include the fully qualified cluster domain in the container image URIs for the **hello-world** and **load-gen** deployments in this manifest.

![image](https://user-images.githubusercontent.com/4908431/177664002-ac8c1c95-e53d-48c7-a2ef-35e1841a4eea.png)

I hope this isn't required because this would be terribly inconvenient for users.  Can't we reference Harbor via a constant cluster URI?

**Comment by jefflill** [comment]
So I tried **neon-registry.node.local/library/hello-world** but that didn't work for some reason, even though the image seemed to be pulled correctly.

![image](https://user-images.githubusercontent.com/4908431/177665582-941ef6fd-5def-43d9-a2ca-5f89b856e55e.png)

**Comment by marcusbooyah** [comment]
Fixed
