### ISSUE TITLE
Add cluster ID to dashboard and have headend insert a dash between every 4th character when generating the ID

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1640]
Right now, **neon-desktop** is assuming that cluster domains are always formatted like:

`CLUSTER-ID.neoncluster.io`

this won't always be true.

- [x] We need to add the cluster ID to the cluster definition to de-tangle this
- [x] Add some dashes to the cluster ID so they'll be easier to read (eventually, I suspect that we'll need these ID from the user for customer support)
- [x] Domain should be a list of domains (I don't think this makes sense - discussed below)
- [x] The ID should also be included in the cluster info
- [ ] ...and be displayed in the cluster dashboard
- [x] Search for this bug link in neon-desktop and fix the place where we're parsing the domain
- [x] Add lat/lon fields

**Comment by jefflill** [comment]
@marcusbooyah: I'm not sure that making the domain a list really makes sense.

I think that one domain should be enough for users as far as our UX goes.  Having more than one of these will make it harder to implement things like dashboards.  For example, how would handle multiple domains:

* Display the first one
* Display all of them in a list (how would you format this flexibly)
* Would we limit the number domains a cluster can have?

I'm not sure I see a use case for multiple domains.  Is it really that useful for a cluster to have multiple domains like:

**my-cluster.foo.com
my-cluster.bar.com
cluster.foobar.com**

I think we conflated having a custom domain with needing this to be a list,  I don't think it needs to be this way:

* If the user doesn't specify a custom domain, the cluster domain in displayed in the dashboard and in the cluster definition will be the standard ***.neoncluster.io** domain.
* If the user specifies a domain and gives us credentials for their DNS provider, then we'll use that.

**NOTE:** We'll always create the ***.neoncluster.io** domain in either case.

We have the cluster ID so we can generate the ***.neoncluster.io** if we need it.  I've added the readonly `ClusterDefinition.NeonClusterDomain` that does exactly this,

**Comment by marcusbooyah** [comment]
this can be closed
