### ISSUE TITLE
XCP guest-tools not installed

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1656]
It seems that XCP VM tools is no longer being installed.

![image](https://user-images.githubusercontent.com/11889627/181091642-b2d88399-e977-4dc1-b51b-2ec8ca4120af.png)

**Comment by jefflill** [comment]
**neon-image** appears to be installing the **guest-tools** when building the XenServer node image.  I'll rebuild this image and see what's going on.

**Comment by jefflill** [comment]
So the tools don't appear to be installed in the XenServer base image.  I'll need to investigate.

**Comment by jefflill** [comment]
FIXED: for 0.7.0-alpha

**Comment by jefflill** [comment]
Looks like this has been fixed.
