### ISSUE TITLE
neon-cluster-operator: manage OpenTelemetry collector services

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1665]
**neon-cluster-operator** needs to create an OpenTelemetry service in each namespace where pods may emit traces.  Currently, these are deployed during cluster setup, but this needs to be dynamic so that telemetry can be collected for new namespaces created by users.

I think we should use annotations to control this with this service being deployed to all namespaces by default.

- [x] **Neon.Kube:** Add the `NeonAnnotation.cs` class and define `public string const DisableTelemetryCollector = "neonkube.io/disable-otel-collector";`
- [x] **neon-cluster-operator:** Add a new control loop that monitors namespaces and looking for the `"neonkube.io/disable-otel-collector` annotation.  If this is present any existing telemetry service will be deleted.  If this is not present, then we'll create the telemetry service in the namespace.
- [x] I think we should remove any services created by cluster setup and leave that to the operator.
- [x] @marcusbooyah: I'm trying to close out the `NeonService` logging/tracing features and I'm trying to make it easy for developers to enable tracing, especially for apps deployed to neonKUBE clusters and I'll need to know the **OTEL Collector** service name so I can configure the trace exporter.  I poked around the neonKUBE repo and I don't think we're actually deploying these services yet (which is OK because **neon-cluster-operator** should be managing this, as described above).

    We should settle on a name for this service now though.  I've defined the `NeonHelper.NeonKubeOtelCollectorName = "neon-otel-collector"` constant for this.  It's a bit weird to define this in **Neon.Common** but I want `NeonService` to be able to reference this in addition to other apps but I didn't want to make other code need to reference **Neon.Service**.

    I've also added the `NeonHelper.NeonKubeOtelCollectorUri = "http://neon-otel-collector"` constant.

    `NeonService` now has an option to automatically configure tracing.  One challenge is that the OTEL collector service may not be configured for the namespace where the `NeonService` is deployed.  I suspect that having tracing enabled without a collector enabled may become a problem for the service, with the exporter having to buffer traces and retrying exports without success.

    I'm going to mitigate this by having `NeonService` create a custom trace sampler and combine this with code that periodically does a DNS lookup for **neon-otel-collector**.  The sampler will reject all traces when the this lookup fails and will start forwarding traces again if the collector service reappears.
- [x] @marcusbooyah: I'm not going to otherwise configure trace sampling in `NeonService` which means that when tracing isn't disabled, OTEL will see all traces.  This may be a bad idea: **we should discuss**.

    I was thinking about defining a double environment variable where users could specify a value between **0...1** that controls the probability of a trace being sampled and I'd key this off of the parent trace ID.  This would work, but we'd need to understand how other folks are doing sampling such that everybody is sampling the same way so that Tempo will end up with complete traces for operations.  It would be cleaner to just let the OTEL collector (or Tempo) handle this, but this would be at the cost of having sending all traces there, which could be costly.

    **JEFF UPDATE:** We're going to go with this approach.

**Comment by marcusbooyah** [comment]
done
