### ISSUE TITLE
taints not being set on setup

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1666]
This is intermittent. We should probably use the k8s sdk for this anyway.

**Comment by jefflill** [comment]
We should have our cluster operator handle thing like this.  I think I
added a related issue for namespaces a week or two ago.

The rational is that setup is a one-time thing and clusters will be more
dynamic soon, supporting adding/removing nodes, etc.

**Comment by marcusbooyah** [comment]
done
