### ISSUE TITLE
Neon.Service logging broken

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1668]
All of the neon kube services are crashing because the `Service.Logger` is null.

![image](https://user-images.githubusercontent.com/11889627/187395979-eaf391c3-106d-41fb-b41a-efe0e2b9736d.png)

**Comment by jefflill** [comment]
Yeah, I hadn't integrated the logging changes into `NeonService` yet.  That is done now.

We have a couple more pending issues:

- [ ] `DiagnosticPools` is not looking like a great idea.  We're currently assuming that things like pool attributes can be returned back to the pool after calling `ILogger.Log()` but we really need to wait until all processors have completed processing the log.  The internal MSFT OpenTelemetry code does this with reference counts, but we don't have access to any of that.

    We may need to ditch pooling.  It also might be worth requesting a feature where loggers could configure a callback where logging extensions like us could return any assets.

- [ ] It would be nice to disable the message ASPNETCORE writes to the console when it starts out to avoid polluting the logs.  This can be accomplished setting the [environment variable](https://andrewlock.net/suppressing-the-startup-and-shutdown-messages-in-asp-net-core/#disabling-the-messages-using-an-environment-variable): `ASPNETCORE_SUPPRESSSTATUSMESSAGES=true`.

    An alternative is to create a custom [IHostApplicationLifetime](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0#ihostapplicationlifetime).  The nice thing about this is that we could associate this with our `ProcessTerminator` to signal ASP.NET to shutdown gracefully.  This is probably the best approach.

- [ ] @marcusbooyah saw some JSON logs that we're split along two lines of text.  I'm not sure how this can happen.

**Comment by jefflill** [comment]
Assigning to @marcusbooyah

**Comment by jefflill** [comment]
Closing this, we'll track the remaining issue at #1675
