### ISSUE TITLE
Azure: MissingSubscriptionRegistration

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1670]
Azure.RequestFailedException: 'The subscription is not registered to use namespace 'Microsoft.Compute'. See https://aka.ms/rps-not-found for how to register subscriptions.
Status: 409 (Conflict)
ErrorCode: MissingSubscriptionRegistration

**Comment by jefflill** [comment]
**CLOSING:** This issue is super old and we've been able to deploy Azure clusters from the staged and marketplace images.
