### ISSUE TITLE
Azure disk ext4

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1674]
I just set up an Azure cluster and the openebs disks were formatted ext4 and couldn't be added to the cstor pool

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"admission-webhook.cstor.openebs.io\" denied the request: invalid cspc specification: invalid pool spec: block device has file system {ext4}","reason":"BadRequest","code":422}

**Comment by jefflill** [comment]
@marcusbooyah fixed this
