### ISSUE TITLE
Headend modelgen client

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1686]
What we need here is to generate the headend client from new classes defined in the **Neon.Kube.Models** library and then convert the ad hoc `JsonClient` based calls scattered through the code to use the new generated client.  This will will be type-safe and also handle things like retries and API versioning.

@marcusbooyah: I've finished the **ModelGen** changes to support the `[ApiVersion]` attribute.  It's a pretty complete implementation; we only support passing **api-version** as a query parameter though (we don't currently support specifying versions in the URI path).  Here's more information on the implementation:

https://github.com/nforgeio/neonSDK/issues/24

Let's make this client nice by adding subclients for **Cluster** and **ClusterSetup**.

**Comment by marcusbooyah** [comment]
DONE
