### ISSUE TITLE
neon-node-agent isn't starting

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1704]
Something bad happened since @marcusbooyah munged this or due to my port to **net7.0**.

I've temporarily commented this out from cluster setup.

**Comment by jefflill** [comment]
@marcusbooyah: I took a quick look: the container image looks fine and I can start the thing in Docker, so the we're using the correct ASPNET base image,

I'm seeing an exception when setting up a watch, but that's probably OK since my quick check isn't running in a cluster.

**Comment by marcusbooyah** [comment]
It's working now
