### ISSUE TITLE
Harbor: cannot push docker images with layers larger than 2gb

### ISSUE THREAD

**Issue by maddadder** [nforgeio/neonKUBE#1707]
Steps to reproduce
1. create a docker image that includes a large enough file such that the layer size above 2gb
2. push the image through the istio gateway via 
docker-compose build
docker push neon-registry.18e7-091a-7bb4-d81e.neoncluster.io/project/my-app:1.0.27
3. 0aae74a6be18: Pushing [=================================================> ]  1.995GB/2.125GB
4. 0aae74a6be18: Retrying in 5 seconds
5. Error in registry-harbor-harbor-registry in the neon-system namespace: 
- unknown error completing upload: s3aws: ServiceUnavailable: Service Unavailable status code: 503,

minio-ss-0-0 was giving me this error:
API: SYSTEM()
Time: 03:43:13 UTC 11/12/2022
DeploymentID: f67c00ed-a9ad-4117-aa73-89695b031e72
Error: Unable to initialize storage class config: Standard storage class parity 3 should be less than or equal to 2 (*fmt.wrapError)
      10: internal/logger/logger.go:278:logger.LogIf()
       9: cmd/config-current.go:725:cmd.applyDynamicConfigForSubSys()
       8: cmd/config-current.go:756:cmd.applyDynamicConfig()
       7: cmd/config-current.go:618:cmd.lookupConfigs()
       6: cmd/config-current.go:871:cmd.loadConfig()
       5: cmd/config.go:235:cmd.initConfig()
       4: cmd/config.go:195:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:404:cmd.initConfigSubsystem()
       2: cmd/server-main.go:371:cmd.initServer()
       1: cmd/server-main.go:552:cmd.serverMain()
 You are running an older version of MinIO released 4 months ago 
 Update: Run `mc admin update` 

I then changed CRDs > tenants > minio from:
- name: MINIO_STORAGE_CLASS_STANDARD
   value: EC:3
   
to:

- name: MINIO_STORAGE_CLASS_STANDARD
  value: EC:2

Which seemed to fix the error, but I still can't push images larger than 2gb

Then I saw OOMKilled on minio-ss-0-0 at the same time of 0aae74a6be18: Retrying in 5 seconds
I increased the memory limits in CRDs > tenants > minio from 768Mb to 1Gi and I was then able to upload a 2gb layer.

**Comment by jefflill** [comment]
**CLOSING:** I don't think we can do anything about this.
