### ISSUE TITLE
Cluster Minio tenant is wide open?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1715]
It looks like the cluster Minio tenant has blank credentials.  This means that any pod in the cluster could mess with our buckets.

![image](https://user-images.githubusercontent.com/4908431/202743822-505ac066-f922-4192-9fc7-36df274fc14e.png)

Imaging this insidious scenario:

1. A hacker decides to target neonKUBE clusters
2. They publish a useful looking container that actually does bad things to cluster Minio buckets
3. ...like modifying existing container images to do something bad
4. ...or just deleting objects

We really need to secure this:

@marcusbooyah: Could this be a easy as generating these security keys during cluster setup?  Are consumers like Harbor configured to reference the secret?

**Comment by marcusbooyah** [comment]
This is being set by setup, it's not wide open.
