### ISSUE TITLE
SsoConnector for dashboard auth?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1731]
I've removed the `SsoConnectors** property from the cluster definition since it's not really baked as a feature yet.

@marcusbooyah says that he was using this to ensure that auth for cluster dashboards would work.  He said that the local connector was being added to this in cluster prepare somewhere but I can't find that code.

@marcusbooyah: I've restored but commented out the code that provisions the SSO connectors in **KubeSetup.Operations.cs**.  I think you'll need to tweak this code to provision the single connector.

**Comment by marcusbooyah** [comment]
This is working
