### ISSUE TITLE
Push headend server update to the headend cluster

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1738]
@marcusbooyah: I've made some changes to the headend service to support the new staging and release S3 buckets:

**neonkube-stage**
**neonkube-release**

These changes have been pushed to the **master branches**.

When you have the chance, can you push this to the headend cluster and also remove the two **$debug(jefflill)** marked code from **KubeVersions.cs** in neonKUBE?  These temporarily hard code the new S3 buckets in the URI returned rather than actually calling the headend.

Just remove the code lines between the: `//#################################` comments.

**Comment by jefflill** [comment]
Hold off on this until I have a chance to push the latest refactor to master.

**Comment by marcusbooyah** [comment]
done
