### ISSUE TITLE
Possible memory leak and race condition in LockProvider

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [nforgeio/neonKUBE#1741]
I [had made a PR](https://github.com/nforgeio/neonKUBE/pull/1737) to switch the LockProvider to a library I wrote in order to make it more performant, however changes were done to LockProvider instead so I closed the PR understanding you wanted to take a different direction. Yet, I've now noticed that the LockProvider seems to have both a memory leak and a race condition.

The code is making use of a ConcurrentDictionary, which despite that there is a method to remove items from this dictionary does not seem to have any references (therefore for every key you add, it stays there permanently in memory, hence the memory leak). The value of the dictionary though is also a SemaphoreSlim, which when released is re-added to the pool. So what could happen? Off the top of my head I see a problem (I may have a mistake here, it's a bit tricky to tell):

Thread A has key "ABC" and obtains the lock, While it's not yet disposed, Thread B also goes in with key "ABC". The item is in the dictionary, so the GetOrAdd returns the same SemaphoreSlim. Thread B has to wait until thread A releases the SemaphoreSlim. Thread A now finishes, releases the SemaphoreSlim and puts it back into the pool. So now that SemaphoreSlim that Thread B is using is also in the pool. In comes Thread C with key "DEF", adds an item to the dictionary with the pooled object returned from Thread A. So now, thread C despite having a different key to thread B is unable to do anything because it has to wait on Thread B.

**Comment by jefflill** [comment]
Thanks for reporting this!

This inspired @marcusbooyah to have a closer look at this and he's been doing some refactoring and other TLC.  This library is currently intended for our internal use only but we do expect to do some more cleanup, perhaps some refactoring (renaming types etc) plus documentation and relocate this to our https://github.com/nforgeio/neonSDK repo and publish as a public nuget package in maybe a month or two.

We really were hoping that Microsoft (or somebody else) would write a proper .NET Operator SDK but ended up having to roll our own.  We tried https://github.com/buehler/dotnet-operator-sdk out last year but had trouble getting it to work.

**Comment by MarkCiliaVincenti** [comment]
Taking care of all race conditions and optimising for performance / lower allocations at the same time can be tricky. This is why I wrote AsyncKeyedLock in the first place. It is now stable and used in a lot of production projects. You could add in the dependency and save yourself a few headaches :)

**Comment by jefflill** [comment]
@MarkCiliaVincenti: Thanks for the heads up on all of this.

@marcusbooyah: Perhaps we should use Mark's nuget.

**Comment by MarkCiliaVincenti** [comment]
This has been merged. Closing issue.
