### ISSUE TITLE
Experiment: LGTM stack ephemeral single binary

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1749]
For smaller clusters we can probably save a significant amount of memory by running Loki, Mimir and Tempo as single binary. Also make storing data in Minio optional as that will also save on memory.

**Comment by jefflill** [comment]
**CLOSING:** We may get some benefit from porting to [Alloy](https://grafana.com/docs/alloy/latest/tasks/migrate/from-operator/) but we're not going to do anything else.
