### ISSUE TITLE
XCP VM tools

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1761]
VM tools are not getting installed for XCP/XenServer nodes.

**Comment by jefflill** [comment]
**CLOSING:** These are being installed but XenCenter seems to report that they aren't installed for more advanced CPUs with better virtualization capabilities.

**Comment by jefflill** [comment]
Have yet another look at this.

**Comment by jefflill** [comment]
Required **XenServerImageHost** changes:

- [ ] There's no need to uninstall **hv-kvp-daemon.service**.  This is no longer installed.
- [ ] We're mounting the guest-tools ISO from **/dev/dvd**; this needs to be **/dev/cdrom**

**Comment by jefflill** [comment]
**FIXED**
