### ISSUE TITLE
KeyExchangeFailed

### ISSUE THREAD

**Issue by Spinks90** [nforgeio/neonKUBE#1772]
I'm connecting to an external SFTP Server. I can connect using WinSCP which gives me the following information:
```
File transfer protocol = SFTP-6
Cryptographic protocol = SSH-2
SSH implementation = CerberusFTPServer_12.0 FIPS
Encryption algorithm = AES-256 SDCTR (AES-NI accelerated)
Server host key algorithm = ssh-rsa 2048
```

Trying to connect I get the following error
```
Renci.SshNet.Common.SshConnectionException: 'The connection was closed by the server: Key exchange failed: Could not agree on key exchange parameters (KeyExchangeFailed).
```

I'm using the latest version of `Neon.SSH.NET` which is `2.11.1` at this time.

Thank you.

**Comment by Spinks90** [comment]
Hey Marcus,

Here is an example of the code, I've hidden the credentials:

```
        var connectionInfo = new ConnectionInfo("example.com", "someuserhere", new PasswordAuthenticationMethod("someuserhere", "apassword"));

        using (var client = new SftpClient(connectionInfo))
        {
            client.Connect();

            var yy = client.ListDirectory("/");
        }
```

The code is throwing an exception on `client.Connect();` but using the same credentials in WinSCP works.

If I use the same code above for different SFTP Server then it connects fine.

**Comment by jefflill** [comment]
**CLOSING**
