### ISSUE TITLE
VMs failing due to I/O error related to fd0

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#431]
I saw this yesterday, and today as well. All my VMs are showing this, and my Kubernetes cluster is unreachable.

`C:\Users\Marcus Bowyer
λ kubectl get pods --all-namespaces

Unable to connect to the server: dial tcp 10.50.0.100:6443: connectex: No connection could be made because the target machine actively refused it.`

This may be a fix: https://askubuntu.com/questions/719058/blk-update-request-i-o-error-dev-fd0-sector-0

![image](https://user-images.githubusercontent.com/11889627/52367788-b74b2580-2a01-11e9-9a58-1e6b1b5444a2.png)

**Comment by jefflill** [comment]
Fixed this by adding this to `node-setup.sh`:
```
sudo rmmod floppy
echo "blacklist floppy" | sudo tee /etc/modprobe.d/blacklist-floppy.conf
sudo dpkg-reconfigure initramfs-tools
```
