### ISSUE TITLE
Resource creation failed

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#452]
I'm getting the following error message when trying to create a resource using the Kubernetes dashboard via the neonKUBE proxy:

> Deploying file has failed
> 
> [InvalidOperationException]: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.

**Comment by jefflill** [comment]
This bug surfaces whenever the dashboard performs a POST (and probably also PUT) request.

There were a couple bugs resulting in the `Content-Type` and `Content-Length` headers not being relayed to the dashboard service for these cases.
