### ISSUE TITLE
neon vault edit does not work with notepad++

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#468]
When the editor is set to use notepad++, the neon vault edit command exits after opening the editor, rather than staying alive until the editor is closed.

**Comment by marcusbooyah** [comment]
I am also seeing the same behavior with Atom.

**Comment by marcusbooyah** [comment]
cmd /k "C:\Program Files (x86)\Notepad++\notepad++.exe" -multiInst secrets.yaml

**Comment by jefflill** [comment]
FIXED
