### ISSUE TITLE
Godoc generation for all exposed methods, variables, interfaces, and structs

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#508]
Using Godoc generation tool to generate clear and concise godocs from my current documentation.  This will be good because then the docs can be published to Godoc and be a valuable resource for users of the cadence-proxy library in the future.

**Comment by jefflill** [comment]
This is super low priority and is probably not worth putting any time into.  We need to get this Cadence thing done so we can move on to actual Loopie service code.  There are two reasons why this isn't important:

1. Nobody but the two of us (and perhaps a future neonKUBE developer will ever care about the API.
2. The "API" here is actually just the messages we're sending back and forth and perhaps the command line I pass to the cadence-proxy.  There is really is no API besides this.

I'm going to go ahead and close this.
