### ISSUE TITLE
Visual Studio Golang setup instructions

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#509]
Write clear and concise constructions for configuring visual studio code for stand alone golang projects and golang projects within larger projects that may have a different code base.  Also configuration for the golang linter, debugger, inferGopath, auto completion, vetting, and auto build.

**Comment by jefflill** [comment]
@johncburns1; I've tweaked `$/Doc/DEVELOPER.md` **step 11** a bit,  You should add the additional steps required to setup VS Code for this, etc.

**Comment by jefflill** [comment]
I don't believe there are any additional steps so I'm closing this.
