### ISSUE TITLE
#3: Cadence Scenario: Baby workflow

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#512]
### Note to JACK:

I realized this is going to need a bit of rework as I've been designing the .NET API.  I'm going to document the changes here over the weekend.

- [x] The `NewWorkerRequest` message adds the boolean `IsWorkflow` property that indicates whether we're registering a workflow vs. an activity worker.  You'll need to call `RegisterWorkflowWithOptions()` when this is **true** and `RegisterActivityWithOptions()` when this is **false**.

- [x] The `NewWorkerRequest` message adds the string `Name` property.  This is the name you'll pass in the workflow or activity options.

---

Design Notes:

* I've found this (new?) site that does a much better job at describing how to use Cadence:

  https://cadenceworkflow.io/docs/

* We're going to model the .NET API on the GOLANG client API rather than on the Java based client because the Java client seems overly complex and also seems to be tied directly to threads (including using thread local variables).  We're going to base our API on .NET Tasks and async methods.

* Messages are going to need to be able to serialize complex types as JSON.  After digging into this further, there are more situations where complex types will be transferred between the cadence-client and cadence-proxy than I had originally thought.

* To keep things simple, the cadence-proxy will implement all workflows and activities such that they all take a single byte array parameter and return a byte array result (and possible error).  The cadence-client will implement multiple typed parameters and typed results for the .NET workflow applications, but these will be serialized into the byte arrays for interactions with the cadence-proxy.

* Here's what I'd like to accomplish for this scenario:

  - [ ] Register a workflow that simply returns a value (no activities)
  - [ ] Register an activity handler (with activity options)
  - [ ] Verify that errors can be returned by the workflow and activity handlers.
  - [ ] Query for the state, history and workflow result.

I think that's it; we're not going to try to handle activities, retries, signals, or anything else for this scenario.

---

### cadence-client prerequisites

Implement these new messages:

- [x] `ProxyMessage` needs methods to serialize and deserialize complex types as JSON.
- [x] `IRetryPolicy` and it's implementations need an optional timeout.  We'll also need an extension method that serializes this into a form that the cadence-proxy can parse easily.
- [x] `WorkflowRegisterRequest`
- [x] `WorkflowRegisterReply`
- [x] `WorkflowExecuteRequest`
- [x] `WorkflowExecuteReply`
- [x] `WorkflowInvokeRequest`
- [x] `WorkflowInvokeReply`
- [x] `NewWorkerRequest`
- [x] `NewWorkerReply`
- [x] `StopWorkerRequest`
- [x] `StopWorkerReply`
- [x] Add `Timeout` property to `ProxyRequest`.

Follow up tasks:

- [x] I think we're going to need an `GoError` type that encapsulates all of the error related properties (need to speak to Jack about this).
- [ ] Actually implement the API.

### cadence-proxy prerequisites

You'll need to support several new messages.  Some of these have complex properties encoded as JSON.  I tried to make these types match the Cadence GOLANG implementations but I'm not sure about actual property names Cadence is going to use for serialization so you may need to update the `[JsonProperty]` attributes to match what Cadence expects.

- [x] Support JSON properties.
- [x] `WorkflowRegisterRequest`
- [x] `WorkflowRegisterReply`
- [x] `WorkflowContextRequest` **note:** renamed `WorkflowContextId --> ContextId`
- [x] `WorkflowContextReply` **note:** renamed `WorkflowContextId --> ContextId`
- [x] `WorkflowExecuteRequest`
- [x] `WorkflowExecuteReply` **note:** Replaced `Result` property with `Execution`
- [x] `WorkflowInvokeRequest`
- [x] `WorkflowExecuteReply`
- [x] `WorkflowInvokeRequest`
- [x] `WorkflowInvokeReply`
- [x] `NewWorkerRequest`
- [x] `NewWorkerReply`
- [x] `StopWorkerRequest`
- [x] `StopWorkerReply`
- [x] Add `Timeout` property to `ProxyRequest`.

### cadence-proxy implementation details

You're going to need a couple dictionaries to track things:

* **workers:** Maps a `long WorkerId` to the `Worker` returned by the Cadence `NewWorker()` function.  We'll need this to implement the `StopWorkerRequest` as described below.

* **workflowContexts:** Maps a `long ContextId` to a Cadence context passed to the Cadence workflow functions you'll be creating.  The **cadence-client** will use context IDs to refer to specific workflow contexts when performing workflow actions.

- [x] **NewWorkerRequest:** You'll need to call the Cadence `NewWorker()` function when you receive this which will return a `Worker` object.  You need to:

  a. Generate a new long `WorkerId`.
  b. Persist the `Worker` instance into your **workers** table (using the `WorkerId` as the key)
  c. Call the `Run()` function on the `Worker` returned by Cadence.
  d. Send a `NewWorkerReply` back to the **cadency-client** including the `WorkerId`.

- [x] **StopWorkerRequest:** This message is designed to stop a worker registered with Cadence (so it'll stop receiving requests to execute workflows and activities).  This message will include a `WorkerId`.  You'll need to:

  a. Lookup the `Worker` with this ID in your **workers** table
  b. If the **workers** table does not have a worker mapped to the `WorkerId` then just send a `StopWorkerReply` with `Error.String = "EntityNotExistsError"` and skip the remaining steps below.
  b. Call its `Stop()` method, remove the worker from the **workers** table
  c. Send a `StopWorkerReply` back to the **cadence-client**.

- [x] **WorkflowRegisterRequest:** You'll need call the Cadence `RegisterWorkflowWithOptions()` function when you receive this message:

  a. Create a new Workflow function (described below)
  b. Call `RegisterWorkflowWithOptions()` passing the new workflow function
  c. Send a `WorkflowRegisterReply` back to the **cadence-client**.

  This workflow function will be called by Cadence whenever it has a workflow that needs us to execute.  Your workflow function needs to do the following:

  a. Generate a new `WorkflowContextId`
  b. Define a new struct called something like `WorkflowExecutionContext` that holds a Cadence workflow context as well as promise/future that will complete when the workflow execution finishes.
  b. Save the context your workflow function received from Cadence to your **workflowContexts** table using the `WorkflowContextId` as the key.
  c. Send a `WorkflowInvokeRequest` to the **cadence-client**, including the argument bytes received by your function as well as the new `WorkflowContextId`.
  
- [x] **WorkflowInvokeReply:** You'll receive this from the **cadence-client** when it completes executing the workflow identified by `WorkflowContextId`:

  a. Use `WorkflowContextId` to lookup the context in your **workflowContexts** table.
  b. If the **workflowContexts** table does not have a context mapped to the `WorkflowContextId` then just skip the remaining steps below.
  c. If `WorkflowInvokeReply` has a null `Error` property, then signal the context promise completion and have it return the `WorkflowInvokeReply.Result` bytes.
  d. If `WorkflowInvokeReply` reports an error, then signal the context promise completion and have it return the error.
  e. Remove the context from the **workflowContexts** table.
  
  **NOTE:** You may not see a `WorkflowInvokeReply` for sometime (perhaps a very long time).
  **NOTE:** Take care not to hold onto any thread synchronization locks for longer than you absolutely have to.

**Comment by jefflill** [comment]
@johncburns1: You can go ahead and begin implementation and echo testing of these new messages.  I've pushed all of my changes to the CADENCE branch.

**Comment by johncburns1** [comment]
Completed!!!
