### ISSUE TITLE
Cluster setup: SSH timeouts out cluster join

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#516]
When creating a cluster, I saw an SSH timeout exception when sending the worker join command. I restarted the cluster setup, but ended up with one less worker than I should have had.

**Comment by jefflill** [comment]
@marcusbooyah: Next time you see this can you please add the exception details and/or the relevant section from the setup logs for the node join failed for?

**Comment by jefflill** [comment]
I'm guessing that the `kubeadm` command is timing out and not the SSH session invoking the command since we have no additional details.  I've added code to retry 5 times after waiting 5 seconds after each failed attempt.  Hopefully this fixes the problem.
