### ISSUE TITLE
Ceph pods not being deleted after host failure

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#518]
In this example, worker-0 was shut down. This resulted in all the pods that were running there to be re-scheduled onto other hosts. The problem is that the pods mounting Ceph block storage would not be able to start since the old pods were never deleted, and still had the volume 'mounted'

![image](https://user-images.githubusercontent.com/11889627/57406466-a2636700-7195-11e9-95aa-8777d1e0a872.png)

**Comment by marcusbooyah** [comment]
Looks like this may be fixed in Rook 1.1, so we will wait for it.

https://github.com/rook/rook/issues/1507

**Comment by marcusbooyah** [comment]
To cleanup after a host failure reboot the stuck VM and then SSH to it. You need to remove all volume paths for orphaned pods. Run the following for all instances of orphaned pods/volumes:

```
root@worker-1:/etc/systemd# journalctl -xe | grep "Orphaned pod"
Jun 11 22:23:44 worker-1 kubelet[858]: E0611 22:23:44.475267     858 kubelet_volumes.go:154] Orphaned pod "0c1b5df4-72a6-11e9-934b-ba810a302026" found, but volume paths are still present on disk : There were a total of 4 errors similar to this. Turn up verbosity to see them.
root@worker-1:/etc/systemd# rm -rf /var/lib/kubelet/pods/0c1b5df4-72a6-11e9-934b-ba810a302026/volumes/
```

**Comment by marcusbooyah** [comment]
This is still alpha, but might be a/the solution: https://rook.io/docs/rook/v1.0/ceph-csi-drivers.html

**Comment by jefflill** [comment]
I’m going to close this since it’s been a year and I’m not sure Ceph is important to us anymore.
