### ISSUE TITLE
Orphaned pod volumes hang around preventing new pods to be created.

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#520]
This happened after I tested taking down a host node. One of the other workers became over subscribed and eventually blew up (Calico was not responding). After bringing up all hosts again, I was seeing the error:

> Orphaned pod "a97aff7b-71bc-11e9-9983-ba810a302026" found, but volume paths are still present on disk

Related k8s issue: https://github.com/kubernetes/kubernetes/issues/60987

**Comment by jefflill** [comment]
@marcusbooyah: This is fixed now, right?

**Comment by jefflill** [comment]
Addressed with OpenEBS updates.
