### ISSUE TITLE
Cadence loose ends

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#525]
#488: Root issue

### Misc Loose Ends

- [x] We're going to need a `StartWorker()` method and related messages where the Cadence application can register the worker to run in a specific domain and task list.

- [ ] We're currently ignoring the `MetricsScope` parameters.  We need to figure out how these work and implement them.

- [ ] Need to figure out workflow and perhaps activity logging for the .NET side.  We'll need to handle both workflow and activity logging.

- [ ] Throw a (`CadenceDisconnectedException` or something) for all pending .NET operations when cadence-proxy fails a heartbeat.

- [ ] Workflow context can be cancelled.  I'm not entirely sure how this works yet (a channel gets closed?).  The **cadence-proxy** will need to send a notification message.

- [ ] Workflow stack trace?  Is there any way we could get the .NET stack traces into the history?

- [x] The current .NET `CadenceConnection` class actually corresponds to the Cadence **client** concept, so perhaps we should rename `CadenceConnection --> CadenceClient`.  I'm also going to integrate all functionality into this class rather than having separate classes for base client functionality, another class for workflow specific methods,...

- [x] I'm not entirely sure about how the [WithValue()](https://godoc.org/go.uber.org/cadence/internal#WithValue) method works.  It looks like it might be useful for the GOLANG API because there really isn't a convenient place to store internal workflow state by default, other than the context.  For the .NET API, workflows are always associated with a `Workflow` derived class where internal state can be stored.  I'm leaving this open so I can come back to verify that I actually understand this before closing the issue.

### Workflow implementation details

I believe these are the operations we'll need to support end-to-end.  Not as bad as I thought it would be.

- [ ] connection: [EnableVerboseLogging](https://godoc.org/go.uber.org/cadence/internal#EnableVerboseLogging)

- [x] workflow: [GetHeartbeatDetails](https://godoc.org/go.uber.org/cadence/internal#GetHeartbeatDetails)

- [x] workflow: [GetLastCompletionResult](https://godoc.org/go.uber.org/cadence/internal#GetLastCompletionResult). 

- [x] workflow: [GetWorkerStopChannel](https://godoc.org/go.uber.org/cadence/internal#GetWorkerStopChannel)

  Cadence uses this to notify an activity that it should terminate gracefully because the worker is being stopped.  We should have the **cadence-proxy** always monitor this and send a notification message to the **cadence-client** when the channel is closed.

- [x] workflow: [HasLastCompletionResult](https://godoc.org/go.uber.org/cadence/internal#HasLastCompletionResult)

  This should be passed viathe `WorkflowInvokeRequest` message and exposed as a read/only property on the context.  This value will not change as the workflow runs.

- [ ] workflow: [IsReplaying](https://godoc.org/go.uber.org/cadence/internal#IsReplaying)

  Another read/only property passed via `WorkflowInvokeRequest`.

- [x] workflow: [MutableSideEffect](https://godoc.org/go.uber.org/cadence/internal#MutableSideEffect)

- [x] workflow: [NewDisconnectedContext](https://godoc.org/go.uber.org/cadence/internal#NewDisconnectedContext)

  We'll need new messages for this so the **cadence-client** can have the **cadence-proxy** create and manage a new context.  This context will be disconnected from any workflow so I'm not entirely sure how we'll manage its life-cycle.  I suppose the **cadence-proxy** can manage a dictionary of disconnected contexts or manage these somehow in the same workflow table.  On the **cadence-client** side, we could make the context disposable and on disposal, send a message to the **cadence-proxy** having it remove the context.

- [x] workflow: [Now](https://godoc.org/go.uber.org/cadence/internal#Now)

- [x] workflow: [RecordActivityHeartbeat](https://godoc.org/go.uber.org/cadence/internal#RecordActivityHeartbeat)

- [x] workflow; [RegisterActivityWithOptions](https://godoc.org/go.uber.org/cadence/internal#RegisterActivityWithOptions)

  It appears that it's possible to register an activity function without a name.  I'm not sure what that means.  Should we just require a name or allow null/blank names?  We should also implement an `Activity` base class on the .NET side.

- [x] workflow: [RegisterWorkflowWithOptions](https://godoc.org/go.uber.org/cadence/internal#RegisterWorkflowWithOptions)

- [ ] workflow: [ReplayWorkflowHistory](https://godoc.org/go.uber.org/cadence/internal#ReplayWorkflowHistory), [ReplayWorkflowExecution](https://godoc.org/go.uber.org/cadence/internal#ReplayWorkflowExecution), and [ReplayWorkflowHistoryFromJSONFile](https://godoc.org/go.uber.org/cadence/internal#ReplayWorkflowHistoryFromJSONFile)

  These are related debug/testing utilities.  Lower priority but we'll probably need these eventually.

- [x] workflow: [SetQueryHandler](https://godoc.org/go.uber.org/cadence/internal#SetQueryHandler)

  Queries (and probably signals) are going to be a bit tricky.  I don't really like how the GOLANG client handles query function registration.  I'm starting to believe that the GOLANG client **context** should be implemented by a **Workflow** base class that applications will derive from.  We'll allow applications to add query and signal methods identified by attributes and the base class will register these with **cadence-proxy** and then forward any callbacks to these methods. 

- [x] config: [SetStickyWorkflowCacheSize](https://godoc.org/go.uber.org/cadence/internal#SetStickyWorkflowCacheSize)

  This should be a connection setting.  This controls how big (in RAM) the cached history for any given workflow can grow.

- [x] workflow: [SideEffect](https://godoc.org/go.uber.org/cadence/internal#SideEffect)

- [x] workflow: [Sleep](https://godoc.org/go.uber.org/cadence/internal#SideEffect)

- [x] workflow: [WithCancel](https://godoc.org/go.uber.org/cadence/internal#WithCancel)

  I think that all .NET workflows should support cancellation out-of-the-box so we'll won't need to expose this to apps.  The second sentence in the description is a bit confusing as it implies that the workflow should be always cancelled after all of the workflow options have completed to release resources.

- [x] activity: [GetActivityInfo](https://godoc.org/go.uber.org/cadence/internal#GetActivityInfo)

  Seems like this information is going to be static for a given activity run so perhaps we can just pass this along with the `ActivityInvokeRequest` from the **cadence-proxy** rather than doing separate queries.

- [x] signal: [GetSignalChannel](https://godoc.org/go.uber.org/cadence/internal#GetSignalChannel)

  **cadence-client** should pass the signals it's prepared to receive when workflows are registered with the **cadence-proxy**.  Each signal will have a method tagged with a special attribute.  **cadence-proxy** will need to get a signal channel for each of these and transmit `WorkflowInvokeSignalRequest` messages as signals are received on the channel.  Note that this means that signals cannot be defined dynamically at runtime with this scheme but that doesn't seem like an important use case.

- [ ] workflow: [ExecuteChildWorkflow](https://godoc.org/go.uber.org/cadence/internal#ExecuteChildWorkflow)

  This GOLANG method makes me wonder whether the `context.WithSOMETHING()` pattern is really all that helpful.  What not just add an optional parameter to `ExecuteChildWorkflow`?  The answer is that GOLANG doesn't support optional parameters or method overloading so perhaps Uber believes that this pattern is helpful.  I don't think it makes sense for .NET/C# though, so we'll probably dump the `context.WithSOMETHING()` pattern.

- [x] client: [ExecuteWorkflow](https://godoc.org/go.uber.org/cadence/internal#TestWorkflowEnvironment.ExecuteWorkflow)

- [x] client: `ExecuteWorkflow`

- [x] client: `SignalWorkflow`: Add an optional parameter that firsts starts the workflow if its not already running and then sends the signal.

- [x] client: `CancelWorkflow`

- [x] client: `TerminateWorkflow`: What the difference between this and `CancelWorkflow`?

- [ ] client: `GetWorkflowHistory`

- [x] client: `CompleteActivity/CompleteActivityById`:

  I'm not sure about the use case for these and they seem a bit weird.  I'm hoping that the `Activity` base class will be able to handle this transparently from the app persective.

- [x] client: `RecordActivityHeartbeat/RecordActivityHeartbeatById`

  These should be implemented by the base `Activity` class.

- [ ] client: `ListClosedWorkflow/ListOpenWorkflow`

  We'll need these.  I don't like these names though.  Perhaps `ListClosedWorkflows()` and `ListOpenWorkflows()` (plural) instead.

- [x] client: `QueryWorkflow`

  Wow, this is synchronous!  I'm going to make this async on the .NET side.

- [ ] `DescribeWorkflowExecution`

  This name seems a bit awkward and isn't really consistent with other Cadence names (e.g. why isn't `GetWorkflowHistory` named `GetWorkflowExecutionHistory`?)  I'll probably name this `DescribeWorkflow` for .NET.

- [ ] client: `DescribeTaskList`

  Another awkward name (and frankly, the term **task list** itself is a bit confusing too, but we'll leave that one alone).  I'm not sure there's a decent alternative though.

**Comment by johncburns1** [comment]
I have implemented a custom metrics scope. We just have to decide on what kinds of metrics we want from Cadence. Right now I have a "NoOpScope" as a placeholder. I also have a start worker method implementation. Will this be a message type or is starting a working going to be an action that takes place in the background?

**Comment by jefflill** [comment]
**Metrics scope:** I added the item to track choosing what we're going to track.

**StartWorker:** This will be new request/reply messages.

**Comment by jefflill** [comment]
Closing because these items are now covered by other issues.
