### ISSUE TITLE
Workflow Context 

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#526]
We should chat about and decide how we are going to define the context for client calls. At this moment, the context is Background, with no timeout and no cancelation.

**Comment by johncburns1** [comment]
Maybe we should define special contexts in the ProxyMessage. For example, during a ConnectRequest, this is the operation that takes the longest because we have to wait to establish a connection to the server. This operation should have a longer timeout than say a domain describe call to the client. And I think that this can be done using context.

**Comment by jefflill** [comment]
I'm leaning towards having `ProxyRequest` include a `Timeout` parameter that you'd use if that makes sense for the specific operation (or you'd just ignore when it doesn't make sense).

We haven't talked about cancellation yet.  The current design is that I'll send you a `CancellationRequest` to cancel a specific operation identified by `RequestId`.  This means that all operations I submit to you need to be cancel-able.  This means that you'll need to maintain a table mapping request IDs to requests and have this mapping also have a copy of the cancellation function you'll create for all operations and then you'd simply call the cancellation function for the pending request when you receive a `CancellationRequest`.  If the operation has already completed, the `CancellationReply` should indicate this via the `CancellationReply.WasCancelled` property.

**Comment by jefflill** [comment]
@johncburns1: The `ConnectRequest` now includes the `ClientTimeout` property (which defaults to 30 seconds).  You should use this as the timeout and then close this issue.

**Comment by jefflill** [comment]
@johncburns1: It looks like you've coded this, so I'm closing this issue.

**Comment by johncburns1** [comment]
My bad. Forgot to close. Thanks for doing that.
