### ISSUE TITLE
Handling unexpected exceptions in the Cadence proxy 

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#527]
After a message comes in, gets deserialized and identified as a valid message type, the Cadence proxy should not run into any errors... But what if it does. I have implemented error handling to catch any unexpected exceptions, but what do we do with them. By this point a 200, 400, or 404 response has already been send back to the Neon Cadence Lib, and if an error occurs, a reply message is not going to be sent back to the Cadence Lib. So how do we communicate to the Neon Cadence Lib that an error has occurred? Is it important? Should this be a fatal error? Should we just recover and continue taking requests/replies? Should we send a secondary 400 response back to the Neon Cadence Lib?

**Comment by jefflill** [comment]
You always need to send a reply to every request message the .NET side as long as you're still connected to the Cadence cluster.  If Cadence returns an error, you need to pass it as **Error** property in the reply,  This is how the .NET connection signals errors to the client app actually initiating the operation.  If you didn't send the reply, then the .NET application will await for operation completion forever.

We'll have to discuss the disconnection case.  I'm hoping that is the Cadence client goes bad ends up disconnecting from the cluster that any pending operations will return an error (canceled or something) and that you'll be able to report those to me so I can throw them for application to handle.  If this doesn't happen and you're able to detect a Cadence client disconnect, then you can have a subsequent heartbeat fail and I can have any pending operations throw exceptions on the .NET side.

**Comment by jefflill** [comment]
@johncburns1: Is this one still active?

**Comment by jefflill** [comment]
Closing this.
