### ISSUE TITLE
Build and publish Cadence release binaries

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#535]
Apparently, Uber sometimes updates release branches after they've been published.  We currently have a situation where our forked release branch which used to build, no longer builds.

The solution is to create a `neonKUBE/cadence` GitHub project and periodically publish the release binaries to the repo, perhaps becoming the *official* source of these binaries.

**Comment by dmetzgar** [comment]
We do use release branches for patching. Which branch are you having trouble with and what are the build errors?

**Comment by jefflill** [comment]
@dmetzgar: Hi Dustin!  Sorry for the delay getting back to you.  You're the first outside person to post to this repo since I made it public.

Here's the deal: We currently have a docker image that combines **cadence** and **cassandra** and also proactively applies the cassandra schema updates, we're using this for integration and unit testing right now (it's nice because it takes only about 10 seconds to start).

We're currently building Cadence Server within our Dockerfile and we'd like to maintain image for all Cadence releases going forward and we need to be able to rebuild these images at any time (for various reasons).

The problem is that you folks seem to be removing older GitHub release branches shortly after you release the next version, which means we won't be able to rebuild older releases after you've deleted the branches.

I figured I could solve this by forking your repo, watching for new releases and pulling them, and **not deleting** older release branches.  This worked for a while, but this failed last week when we tried top rebuild this image for your **0.5.7** release from my fork (the 0.5.7 release no longer exists in your official repo).  For what it's worth, we're seeing this compiler error:

```
go build -i -o cadence-server cmd/server/cadence.go cmd/server/server.go
# command-line-arguments
cmd/server/server.go:128:46: too many arguments in call to cluster.NewMetadata
        have ("github.com/nforgeio/cadence/vendor/github.com/uber/cadence/common/log".Logger, "github.com/nforgeio/cadence/vendor/github.com/uber/cadence/common/metrics".Client, dynamicconfig.BoolPropertyFn, int64, string, string, map[string]int64, map[string]config.Address, dynamicconfig.StringPropertyFn, string, dynamicconfig.BoolPropertyFn)
        want ("github.com/nforgeio/cadence/vendor/github.com/uber/cadence/common/log".Logger, "github.com/nforgeio/cadence/vendor/github.com/uber/cadence/common/metrics".Client, dynamicconfig.BoolPropertyFn, int64, string, string, map[string]config.ClusterInformation, dynamicconfig.StringPropertyFn, string, dynamicconfig.BoolPropertyFn)
```

What I'd really love is avoid having to compile Cadence Server at all and be able to simply download pre-built binaries from someplace where all release versions will be archived.  That would make it easy to build custom docker images.

I was figuring that I could just build these binaries myself and and release them on GitHub, but it would be super nice if you Uber folks did this.  We really only care about the Linux binaries right now, but I was going to do OS/X and Windows for completeness.

**Comment by dmetzgar** [comment]
Ah, just saw this reply. Our process is generally to put a tag on master for the release and create a branch for any patches. After a few versions we clean up the old branches. The tags should still be there though. I created an issue to document our release process.

**Comment by jefflill** [comment]
Cool thanks.

**Comment by jefflill** [comment]
@dmetzgar: We've been stupid!  We'll just use the GitHub tags as you suggest.

I've been mostly using the Visual Studio integrated GitHub UX and didn't realize that tags and branches were essentially the same thing.
