### ISSUE TITLE
[CodeGen] Bugs and enhancements

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#538]
- [x] It would be nice if Neon.CodeGen supported `ReadOnlyCollection`.

  **NOTE:** CodeGen now supports `ReadOnlyCollection` and `ReadOnlyDictionary`.

- [x] Properties defined as `List<List<T>>` generate bad code:
  ```
  this.Coordinates = property.Value.ToObject<global::System.Collections.Generic.List<List`1>>(RoundtripDataHelper.Serializer);
  ```

  **NOTE:** I added a test with a `List<List<string>>` property and that worked.  I can't repro the bug above.

-[x] Can JSON.NET handle serializing cyclical data?

  **NOTE:** It looks like the answer is **yes**.  JSON.NET has two options for doing this: `PreserveReferencesHandling.Objects` and `ReferenceLoopHandling.Ignore`.  The former generates a custom JSON output that preserves object references but may not be compatible with all JSON parsers.  The latter doesn't preserve objects.  `NeonHelper` JSON parsing defaults to `ReferenceLoopHandling.Ignore`.  This article describes how this works:

  https://stackoverflow.com/questions/23453977/what-is-the-difference-between-preservereferenceshandling-and-referenceloophandl

**Comment by jefflill** [comment]
- [ ] **BUG:** Properties defined as `List<List<T>>` generate bad code:
  ```
  this.Coordinates = property.Value.ToObject<global::System.Collections.Generic.List<List`1>>(RoundtripDataHelper.Serializer);
  ```

- [ ] Should we also support `ReadOnlyCollection<T>` as `ReadOnlyDictionary<TKey, TValue>`?

- [ ] Add a `[DataProperty]` attribute that specifies whether a property is virtual or not.

- [ ] Initialize property values to the `[DefaultValue(v)]' attribute, if we're not already doing that.

**Comment by jefflill** [comment]
Marcus wanted this to handle geo related stuff, but we decided this isn't really an appropriate use case for `IRoundtripData` so I'm putting this on the backlog.

The `List<List<T>>` thing is still a bug and we should still consider the other features in the future.
