### ISSUE TITLE
[cadence-proxy]: Move this source folder up one directory

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#541]
@johncburns1 : Please move the:

&nbsp;&nbsp;&nbsp;&nbsp;`$\Go\src\github.com\loopieio\cadence-proxy`

directory up one folder, effectively replacing the `loopieio` folder, when you have a spare moment.  This can keep till you get back and have a spare moment.

**Comment by johncburns1** [comment]
Move is done and everything works in testing.
