### ISSUE TITLE
[cadence]: cadence-proxy is still serializing ErrorType and ErrorDetails in replies

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#548]
I was working on #534 to optimize the memory allocations around and noticed that the **cadence-proxy** is still passing the old `ErrorType` and `ErrorDetails` message properties in `ProxyReply` messages like `InitializeReply`.  I took a quick look at the GO source though, and don't see where these properties are set.

I'm currently testing out of the **jeff** branch and am investigating further.

**Comment by johncburns1** [comment]
I have been looking at this one.  In the cadence branch there should be no reason why the ErrorDetails are even being set.  There is not ErrorDetails property in the CadenceError struct that I am sending back, and it is not being set in the reply.  I searched for references to it in the project and could find nothing.  The only thing that I can think of is that maybe some old version of the cadence-proxy has been cached and not updated.

**Comment by jefflill** [comment]
Yeah, I couldn’t find anything either.  I have cleared the build binaries
since then so that’s not it.

I’ll look further.  Perhaps my tests are doing something funny.

—Jeff

**Comment by johncburns1** [comment]
Alright.  Which test package are you seeing this? Maybe I can do some investigation while you are going to Jurassic Island.

**Comment by jefflill** [comment]
FIXED: This was due to problem with `neon-build copy ...` that was preventing the most recent **cadence-proxy** binaries from being imported as resources into the **Neon.Cadence** library.
