### ISSUE TITLE
Add Result property to WorkflowSignalChildReply

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#551]
When signaling the ChildWorkflowFuture, the return value is a workflow.Future.  I assume that I am going to wait on the future to return either a result or an error.  I need to send the result back to the Neon.Cadence client in the reply.  As it stands, there is not Result property in the WorkflowSignalChildReply message type.  I am going to add one.  Tell me what you think about this.

**Comment by jefflill** [comment]
No, signals don’t return replies, the semantics are fire-and-forget.
