### ISSUE TITLE
Add Result to WorkflowSignalInvokeReply

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#555]
Currently there is not Result property in WorkflowSignalInvokeReply, so there is nothing to get from the future (aside from an error) that can be sent back to the Neon.Cadence client via WorkflowSetSignalHandlerReply.  Should we add a Result property or just return a nil result if there is no error?

**Comment by jefflill** [comment]
No, signals don’t return replies, the semantics are fire-and-forget.

**Comment by johncburns1** [comment]
In this case, I am going to have the signal handler function defined in WorkflowSetSignalHandler return just an error in stead of an error and a []byte, because there should never be a result, just either an error or nil.

**Comment by jefflill** [comment]
That’s correct, did I have a Result in the .NET message? (I’m at McDonalds
now)

—Jeff

**Comment by johncburns1** [comment]
No there is not, but in the specs it says to return either a result or an error, but I think this may just be a copy and paste error in the specs.  What you eating? Their new artisan sandwiches are pretty good.

**Comment by jefflill** [comment]
Breakfast burrito, baby!
