### ISSUE TITLE
[cadence]: "Hello World!" test is failing

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#557]
I've implemented the first end-to-end workflow unit test as `Test_Workflows.HelloWorld()`.  This test is super simple: it registers a domain, starts a workflow worker, registers a simple hello-world workflow, and then executes it.  The test workflow simply returns "Hello World!".  I pushed this to **cadence**.

The test is currently failing after it registers the domain and then while it's starting the workflow worker.  It looks like **cadence-proxy** is exiting unexpectedly.

It's fun to be finally actually testing this all end-to-end.

**Comment by johncburns1** [comment]
* There needs to be WorkflowOptions defined when calling client.StartWorkflowAsync()
* WorkflowOptions.ToInternal is not working properly, causing WorkflowExecuteRequest to not be sent by the Neon.Cadence client
* Move cadence client calls into the clientHelper in the cadence-proxy

**Comment by jefflill** [comment]
FIXED
