### ISSUE TITLE
CouchbaseFixture.Clear() not clearing all indexes

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#561]
Full Text Indexes are not being removed.

**Comment by jefflill** [comment]
Yeah, I haven’t done anything with the FT indexes.

Do you need this now or can it go on the backlog?

**Comment by marcusbooyah** [comment]
Not super urgent, it can go on the backlog, or I can fix it.

**Comment by jefflill** [comment]
Sure, go ahead and fix it.

—Jeff

**Comment by marcusbooyah** [comment]
Fixed
