### ISSUE TITLE
Implement GetVersion()

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#564]
Need to add support for WorkflowGetVersion() on the cadence-proxy side. 

- [x] Request/Reply message types

- [x] Add to message factory 

- [x] Add endpoint request handler

- [x] Add reply builder

**Comment by jefflill** [comment]
The .NET side `GetVersionAsync()` API is already implemented.

**Comment by johncburns1** [comment]
FINISHED
