### ISSUE TITLE
CadenceFixture: Option to leave Cadence container running

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#566]
Once Jack enables the Cadence UX to the **cadence-test** Docker image, we'll want to allow developers to be able to leave the test container running so they can poke around the workflow history.

This should be easy to do with an optional parameter to the start methods that would fall through to a new, related option for the underlying `ContainerFixture`.

**Comment by johncburns1** [comment]
## Adding a note to branch cadence server from release tags instead of from working branches.

**Comment by jefflill** [comment]
@johncburns1: I added the `keepOpen` parameter to the `CouchbaseFixture` start methods as well as the underlying `ContainerFixture`.
