### ISSUE TITLE
Misc unit test failures and changes

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#574]
Tracking unit test failures and other current issues:

- [x] `Test_EndToEnd.Workflow_Signal_Twice()` is failing.

- [x] `Test_EndToEnd.Heartbeat_Single()` is failing.  This test simply starts an activity that records a single heartbeat and returns.  It appears that the **cadence-proxy** terminates in a panic.

- [x] I've added the `ActivityRecordHeartbeatRequest.TaskToken` property to support external heartbeating.  When this is non-NULL, you'll ignore the `ContextId` and call `client.RecordActivityHeartbeat()`, passing the token.

- [x] `Test_EndToEnd.Workflow_Signal_Child` is failing when I send a `WorkflowSignalChildRequest` to the **cadence-proxy**.  Looks like the proxy is terminating in a panic.

- [x] `Test_EndToEnd.WorkflowTerminate` doesn't appear to be terminating the workflow.

- [x] I've noticed that the **cadence-proxy** seems to just terminate whenever there's a problem.  Is there a way to catch these errors and transmit them back to me in the reply message?  I'd rather see that happen as opposed to a crash when something unexpected happens.  Let's discuss this on Monday.

- [x] `Test_EndToEnd.Workflow_Cancel` doesn't seem to be cancelling the workflow.  This test is starting the `DelayWorkflow` which just sleeps for 30 seconds.  The unit test waits until the workflow reports that it's running and then cancels it.  I'm expecting to see the reply from you for the `SleepAsync()` to have a cancel error.  Note that the **cadence-proxy** is not dying in this case.

- [x] `ActivityInvokeReply` adds the new `Pending` property.  This will be TRUE when the activity is going to be completed externally.  In this case, the **cadence-proxy** will return from this from the activity function:
  ```
  return "", activity.ErrResultPending
  ```
  as described here: https://godoc.org/go.uber.org/cadence/activity#hdr-Activity_Cancellation

  The `Test.EndToEnd.ActivityExternal` unit test exercises external activity heartbeating and completion.

- [x] `Test_EndToEnd.Workflow_Cancel_Child` is failing.  It looks like **cadence-proxy** is crashing.

**Comment by johncburns1** [comment]
Completed panic recovery so message returns with a cadence panic error instead of terminating the cadence-proxy.  We still need to figure out Termination, but that spec has been laid out in another issue.
