### ISSUE TITLE
All container-init output should use standard logging format

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#577]
The wget command error is not using the logger.

**Comment by jefflill** [comment]
One general approach for this would be to write a console app or script that would read lines from STDIN and then write them to STDOUT with the standard format.

Then, we’d pipe the output from commands like WGET to this app.

We wouldn’t be able determine log level but perhaps we could do this via a command line option, for example if only actually errors or warnings are going to STDERR, we could pipe that to the app with —error and then pipe STDOUT to another instance of the app with —info

**Comment by jefflill** [comment]
@marcusbooyah: What was this relating to?  Is some service doing `wget` in its Docker startup script?

**Comment by jefflill** [comment]
This came up when Marcus tried to workaround the Istio/Envoy sidecar delay.  This is addressed now by `NeonService` service dependencies.
