### ISSUE TITLE
Log indexes not matching up

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#578]
The first three entries here were logged using the log-index.sh script, the last entry was logged using the Neon logger.

[2019-07-02T22:13:33.000+00:00] [INFO] [index:11] Container started.
[2019-07-02T22:13:33.000+00:00] [INFO] [index:12] Running in Kubernetes with Istio enabled.
[2019-07-02T22:13:33.000+00:00] [INFO] [index:13] Envoy Sidecar available.
[2019-07-02T22:13:34.003+00:00] [INFO] [index:1] Starting [base-data:master-4727567]

**Comment by jefflill** [comment]
This is due to the scripts and .NET maintaining different counters.  One workaround would be to have the .NET logger look for the file with the script index and use that to initialize its index.  This means we'd have to standardize on the location of the script index file.

**Comment by jefflill** [comment]
Currently, we're only deploying Linux based services and the logging scripts we're including in our container images are writing the `long` index of the last logged event to this RAM file:
```
/dev/shm/log-index
```
We're going modify the **Neon.Common** logging code to read the index from this file when logging is initialized on Linux such that the next event logged will use the index just read.

**Comment by jefflill** [comment]
**FIXED** for 2.1.0
