### ISSUE TITLE
Convert CADENCE-PROXY to a shared library

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#579]
Apparently, the GOLANG compiler can generate a shared library that C# should be able to call.  This would be nice because we wouldn't have to run **cadence-proxy** as a separate process and we'd avoid a lot of overhead performing HTTP/network operations:

https://golang.org/doc/go1.10#compiler

The easiest approach would probably be to have both the .NET and GOLANG sides expose a method/function that emulates what we're already doing, submitting HTTP-like requests with byte array payloads.  We'd retain the same message structure we're already doing to seamlessly handle parameter conversion, etc.

I'm putting this on the backlog.  I believe that we can go with the second process though for an initial release and for Loopie production and come back to this later in the fall or winter.

**Comment by jefflill** [comment]
It looks like this may work.  GOLANG is capable of generating Windows DLLs as well as Linux/OSX shared libraries.  We can build the DLLs natively on Windows and we should be able to use the **nkubeio/golang** container to compile the shared libraries.

**Comment by johncburns1** [comment]
Some more examples on using shared-c go:

https://github.com/vladimirvivien/go-cshared-examples

**Comment by johncburns1** [comment]
- Unzip and set shared libraries in a CadenceClient static constructor

- Load the shared libraries in the CadenceClient

- For the first step, lets just get rid of HTTP requests on the .NET side, but keep them on the cadence-proxy side, and once that is working then we can go back and make the changes to the proxy

**Comment by jefflill** [comment]
Let's go ahead and start on this in the new **cadence-shared** branch.  I'm going to push hard over the weekend to complete the unit testing iand some remaining features in the **cadence** and **jeff** branches and then I figure we can integrate this early next week and hopefully put the first cut of the .NET Cadence client to bed.

@johncburns1: I'm still making a lot of changes to the .NET side, so it would be best for you to avoid making changes on the .NET side so we can hopefully avoid merge conflicts.

**Specification:**

The essential goal here is to have a way to the the .NET client to send messages to **cadence-proxy** and for **cadence-proxy** to send messages to the .NET client.  A message in this case is simply a byte array holding a serialized proxy message.  This is **exactly the same format** we're using for the body of the HTTP requests we're currently sending back and forth.

The basic approach here is that we'll build the **cadence-proxy** as a DLL for Windows and shared libraries for Linux and OS/X.  The proxy library will expose a handful of APIs to the .NET client:

```
// This function determines whether there's a message from cadence-proxy waiting
// to be received and processed by the .NET client.  If a message is pending, the function
// will return the size of the serialized message in bytes.  If no message is pending, the
// function will wait for for up to the specified timeout for a message and return its size.
// If no message is ready before the timeout, the function will return 0.
Int32 IsMessageReady(Int64 timeoutNanosecond);

// This function retrieves the next message from the cadence-proxy.  This will called
// immediately after a call to IsMessageReady() returned a positive size.  The buffer passed
// will be allocated to be at least as large as the message size returned by IsMessageReady().
// GetMessage() will copy its message bytes into the buffer and then discard the message
// on it's size.  This will never be called when there's no message ready.
void GetMessage(byte *pMessageBuffer);

// This function will be called when the .NET client needs to transmit a message to the
// cadcence-proxy.  messageSize will be passed as the number of serialized message bytes
// referenced by pMessageBuffer.  cadence-proxy should make a copy of the message bytes
// and then proceed to deserialize and process it the same way you already do for messages
// received via HTTP.  Note that SendMessage() should return after it's made a copy of the
// message buffer but before it performs any other processing (which should probably happen
// in a go-routine).
void SendMessage(Int32 messageSize, byte *pMessageBuffer);
```

**Comment by jefflill** [comment]
**CLOSING:** We're not going to be able to do this due to #668.
