### ISSUE TITLE
Cadence: cadence-proxy should retry connecting to Cadence on failure.

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#582]
We're seeing some Cadence cluster connection failures sometimes during unit tests.  I'll bet that we're trying to connect to the new Cadence test container before it's ready.

@johncburns1: We need to retry a few times.  I'll add some retry parameters to the `ConnectRequest` and then assign this to you.

**Comment by jefflill** [comment]
@johncburns1: I've added the following properties to the `ConnectRequest` message:

- [ ] **Retries:** This is an integer specifying the maximum number of times you should retry connecting to the Cadence cluster.  Note that **retries=0** means that you'll do an initial connection attempt and not retry, and that **retries=1** means you'll do the initial attempt and then retry once, etc.  This **defaults to 3**.

- [ ] **RetryDelay:** This is the duration you should wait before each retry.  This **defaults to 5 seconds**.

  Both of these values can be customized by the .NET workflow developer via `CadenceSettings`.

- [ ] One other thing: Can you return a friendlier error message when the connection could not be established?  Something like: **"connection failed"**.  I'd map this to a friendly exception on the .NET side.

**Comment by johncburns1** [comment]
Finished
