### ISSUE TITLE
Support new ReplayStatus message properties

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#586]
I've added the new `ReplayStatus` property to these messages:

* `WorkflowReply` (base class)
* `WorkflowInvokeRequest`
* `WorkflowQueryInvokeRequest`
* `WorkflowSignalInvokeRequest`

This property returns this enum:

```
/// <summary>
/// Indicates a workflow's current replay status.
/// </summary>
internal enum InternalReplayStatus
{
    /// <summary>
    /// Indicates that the corresponding operation cannot determine the replay
    /// status (e.g. because the it didn't relate to an executing workflow).
    /// This is the default value.
    /// </summary>
    [EnumMember(Value = "Unspecified")]
    Unspecified = 0,

    /// <summary>
    /// The related workflow is not replaying.
    /// </summary>
    [EnumMember(Value = "NotReplaying")]
    NotReplaying,

    /// <summary>
    /// The related workflow is replaying.
    /// </summary>
    [EnumMember(Value = "Replaying")]
    Replaying
}
```

The idea here is that the .NET side needs to to know whether the workflow is currently replaying from history or not so it can decide whether or not to record logs and metrics (and also to indicate this state to advanced workflows).

The GOLANG client returns the current replay state via the `IsReplaying(ctx)` function.  **cadence-proxy** will need to call this and set the new `ReplayStatus` property before you send any of these messages to the .NET client:

- [x] `WorkflowInvokeRequest`
- [x] `WorkflowQueryInvokeRequest`
- [x] `WorkflowSignalInvokeRequest`

The proxy will also need to set this for workflow replies to requests the .NET side sends when performing a workflow operation that will be recorded to the history.  I believe is the definitive list of workflow reply messages that will need this set:

- [x] `WorkflowCancelChildReply`
- [x] `WorkflowExecuteChildReply`
- [x] `WorkflowGetLastResultReply`
- [x] `WorkflowGetTimeReply`
- [x] `WorkflowGetVersionReply`
- [x] `WorkflowHasLastResultReply`
- [x] `WorkflowMutableRequest`
- [x] `WorkflowSignalChildReply`
- [x] `WorkflowSleepReply`
- [x] `WorkflowWaitForChildReply`

**Comment by johncburns1** [comment]
Implemented message properties and endpoint behavior.
