### ISSUE TITLE
Detect parallel workflow operations

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#589]
Investigate whether the .NET client can detect multi-threaded access to the base workflow functions.  This is currently detected by **cadence-proxy** which returns an obscure error message.  It would be better to detect this and throw a clearer error.

The basic idea is to have the .NET client keep track of the number of pending **cadence-proxy** operations and ensure that there's never more than one in progress.

**Comment by jefflill** [comment]
DONE

**Comment by jefflill** [comment]
The check implemented above is too restrictive and will prevent running child workflows and activities in parallel.

For workflow operations that return futures, we need to implement some kind of scheme where the **cadence-proxy** notifies .NET after the operation has been submitted to Cadence but before it actually completes.  Our parallel check will need to wait for this intermediate ack in this situation rather than waiting for the full operation to complete.

**Comment by johncburns1** [comment]
List of operations that return a future:

- WorkflowSleep

- WorkflowSignalChild

- ActivityExecuteLocal

- WorkflowExecuteChild

- ActivityExecute

**Comment by jefflill** [comment]
Consolidated into #627
