### ISSUE TITLE
Test Cadence on .NET Framework

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#590]
We're doing some tricky dynamic compilation for workflow and activity stubs which may need some TLC to get working on the regular old .NET Framework.  We should used a shared project (or something) to run all of the workflow tests as .NET Core (which we're doing now) as well as separate tests targeted at .NET Framework.

The primary concern is around ensuring that we're referencing the current .NET assemblies for both platforms before dynamically compiling the generated code.

**Comment by jefflill** [comment]
There are some issues preventing .NET Framework compatibly including some of the Xunit related class libraries being built as netcoreapp3.0 and some nuget packages (like those for Roslyn) what don't appear to be available for .NET Framework on first look.

I've decided not to support this for v1 and am putting this on the backlog.

**Comment by jefflill** [comment]
**DONE:** This took a bit of doing but Cadence on .NET Framework works now!

**Comment by johncburns1** [comment]
We, the people thank your dearly.
