### ISSUE TITLE
Evaluate .NET metrics solutions

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#598]
[metrics.net](https://github.com/Recognos/Metrics.NET) looks like a reasonable solution.  An alternative might be the new .NET [EventCounter](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventcounter?view=netframework-4.8).

Here's some more information about **EventCounter:** [link](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md)

I'm guessing that for **EventCounter** we'd need to implement some kind of custom provider to deliver events to Prometheus or whoever.  Perhaps we could use Metrics.NET for this to provide a nice integrated solution,  Apparently, ASP.NET uses **EventCounter** so we'll want to expose all of these built-in metrics to our supported external monitoring solutions.

**Comment by jefflill** [comment]
@marcusbooyah: Let's use this issue to track all related metrics thinking.

**Comment by marcusbooyah** [comment]
Looks like https://github.com/AppMetrics/AppMetrics is the latest .NET standard port of Metrics.NET

**Comment by jefflill** [comment]
We're going to go ahead and use AppMetrics.
