### ISSUE TITLE
KubeService: Enable .NET server GC by default?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#600]
It looks like .NET Core 3.0 defaults console apps to use the workstation GC.  We need to investigate whether we should enable server GC mode by default:

https://devblogs.microsoft.com/dotnet/using-net-and-docker-together-dockercon-2019-update/

**Comment by dmetzgar** [comment]
Might want to check out this thread: https://twitter.com/Nick_Craver/status/1148725141452578817
And the response from Maoni Stephens. Sometimes workstation is better.

On a previous project using .NET Framework/Windows Server we used workstation GC when there was only 1 core, but for more cores we used server GC.

**Comment by jefflill** [comment]
Yep.  It looks like .NET Core 3.0 will switch automatically to server GC when there's only one CPU.  Here's the detail from the link above:

> Server GC is enabled by default for ASP.NET Core apps (it isn’t for console apps), because it enables high throughput and reduces contention across cores. When a process is limited to a single processor, the runtime automatically switches to workstation GC. Even if you explicitly specify the use of server GC, the workstation GC will always be used in single core environments. 


So, it looks like this will do the right thing if we enable server GC.

**Comment by jefflill** [comment]
...although we'll need to ensure that it's not ASP.NET making that decision.  It's probably best to have `KubeService` handle this.  We'll need to poke around the ASP.NET code to align implementations (making sure we handle CPU rounding-up the same way).

**Comment by jefflill** [comment]
This cannot be enabled in code.  This needs to be specified in the service **csproj** file like:
```
<PropertyGroup>
  <ServerGarbageCollection>true</ServerGarbageCollection>
  <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
</PropertyGroup>
```
This [link](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/configuring_.NET_garbage_collection.html) also recommends doing concurrent collection.  Note that both modes will be disabled when there is only one CPU.

**Comment by jefflill** [comment]
@marcusbooyah: Add this to the neonKUBE operator service's ***.csproj** file when you implement it.

**Comment by jefflill** [comment]
@marcusbooyah: I went ahead and added this for you.  It's pushed to **master**.
