### ISSUE TITLE
CadenceClient ConnectAsync strips host when http/https not specified

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#603]
I noticed that when reading endpoints from settings.Servers when sending the ConnectRequest each Server string is parsed into a uri and the uri.Host is extracted.  The port is then appended to the end of the uri.Host.  If you do not add http/https:// to the server string, uri.Host returns an empty string.  Is this the behavior that we want? Also the cadence server endpoint (host:port) is specified in CadenceFixture startup, but when the ConnectRequest is sent, it just strips the port and then appends the same port right after.

**Comment by jefflill** [comment]
This is basically by design.  The servers setting requires the URI scheme (HTTP://, HTTPS://, CADENCE://).

I have updated the code to ensure that the scheme is present.
