### ISSUE TITLE
cadence-proxy times out for unregistered workflows and activities

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#607]
I've started re-implementing the Cadence unit tests and noticed that the **cadence-proxy** doesn't immediately report an error then we try to call an unregistered workflow type or have a workflow try calling an unregistered activity type.  I can see in the logs that Cadence detects these problems but **cadence-proxy** just hangs for a while and then times out:
```
Aug  4 09:48:29 [34mINFO[0m   internal/internal_worker_base.go:305    Task processing failed with error       {"Domain": "test-domain", "TaskList": "test-tasks", "WorkerID": "23640@WORK@test-tasks",                                                                        "WorkerType": "ActivityWorker", "error": "unable to find activityType=TestCadence.Test_EndToEnd.ActivityNotRegistered. Supported types: [internalSessionCreationActivity, internalSessionCompletionActi                                                                       vity, TestCadence.Test_EndToEnd.ActivityWithNoResult, TestCadence.Test_EndToEnd.ActivityWithResult]"}
```
These are the tests that are failing:

![image](https://user-images.githubusercontent.com/4908431/62426725-4da09100-b69d-11e9-8156-aa2bbf416635.png)

It's possible that this is by design for Cadence, where it detects the unregistered workflow/activity types and then waits for the client timeout while retrying, hoping the type will be registered soon, although I'd prefer to see an immediate error if Cadence doesn't allow submitting calls to unregistered workflows or activities.

We'll also need to investigate how Cadence handles workflow/activity registrations when workers start/stop.  Personally, I'd like Cadence to be able to accept calls to unregistered workflows/activities and then let them idle until a worker registers an implementation or the call times out.  This may be exactly what we're seeing here, so **this may not be a bug**.  I'm not sure how to unit test this though until we allow multiple Cadence client again.

One final thing: It looks like the timeout error I get from Cadence actually has the **Custom** type, not **Timeout**.  I haven't looked to closely to determine if this is caused by the **cadence-proxy** or the .NET client.  **Are you mapping the error types on the GO side?**

**Comment by jefflill** [comment]
I looked at this more closely and I believe the Cadence timeout behavior here is **by design**.  It appears that the Cadence client itself is retrying the workflow submission in the hope that some worker will register an implementation.  I think I would have preferred if the workflow was submitted to the Cadence cluster even if there are no registered workers for the workflow but the current implementation isn't unreasonable.

@johncburns1: I'm going to leave these tests in for a bit though, so you can have a look at your timeout error mapping (from above):

> One final thing: It looks like the timeout error I get from Cadence actually has the Custom type, not Timeout. I haven't looked to closely to determine if this is caused by the cadence-proxy or the .NET client. Are you mapping the error types on the GO side?

**Comment by johncburns1** [comment]
As far as the error types are concerned, some of the error types are mapping, some are not, I recently changed way that errors are being handled.  I need to take a closer look and make sure that all error types are being mapped as they should be.

**Comment by johncburns1** [comment]
Behavior by design and Timeout errors are working as expected.
