### ISSUE TITLE
Cadence message (and other) tests are failing

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#611]
@johncburns1: I just merged your changes to the **cadence** branch with my changes from **jeff** and most of the unit tests are failing now.  It looks like the message tests are failing because you're not echoing back the new **ContextId** property.

I'm not sure what's going on with the other tests.  I did see a log entry in the Cadence window complaining about an **unexpected message type**.  Perhaps this is related.

These tests we're passing in the **jeff** branch and the message tests work when I run them in emulation.

**Comment by johncburns1** [comment]
I'll look into it. They were passing on Cadence. Probably just a minor inconsistency.

**Comment by johncburns1** [comment]
I synced, cleaned the cadence-proxy exe's in Neon.Cadence/Resources, cleaned the solution, and rebuilt, and all of the tests are passing.  I think you may have just had an older version of the cadence-proxy in your local Cadence branch.  But things seem to be working as expected.  Closing this issue.
