### ISSUE TITLE
cadence-proxy: Large message transmission fails

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#614]
The **Test_EndToEnd.Workflow_Echo** test is failing with **cadence-proxy** returning a bad request error.  This test calls a workflow that attempts to return successively larger byte arrays up to 10MiB.  
```
cadenceclient/helper.go:483     failed to create workflow       {"error": "BadRequestError{Message: Blob data size exceeds limit.}"}
```
It looks like this is failing with 2MiB byte array.

Is this a Cadence limit or is the GO HTTP server you're using limiting the request size?  I've configured the .NET HTTP servers to allow request bodies of up to 15,000,000 bytes.  If this is a Cadence limit, is this limit configurable?

My latest changes were pushed to **cadence**.

**Comment by jefflill** [comment]
This link suggests that Cadence limits may be quite a bit smaller than 10MiB:

https://news.ycombinator.com/item?id=19732447

Folks really shouldn't be slinging around data this large in workflows and activities anyway.  I'll let you investigate this, but I'm probably going to reduce the maximum message size to 1.5MiB which will support byte array payloads of up to 1MiB (after they've been base-64 encoded and along with some JSON and message overhead).

**Comment by johncburns1** [comment]
https://www.gitmemory.com/samarabbas
Search for blob.

**Comment by johncburns1** [comment]
So after some exploration it looks like the cadence-frontend server BlobSizeLimit is set to a strict 2MiB (2*1024*1024).  The server should throw an internal warning @ ~256KiB (256*1024).  For the history service the BlobSizeLimit is a little larger (20MiB).  These are values that are hard coded and cannot be changed it doesn't seem.  

FrontedService config:  https://github.com/uber/cadence/blob/master/service/frontend/service.go
HistoryService config:  https://github.com/uber/cadence/blob/master/service/history/service.go

**Comment by johncburns1** [comment]
This configuration also happens on the server side when the cadence server is launched and is not something that we can configure from the client.  I can ask if this might be something that they can expose so that we can set it when configuring our cadence cluster.

**Comment by jefflill** [comment]
OK: I’ve removed any request size limitations on the .NET side and also reduced the maximum payload byte size to 1MiB so the test will pass.  You don’t need to do anything on the GO side.

**Comment by johncburns1** [comment]
Great.  I just edited the test as well so that the loop signature is:
```
for (int size = 1024; size < 2 * 1024 * 1024; size *= 2) {}
```

**Comment by jefflill** [comment]
I’ve already done that in the JEFF branch and have som other changes.  I’ll
push to cadence when I get in (leaving lunch now].

—Jeff

**Comment by johncburns1** [comment]
Ok i'll just leave it as is then.  We are about to head to grab a quick bite so will probably see you when we get back.
