### ISSUE TITLE
Workflow replay status is not being set?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#619]
@johncburns1: I'm doing replay testing and I'm seeing `WorkflowInvokeRequest` messages with `ReplayStatus=NotReplaying` when it should be replaying.

The test is **Test_EndToEnd.ReplayStart**.  This starts a workflow that tracks whether it's being invoked for the first time.  For the first invoke, it verifies that the workflow **is not** replaying and then throws an exception to force a replay.  The workflow restarts as expected, but it's not reporting that its replaying the second time.  I also tried delaying the decision task by more than the decision task time out as an alternate way to force the restart.  This had the same effect as the exception (as expected).

It looks like message serialization is working correctly.  I temporarily changed **utils.go:178** to hardcode `isReplaying = true` and am then correctly seeing the IsReplaying on my side.

Here are some possible explanations:

1. Cadence GO client is busted and isn't reporting replay status correctly for the first decision task.

2. **cadence-proxy** isn't inspecting the correct context at **utils.go:178**.  This needs to be the context passed to the workflow function.

It appears that you're checking the correct context, but could you please verify this.

If that doesn't work, we should replicate this with a pure GO workflow and verify that we're seeing the expected value when the workflow is restarted.

**Comment by jefflill** [comment]
I did some more research on this.  Here are some observations:

1. It appears that Cadence **does not** return `IsReplaying=true` when the workflow method is first called even if the workflow is replaying.  It looks like they set this after the first decision task completes.  I added a NOP activity call and after it returns `IsReplaying` is set correctly.

  The consequence of this will be that logging and metrics will be recorded by default for replaying workflows for the first decision task.  This seems a bit weird.  It would be good to confirm this is indeed the behavior for regular GO workflow and then discuss with the Uber guys.

2. I tried two methods to force a workflow to be replayed:

    a. First I threw an exception.  In this case, the workflow was restarted but `IsReplaying` was always `true`.

    b. Then I had the workflow pause for 12 seconds (exceeding the decision task 10 second timeout).  This also caused the workflow to restart, but `IsReplaying` was being set properly for this case.

  We need to figure out why exceptions aren't working.

**Comment by jefflill** [comment]
I was able to repro this in a simple GO workflow.  The interesting thing is that `IsReplay(ctx)` always returns `false`, even for decision task timeouts or after doing something like a workflow sleep.

I've submitted this to Uber:

https://github.com/uber-go/cadence-client/issues/821

**Comment by jefflill** [comment]
Uber confirmed that this is working as intended.  He also suggested that disabling the worker sticky cache and causing the workflow to sleep will cause it to be replayed.  I should be able to implement my replay unit tests taking advantage of this behavior.

**Comment by jefflill** [comment]
The sticky cache technique didn't work for these tests.  The problem is this causes Cadence to report replaying even on the first workflow run.  Maxim mentioned [here](https://github.com/uber-go/cadence-client/issues/821#issuecomment-521890186) that panic will also cause the workflow to replay.  I tried this in a pure GO workflow and it's doing exactly what we need.

I'm going to reopen this and see if I can add a new message to c **cadence-proxy** to do this without breaking things.

**Comment by johncburns1** [comment]
Sounds good. It should be fine since the proxy gracefully handles panics.

**Comment by johncburns1** [comment]
Seems like you are warming up to the go environment 😊

**Comment by jefflill** [comment]
@johncburns1: I've partially implemented this change on the **cadence-proxy** side.  I ended up adding the new `WorkflowInvokeReplay.ForceReplay` property and have the proxy **panic** in the workflow function.  This looked like it worked as expected in my little playground test case.

This looks like it's crashing **cadence-proxy**.  I suspect that you may be trying to catch and handle this panic somewhere else.  Can you have a look on Monday?  I'm going to move on to some other Cadence testing over the weekend.

**One other thing:** I think we should keep all of the logging you're doing in **cadence-proxy**; all of the logging you've marked for deletion with:
```
// $debug(jack.burns): DELETE THIS!
```
This all uses the **DEBUG** log level, so it shouldn't incur much overhead for production deployments which will typically use set **INFO** log level.  You can go ahead and delete these comments.

**Comment by johncburns1** [comment]
Yeah I can do that. I'm actually going up to queen Anne later today so might drop by and if it's something that is going to be a quick fix I'll go ahead and make the changes. Was contributing to the proxy pretty straight forward? Is it laid out in a way that makes it easy to get a good idea of what is going on/where everything is happening/how to add more message types and features?

**Comment by johncburns1** [comment]
So I resolved the panic issues with the new WorkflowInvokeReply.ForceReplay() property.  The test fails, but the panic is being handled and sending it back to the Neon.Cadence client.  I was not doing any panic recovery for ProxyReply message types.  We can talk about how you want this "panic notice" to come back to the workflow.

**Comment by jefflill** [comment]
Yeah, I have a look at the test when I get in.  My understanding is that the panic will be handled internally by the Cadence GOLANG client by restarting/replaying the workflow.  That’s the behavior I saw in my playground test.

**Comment by jefflill** [comment]
We're still seeing problems with `Workflow.IsReplaying` not being set to `true` after raising a panic in the GOLANG workflow function.  The workflow is being restarted as expected, but we're not seeing this property being set properly.  What's strange is that I see the expected behavior in the little GO workflow test.

I'm going to set this aside for a few days while I complete some other tasks and then have another look.

**Comment by jefflill** [comment]
*OH WAIT:** I had sticky execution still disabled.  After re-enabling this, we're seeing different behavior: **timeout**.

**Comment by jefflill** [comment]
Jack has this working now in **cadence-proxy**.  We're still seeing the original behavior where `IsReplaying=FALSE` when a workflow without any history is replayed.

I've reopened the Uber bug: uber-go/cadence-client#821

**Comment by jefflill** [comment]
@mfateev says this behavior is by design.  This means that it will be possible for logs/metrics written before the first operation that writes to history to be duplicated when the workflow is replayed because a rescheduled workflow with no history is considered by Cadence to still be the initial run.

**Comment by jefflill** [comment]
**BY DESIGN**
