### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#623]
@marcusbooyah: You have a couple of build warnings:

![image](https://user-images.githubusercontent.com/4908431/63195269-01533a80-c027-11e9-97fe-48692ea4621e.png)

The Regex warning looks like it may cause a malfunction.  In generally, we should try to fix warnings.

Also, when you have a chance, can you please put some words in the comments for parameters, etc. and also add <para>...</para> tags to code comments where necessary.  I'm going to start publishing a neonKUBE documentation website for releases next week.

**Comment by marcusbooyah** [comment]
I fixed the warnings and added some param comments.

**Comment by jefflill** [comment]
**YAY MR. BOOYAH!**
