### ISSUE TITLE
Multi-client: cadence-proxy is reporting DomainAlreadyExists on second connect

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#634]
When enabled, **cadcence-proxy** is supposed to create the domain domain *if it doesn't already exist*.  The **Test_MultiClient.ConnectTwice** test is failing on the second connection with a `DomainAlreadyExists ` error.

I suspect this is because you're not actually checking to ensure that that domain doesn't already exist before creating it.

The best approach is simply to ignore the `DomainAlreadyExists `error in this case.  Doing a check and create would probably work most of the time but there's the potential for a race condition between the existence check and creating the domain.  Its entirely possible that another client somewhere is doing the same thing and creates the domain between the time the first client checks and before it creates the domain.

I just pushed my multi-client changes to **cadence**.

**Comment by johncburns1** [comment]
DomainAlreadyExistsError is now being ignored during domain registration.
