### ISSUE TITLE
LogRequest/LogReply messages

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#639]
@johncburns1: I've added new `LogRequest/LogReply` messages to the .NET side.  You'll need to implementing these in **cadence-proxy**.

The idea here is that **cadence-proxy** will send a `LogRequest` in two cases:

1. When the Cadence GOLANG client logs something.
2. When your **cadence-proxy** code logs something.

There are four important message properties:

- `TimeUtc:` The time UTC when the log was generated.

- `LogLevel:` One of the [LogLevel](https://github.com/nforgeio/neonKUBE/blob/master/Lib/Neon.Common/Diagnostics/LogLevel.cs) enumeration values.  These should map pretty closely to the GOLANG logger levels.  I'd map `panic --> LogLevel.Critical` and you shouldn't have to worry about the security related levels.

- `FromCadence:` This is used to identify the event source.  Pass TRUE if the event is coming from the Cadence client or FALSE if it's coming from your code.

- `LogMessage:` The message text.

Note that you should never send a `LogRequest` when the log level `LogLevel.None` or is greater than the log level I passed to cadence-proxy in the new `InitializeRequest.LogLevel` message property (more on this below).

I added the new `LogLevel` property to the `InitializeRequest` message.  This will be set to `LogLevel.None` when logging is completely disabled.  I believe I'm currently passing the log level as a parameter on the cadence-proxy command line, but you should ignore this going forward (because there will be no command line (for production) once we've implemented the shared libraries.

I recommend that you leave everything as is when the cadence-proxy is started in the debugger so that you'll still be able to see these logs in the command window and then send the `LogRequest/Reply` messages when running in shared library mode.

My changes are pushed to **cadence**.

**Comment by johncburns1** [comment]
Waiting on clientId = 0 fix #644

**Comment by jefflill** [comment]
Closing this because #646 covers the remaining issues.
