### ISSUE TITLE
Duplicate workflow and (probably) activity registrations panic

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#641]
@johncburns1: I'm seeing this panic when registering a workflow that is already registered:
```
Neon.Cadence.CadenceCustomException : Panic: workflow name "TestCadence.Test_MultiClient.WorkflowWithResult1" is already registered
    MessageType: WorkflowRegisterRequest, RequestId: 18.
    goroutine 5025 [running]:
    runtime/debug.Stack(0xc0002ebce0, 0x12, 0x17)
    	C:/Go/src/runtime/debug/stack.go:24 +0xa4
    github.com/cadence-proxy/internal/endpoints.handleIProxyRequest.func1(0xf5db40, 0xc0000b6198, 0xc00042dbc0, 0xc00042dcc0)
    	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:156 +0x11d
    panic(0xcc0640, 0xc000567210)
    	C:/Go/src/runtime/panic.go:522 +0x1c3
    github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.RegisterWorkflowWithOptions(0xccb8c0, 0xc0002dcf60, 0xc00059e7b0, 0x30)
    	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/workflow.go:255 +0x83
    github.com/cadence-proxy/vendor/go.uber.org/cadence/workflow.RegisterWithOptions(...)
    	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/workflow/workflow.go:95
    github.com/cadence-proxy/internal/endpoints.handleWorkflowRegisterRequest(0xf4b000, 0xc00008a130, 0xc0000b6198, 0xc0000b6198, 0xc0003f7bc0)
    	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/request_handlers.go:503 +0x457
    github.com/cadence-proxy/internal/endpoints.handleIProxyRequest(0xf5db40, 0xc0000b6198, 0x0, 0x0)
    	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:269 +0xd1d
    github.com/cadence-proxy/internal/endpoints.processIncomingMessage(0xf58500, 0xc0000b6198, 0xc00055c840)
    	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:120 +0xed
    created by github.com/cadence-proxy/internal/endpoints.MessageHandler
    	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:72 +0x165
```
This is a problem for us because stopping a worker with registrations doesn't seem to actually unregister the workflow and activity registrations.  So this series of operations fails:

1. Establish Cadence connection A
2. Register a workflow on A
3. Start a worker on A
4. Stop the A worker
5. Dispose connection A
6. Establish a new connection B
7. Register the same workflow on B

Step 7 fails with the error above.

I wonder if it's possible for you to catch and ignore these duplicate registration panics for workflows and activities.

*Not a huge priority*

**Comment by jefflill** [comment]
Turns out this has a fairly high priority after all.  I've temporarily hacked the .NET side to ignore these errors but it would be better if you did this on the GOLANG side because you're more tightly coupled to the GO Cadence client.

Assign this back to me when this is done and I'll remove the hack from the .NET Client.

**Comment by johncburns1** [comment]
Just completed the fix for this.  Made a wrapper for the workflow.Register and activity.Register methods that catches panics and checks to see if the error contains the string "already registered".  If so then it ignore is, if not then panics the error again, which will trigger a panic response back to the .NET client.
