### ISSUE TITLE
Log to console mode

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#645]
@johncburns1: Can you do me a favor and add a somewhat hardcoded mode to the **cadence-proxy** that will print the log events out to standard output *in addition to* transmitting them to the .NET client via `LogRequest` messages?

- [x] The idea is that this would be an internal global boolean constant or variable that normally be FALSE but it would be nice to be able to temporarily be able to enable this when debugging.

- [x] Could you also log the client ID for all messages sent or received.  I'm currently debugging some multi-connection issues and this info would come in handy.

**Comment by johncburns1** [comment]
Would you like this to be able to be toggled or just hardcode it to be enabled?

**Comment by jefflill** [comment]
Yeah, it would make sense to hardcode this mode when **cadence-proxy** is run as its own process but never when it's deployed as a shared library.  That would be the best of all worlds.

**Comment by johncburns1** [comment]
I am about to push the changes.  I created a boolean var in main.go called verboseLogging.  When set to true, this sets the global var VerboseLogging to true.  Works exactly the same as DebugPrelaunched.  I altered the custom logger setup to take both debugPrelaunched and verboseLogging as parameters to create the logger core with.

Rules for the logger are this:
```
func (c Core) Write(entry zapcore.Entry, fields []zapcore.Field) error {
    if !debugPrelaunched {
        return transmitToDotnetClient()
    }
    var err error
    err = logToStandardOutput()
    if err != nil {
        return err
    }
    if verboseLogging {
        err = transmitToDotnetClient()
        if err != nil {
            return err
        }
    }
    return nil
}
```

**Comment by johncburns1** [comment]
I made the changes.  If the cadence-proxy is run with the debug flag (passed via command line args), then output will be logged to both stdout and transmitted to the .NET cadence client.  This works for both DebugPrelaunch and normal debugging.

**Comment by jefflill** [comment]
OK.  We'll call this done now and close this issue.
