### ISSUE TITLE
Cadence proxy logging issues

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#646]
Setting the `LogLevel` property in `CadenceSettings` and then connecting to a Cadence cluster via `CadenceClient.ConnectAsync()` does not alter the `InternalLogLevel` field.  `InternalLogLevel` is used to set the `LogLevel` property in a `InitializeRequest` sent to the cadence proxy during `CadenceClient.ConnectAsync()`.

The result is that the `LogLevel` sent to the cadence-proxy during initialization is always `None=0`, so nothing is getting logged by the cadence-proxy.

The proper behavior is that the user shall be able to alter the `LogLevel` sent to the cadence-proxy in the `CadenceSettings`, and the cadence-proxy should then use that as its log level for logging to stdout as well as transmitting messages back to the .NET client.

**Comment by jefflill** [comment]
@johncburns1: I'm working on this.  One potential change for you Jack is that `CadenceSettings.LogLevel` may now be set to **"none"** too.  This wasn't documented earlier so the **cadence-proxy** may not support it.

**Comment by johncburns1** [comment]
That's fine, when I deserialize the log level, I set it to all caps when I parse it so case shouldnt matter.

**Comment by jefflill** [comment]
@johncburns1: Never mind.  I'm passing you a `LogLevel` enum in the message.  I'm not sure why I had the setting be a string back when we first started this project.

**Comment by jefflill** [comment]
**FIXED**

**Comment by johncburns1** [comment]
Sorry I was wrapped up with the wf-sms stuff for the second half of the day.  Will get on it tomorrow.

**Comment by jefflill** [comment]
@johncburns1: The new log format is pretty hard to read.  Would it be possible to write a blank line after every entry logged to the console or perhaps not write as JSON?  Right now, it's pretty much a solid block of text.

As a temporary workaround, I've surrounded the  "---" logged messages for received messages in attempt to make these easier to pick out.  You can remove these.

I've also changed the name of your internal logger from *proxy* to *cadence-proxy*.

**Comment by johncburns1** [comment]
Yeah I can make it more human readable. I just did the json because it is a little more lightweight. I'll make it look beautiful

**Comment by jefflill** [comment]
Cool thanks.  This will probably pay off whenever we need to debug weird issues.

**Comment by johncburns1** [comment]
Add `\n` line ending as well as replace JSON encoder with a console encoder in the cadence-proxy logger.
