### ISSUE TITLE
Logging: Clients registering a default domain that is already registered is not an error

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#649]
@johncburns1: Cadence clients that specify a default domain are supposed to register the the domain if the domain is not already registered with Cadence.  The **cadence-proxy** is currently logging an error when the domain already exists.  We don't considered this an error (because of the expected behavior defined above). 

Can you please not log this error.

**Comment by johncburns1** [comment]
FIXED.

**Comment by johncburns1** [comment]
This behavior has changed.  Must react accordingly.

**Comment by jefflill** [comment]
What behavior has changed here?  We were talking yesterday about not eating the *type already registered* error, not the special case *domain already registered* error.  Is the code making this decision centralized?  *-- that would explain this then*

**Comment by johncburns1** [comment]
Yes yes, my bad.  Not domain.  Over zealous.
