### ISSUE TITLE
Generated service clients don't support Blazor

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#650]
We get the following error when constructing a `JsonClient`:

> System.PlatformNotSupportedException: System.Net.Http.HttpClientHandler is not supported on the current platform.

**Comment by jefflill** [comment]
I modified ModelGen to generate a new constructor for service clients that accepts an `HttpClient` parameter.  You should be able to simply pass the client you get from Blazor:

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.0

The new code does compile and my modelgen unit tests are passing but I haven't actually tested this with a Blazor app.
