### ISSUE TITLE
Implement metrics

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#657]
Use the [AppMetrics](https://github.com/AppMetrics/AppMetrics) to implement metrics for:

- [ ] NeonService
     - [ ] Console
     - [ ] Web
- [ ] Cadence
- [ ] Temporal

**Comment by marcusbooyah** [comment]
Another possible solution: https://github.com/prometheus-net/prometheus-net

**Comment by jefflill** [comment]
We ended up implement metrics here: #1039
