### ISSUE TITLE
New activity future messages

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#672]
We need some new messages to support running activities in parallel with other workflow operations.  The current activity execute messages execute and then wait for the result,  We need to be able break this up into operations, one that starts the activity and returns a reference to the activity promise and a second operation that waits for the promise to complete.

We'll need messages for normal and local activities:

- [x] `ActivityStartRequest/Reply`

`ActivityStartRequest` should start a normal activity but not wait for the future to return the result.  Instead, the **cadence-proxy** should persist the future in a local workflow map keyed by the `ActivityStartRequest.ActivityId` property (a `long`).  The reply simply indicates that the activity has been started.

- [x] `ActivityGetResultRequest/Reply`

`ActivityGetResultRequest` should call `Get()` on the local activity promise keyed by `ActivityId` and then send a `ActivityGetResultReply` with the result.

- [x] `ActivityStartLocalRequest/Reply`

`ActivityStartLocalRequest` should start a localactivity but not wait for the future to return the result.  Instead, the **cadence-proxy** should persist the future in a local workflow map keyed by the `ActivityStartLocalRequest.ActivityId` property (a `long`).  The reply simply indicates that the activity has been started.

- [x] `ActivityGetLocalResultRequest/Reply`

`ActivityGetLocalResultRequest` should call `Get()` on the local activity promise keyed by `ActivityId` and then send a ``ActivityGetLocalResultReply` with the result.

**Comment by jefflill** [comment]
@johncburns1: All of the messages above have been changed from inheriting from `ActivityRequest/ActivityReply` to inheriting from `WorkflowRequest/WorkflowReply`.

I realized that I need the current workflow replay status from you for these operations.

This change is pushed to **cadence**.

**Comment by johncburns1** [comment]
DONE.
