### ISSUE TITLE
Host Helm charts somewhere

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#673]
The GitHub API only allows 60 requests (per hour?) and installation breaks halfway through now that we have more Helm chart files to download. We can get around this by using keys but I think we should just host a public Helm repo (Harbor backed by S3?) somewhere.

**Comment by jefflill** [comment]
@marcusbooyah: Can this be closed now?

**Comment by jefflill** [comment]
**DONE**
