### ISSUE TITLE
cadence-proxy not responding to heartbeats

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#706]
@iancode: reports that the Loopie CustomerApi service is continuously logging Cadence heartbeat failures.

I saw this in the CustomerApi console window running locally via **neon-cli**.  The interesting thing is that these failures are not causing Cadence to drop the connection.

**Comment by jefflill** [comment]
@johncburns1: There are a couple issues here:

- [ ] Why are these timeouts occurring?
- [ ] The .NET side isn't closing the client connection when these timeouts occur.

The interesting thing was that the timeouts looked like they were happening on **one second** interval which seems weird because the default heartbeat timeout is **5 seconds**, which with the default heartbeat interval of 1 second means that we should have seen these reports every **6 seconds** (not just 1 second).

I'll poke around a bit on my side.  Heartbeats were re-enabled a couple releases ago.  Perhaps I broke something.

**Comment by jefflill** [comment]
I've temporarily disabled heartbeats for release **v0.7.0-alpha** so we can have a look at this.

**Comment by jefflill** [comment]
I took a quick look at this after re-enabling heartbeats and everything looks fine when running unit tests.  I'm now wondering if the Loopie services are using a too-short heartbeat timeout.  From looking at Ian's console window it seemed to be reporting a timeout every second or so.  The default timeout is currently 5 seconds.

**Comment by jefflill** [comment]
`CadenceClient` will now throw `ObjectDisposedException` exceptions after heartbeat failures, effectively closing the connection.  Ultimately we should look into transparently restarting **cadence-proxy** as descussed in #708.

**Comment by marcusbooyah** [comment]
Should this be set in the Cadence settings? @johncburns1 said it's in there now, but we aren't setting it for the Loopie services. Maybe the default is too short?

Current settings we are using:
```yaml
createDomain: true
debug: false
defaultDomain: loopie
logLevel: info
servers:
  - http://cadence-frontend.cadence:7933/
```

**Comment by jefflill** [comment]
@marcusbooyah: The default should be 5 seconds which should be plenty long which is what we're using for all of the unit tests.  Can you verify that this actually deserializes as 5 seconds in the services?

**Comment by johncburns1** [comment]
Im on it coach, just updating to new neon.

**Comment by jefflill** [comment]
After further investigation, this is actually a serious problem:

Each `CadenceClient` maintains a table of pending operations keyed by request ID.  Each operation includes the timeout and the `TaskCompletionSource`.  When replies are received from **cadence-proxy**, the client is supposed to complete the operation and then remove it from the table.  The problem is that **operation removal isn't happening**.

The effect is that the timeout thread will ultimately detect that **all operation** are timing out.  This happens silently in unit tests for all operations because the Xunit test runner silently absorbs all logging output going to STDOUT/STDERR.  In production code, we're only seeing this for heartbeats because only heatbeat failures are currently being logged by the client.

I initially thought that this would result in memory leak as well, but this won't happen because the timeout thread is removing these operations from the table.

**Comment by jefflill** [comment]
**FIXED**

**Comment by jefflill** [comment]
This is still a problem.  The code that removed completed operations got reverted somehow.

**Comment by jefflill** [comment]
**REALLY FIXED!**
