### ISSUE TITLE
Some of the Cadence tests are failing unexpectedly

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#709]
I was running all of the cadence tests at once and it looks like there are workers hanging around after their clients have been disposed of (which I think was the expected behavior).  This is causing decision task timeouts in almost all of the Test_EndToEnd tests as well as Test_MultiClient.Multiple_TaskLists.  This seems like a recent issue.  Test_MultiClient.Multiple_TaskLists fails with a heartbeat timeout waiting for this line to be true:
```
 return await Task.FromResult(Activity.Client.ClientId == workerClient1.ClientId);
```

**Comment by johncburns1** [comment]
Will do a deeper investigation into the issue.

**Comment by jefflill** [comment]
The workers should be disposed when connections are closed.

I might have tweaked that behavior recently.

—Jeff

**Comment by jefflill** [comment]
Yeah, I’ve been looking at this too.  I’m not sure what happened.

—Jeff

**Comment by jefflill** [comment]
I've commented out the code that's causing this.  I'm not sure it's worth fixing since it's just checking for developer errors but I'll put on the backlog to have another look later.

**Comment by jefflill** [comment]
I'm seeing one test fail with an activity timeout error but I think it's unrelated to recent changes.  I went ahead an re-enabled this code and am going to close this.
