### ISSUE TITLE
JsonClient: Retry policy not working?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#718]
@granth7: Reported that a retry policy in a Xamarin Android app isn't working.  Need to investigate.

**Comment by granth7** [comment]
This ended up being related to Android's HttpClient max timeout being set to 30 seconds.
So, the retry policy was never called because it was waiting for the default timeout.
Changing the HttpClient to a shorter interval resolves this issue for now.

**Comment by jefflill** [comment]
Closing as a false alarm.
