### ISSUE TITLE
Add "Command" menu to neonDESKTOP that launches a CMD window with correct PATH

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#722]
When installing/updating Docker Desktop, it puts it's version of kubectl first on the path. This is annoying since it's normally a couple versions behind, and may not support all features.

The workaround is to just delete the version of kubectl that's located here: `C:\Program Files\Docker\Docker\Resources\bin\kubectl.exe`

**Comment by jefflill** [comment]
**neonKUBE Desktop** probably won't be able to do that silently because modifying files in the **Program Files** directories requires elevated permissions.  I could see **neonKUBE Desktop** detecting this situation, asking the user for permission to delete (or rename) the file and then executing a little console app with elevated permissions to that deletes the thing.

**Comment by jefflill** [comment]
An alternative might be to have neonDESKTOP probe the PATH for `kubectl.exe` instances, check their versions and ensure that the most recent version is in the front of the PATH.  Although this might work, it's a huge hack.   Messing with somebody's PATH could really mess things up, let alone that existing processes won't see the change until it restarts.

A better alternative might be to launch `Cmdr` or a CMD window from neonDESKTOP with a specific PATH that we specify.

**Comment by jefflill** [comment]
...we'll also need to think about what version of `kubectl.exe` we're using in neonDESKTOP.  Do we need to upgrade this when users deploy newer versions of Kubernetes?  Should we match the `kubectl.exe` version with the connected cluster version or can we rely on `kubectl.exe` backwards compatibility.

**Comment by jefflill** [comment]
I went ahead and add the **Command** menu item that launches a Windows CMD.exe window with the correct PATH.
