### ISSUE TITLE
CodeDoc site improvements

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#729]
We're currently using the free Sandcastle Help File Builder (SHFB) to build our documentation.  It's working fairly well after I added the post-build munge that updates the HTML to flatten the site structure and replace GUID page names with something friendlier.

There are a couple things that could use some work:

- [x] The left-hand table of contents pane behavior is a bit weird though.  When you click on one of the TOC links, the right pane displays as expected but the TOC pane also updates such that not all page links are displayed.  This is probably an issue with the site scripts generated by SHFB.

- [ ] It would be nice to be able to add a **version menu** to all pages so we could publish documentation for multiple Neon versions.

- [ ] It would be nice to write a custom SHFB plugin that includes the type name for a remote type referenced via a `<see cref="..."/>`.  The idea is that references to items within the current type wouldn't include the type name but that references to types outside would.  The default SHFB implementation is confusing in this situation.

  **NOTE:** I've manually included the external type reference as another `<see cref="..."/>` in some places in the code, so we'd have to search for and remove these.

**Comment by marcusbooyah** [comment]
Porting to docfx #1206
