### ISSUE TITLE
Neon.Cadence DEBUG logs not showing in Kubernetes dashboard

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#766]
When setting log level to `DEBUG`  in a Kube Service deployment's `CadenceSettings` , the `DEBUG` level logs do not appear in the Kubernetes dashboard.

**Comment by jefflill** [comment]
@johncburns1: I took a look at this from the .NET side.  I set `CadenceSettings.Debug=true` and `CadenceSettings.LogLevel=LogLevel.Debug`.

**cadence-proxy** is sending the INFO messages but I never see a DEBUG message.

**Comment by jefflill** [comment]
This is working as expected.  The confusion is that to enable this, `LogManager.Current.LogLevel` must be set to `Debug` and CadenceSettings.LogLevel` must also be set to `Debug`.
