### ISSUE TITLE
Should ModelGen support flag enums?

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#770]
Investigate.

**Comment by jefflill** [comment]
We need to determine how JSON.NET handles bit wise/flag enums as well as probably enhance the Neon enum support for custom [EnumMember] values.

We should combine this investigation with #767.

**Comment by jefflill** [comment]
I added a couple unit tests to look into this.  It appears that JSON.NET is handling serialization of enum types with the `[Flags]` attribute as expected.  So this isn't a problem.
