### ISSUE TITLE
cadence-dev Docker image is no longer building

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#781]
@johncburns1: The **cadence-dev** Docker image is no longer building.  It looks like Cassandra setup is failing.

I tried poking around a bit and tried upgrading to a later Cadence version and that got further but failed due to a YAML config error.  Can you please have a look when you have a free moment?

**Comment by johncburns1** [comment]
On it.  What version of cadence did you upgrade to?

**Comment by jefflill** [comment]
I think I tried **36x** but I reverted.

**Comment by johncburns1** [comment]
Ok.

**Comment by johncburns1** [comment]
FIXED.  The issue was that Apache changed their endpoint for the Cassandra package download.  Switched the package download URI and seems to be building and running as it was before.
