### ISSUE TITLE
Cadence breaking changes

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#783]
There have been a handful of Cadence server releases since the last time the images was updated.  In the branch `cadence`, I have updated the Cadence server, Cassandra, Golang, Cadence go-client, and Cadence web UI to the most recent versions that are compatible with one another.  There are some breaking changes that need to be fixed on the .NET side.
The breaking changes that I can identify so far are:
* `go.uber.org/cadence/.gen/go/shared.DomainConfiguration` has removed the fields `ArchivalBucketName` and `ArchivalStatus` and have added `HistoryArchivalURI`, HistoryArchivalStatus, `VisibilityArchivalStatus`, and `VisibilityArchivalURI`
* `go.uber.org/cadence/workflow` has removed the field `ChildPolicy` and replaced it with `ParentClosePolicy`  
* `go.uber.org/cadence/workflow` has removed the type `ChildWorklfowPolicy`
* `go.uber.org/cadence/client` has added the type `ParentClosePolicy`
* There is now a limit on `go.uber.org/cadence/.gen/go/shared/RegisterDomainRequest.WorkflowExecutionRetentionPeriodInDays`.  We were originally setting this in `ConnectRequest` to create the default domain if specified.  The default value that we set for this was `int32(365)`.  The new limit is `int32(30)`

There are currently 2 tests failing in `Test.Neon.Cadence`:
* `TestCadence.Test_Messages.Test_WorkflowDescribeExecutionRequest`
* `TestCadence.Test_Messages.Test_WorkflowExecuteChildRequest`

These failures are related to the breaking changes mentioned about.

**Comment by jefflill** [comment]
Adding @marcusbooyah because we'll probably need to upgrade Cadence/Cassandra in production to support this.

**Comment by jefflill** [comment]
Changes in progress:

* I modified **cadence-proxy** to use `retentionDays=7` when it creates a default domain on connect.  This is consistent with the default of 7 days when a domain explicitly created by the user.

**Comment by jefflill** [comment]
Merged for **v2.0.0**
