### ISSUE TITLE
temporal-proxy port

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#800]
@johncburns1: I'm ready for your to start working (if you wish) on porting **cadence-proxy** --> **temporal-proxy**.  I've just completed #799 which copied and munged several projects like **Neon.Cadence** into **Neon.Temporal**.

The next steps are to:

- [x] **JEFF:** Port **cadence-proxy** over to Temporal.  I figure we'll call this **temporal-proxy** and I've added a build script for this.  The script actually builds **cadence-proxy** and then copies the generated files into the **Neon.Temporal** library project so that project can build.  You'd need to figure out how to build the real thing.

- [x] **JEFF:** I imagine some settings will need to change (i.e. the port Temporal server exposes to clients) and there are probably some other changes we'll have to deal with.  It sounds like Maxim has been using Temporal as an opportunity to refactor some names.

     **JEFF:** I've renamed some settings to better match what Temporal is doing, we now clone settings before establishing a connection, settings bound to a client are now read-only, and we do some setting validation now.

- [x] **JEFF:** I've created the **temporal-dev** Docker image but it's just a placeholder and it's actually just building **cadence-dev**, so **JACK** will need to do your magic here too,

- [x] **JEFF:** Maxim has renamed **Domain --> Namespace**.  I've done the same on the .NET side everywhere.

See the comment below with more TODO items.

**Comment by johncburns1** [comment]
On it!!!

**Comment by shenzhen-xi** [comment]
hi what's the status of `temporal-proxy`? is it useable

**Comment by jefflill** [comment]
No not yet.  We're only a couple weeks into the port of the **Neon.Cadence** .NET SDK to **Neon.Temporal**, so it's very much under construction still.  We're hoping to have something folks can begin previewing in 2-3 weeks or so.

The [Neon.Cadence](https://github.com/nforgeio/neonKUBE/tree/master/Lib/Neon.Cadence) .NET SDK is usable at this time if you wish to give it a spin.  We've been running workflows in production for about 6 months with that.  The Temporal port will work pretty much the same, but we''ll be renaming some things (e.g. "Cadence" --> "Temporal") and we're also completing some missing features but we expect that it won't be a huge task to migrate workflows written for **Neon.Cadence**.

**Comment by jefflill** [comment]
**NEXT ROUND OF CHANGES:**

---

**Workers:**

Temporal has changed the worker life-cycle a bit.  For Cadence, you established a connection, then registered workflow and activity implementations on the connection and then started the worker, specifying the domain and task list.  This was a bit broken and essentially prevented developers from starting more than one worker for any given connection,  Also, we believe that the activity/workflow registrations were actually managed as a global process static, which means that any given GOLANG process can only host one worker.  We worked around this by starting a new **cadence-proxy** for each .NET connection.

Temporal addresses this by:

- [x] **JEFF:** A new worker uses the `Namespace` specified for the client connection rather than specifying this as a parameter.  This means that `TemporalSettings.Namespace` will now be required when establishing a .NET Temporal connection.

- [ ] **JEFF:** Workflow/Activity registration is now done on the worker instance (not the client):
     - [ ] **JEFF:** Relocate the registration APIs to `Worker`
     - [ ] **JEFF:** Remove the `NewWorkerRequest.Namespace` property.  This is now implied by the Cadence client.
     - [ ] **JEFF:**

**Comment by jefflill** [comment]
**CLOSING:** Temporal is deprecated.  We're waiting for an official client.
