### ISSUE TITLE
ArgumentNullException for workflows that return an error and a result

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#808]
We're seeing this happen with interop testing against GOLANG workflows.  The problem happens when a workflow returns a result (like a string) as well as an error.  The problem is that **cadence-proxy** is replying with the encoded result as NULL when the workflow returns an error but the `JsonDataConverter` has an argument check that ensures that the encoded data is never NULL, resulting in the errant exception.

I've removed this check and added unit tests to cover this situation.

I also noticed that `WorkflowStub` doesn't have a `Task GetResultAsync()` method for the situation where the workflow doesn't return a result.  I've added this.

**Comment by jefflill** [comment]
Fixed for: v2.0.1

**Comment by kaiverge** [comment]
Thank you very much Jeff, will test it as soon as i can
