### ISSUE TITLE
.NET client needs to implement TaskListKind

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#842]
Temporal introduced the concept of TaskListKind, which describes the _kind_ of a tasklist.  The details are bellow:
```
const (
	// Decision type of task list.
	TaskListType_Decision TaskListType = 0
	// Activity type of task list.
	TaskListType_Activity TaskListType = 1
)
```

It looks like they define 2 different kinds of tasklists, **Decision** and **Activity**.  When describing a tasklist, this is a value that is returned.  At the moment `Test_DescribeTaskListRequest` fails with a deserialization error because the .NET client does not know about this value.

**Comment by jefflill** [comment]
Actually, this `enum` definition does exist in the .NET client.

We actually define two similar enums: `TaskListKind` and `TaskListType`.  The former looks like it matches what you have above and `TaskListType` indicates a _normal_ vs. a _sticky_ task list.

The current code doesn't appear to use `TaskListKind` for anything.  I believe we defined that for admin APIs we haven't implemented yet.  From what you have above, it looks like Temporal renamed **TaskListKind --> TaskListType**.

**Comment by jefflill** [comment]
The original `DescribeTaskList` message included both `TaskListType` and `TaskListKind` properties.  The updated cirresponding GOLANG API doesn't appear to accept a `TaskListKind` parameter, so I've removed this from this message on the .NET side.  `TaskListType` remains.

@johncburns1: Are you serializing a `TaskListKind` property or a `TaskListType` property on the GOLANG side?

It should be `TaskListType`.

**Comment by johncburns1** [comment]
I am serializing both `TaskListKind` and `TaskListKind`.  I think this is an error on my end though.  Looking at the input parameters to `DescribeTaskList`, it does not look like it even takes TaskListKind.  So this is for sure an oversight on my end.  I will just remove `TaskListKind` and that should fix this.

**Comment by johncburns1** [comment]
I'll go ahead and close this SINCE IT IS NOT ACTUALLY AN ISSUEEE!!!

**Comment by johncburns1** [comment]
After looking deeper into this, it looks like we actually do need to pass `TaskListKind` in the `DescribeTaskListRequest`.  The `workflowservice.DescribeTaskListRequest` contains a `TaskList` type, which takes a `TaskListKind` value.  I am not sure if this is required.  It looks like this is not a required field, but it exists.

```
DescribeTaskListRequest struct {
    Namespace             string                `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
    TaskList              *tasklist.TaskList    `protobuf:"bytes,2,opt,name=taskList,proto3" json:"taskList,omitempty"`
    TaskListType          tasklist.TaskListType `protobuf:"varint,3,opt,name=taskListType,proto3,enum=tasklist.TaskListType" json:"taskListType,omitempty"`
    IncludeTaskListStatus bool                  `protobuf:"varint,4,opt,name=includeTaskListStatus,proto3" json:"includeTaskListStatus,omitempty"`
}

type TaskList struct {
	Name string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind TaskListKind `protobuf:"varint,2,opt,name=kind,proto3,enum=tasklist.TaskListKind" json:"kind,omitempty"`
}
```

**Comment by jefflill** [comment]
Oh, I've been looking at the GODOC which must be out of date.

**Comment by jefflill** [comment]
You know, I suspect this is a Temporal screw-up.  I think that the `Kind` field in the request is actually supposed to be a `TaskListType`, not a `TaskListKind` and it's compiling due to GOLANG's crappy enum implementation.  These enum types are are both just `int32` so there's no actual type checking happening during compilation for any assignments.

It really doesn't make sense for this API to list workers based on whether they're **sticky** or **normal**.  @johncburns1: Why don't you submit a Temporal issue to get some guidance (and to let them know we're still alive)?

So `DescribeTaskListRequest` continues to include the `TaskListType TaskListType` property.  I also noticed that Temporal has added the `IncludeTaskListStatus bool` request property.  I've added a new `bool IncludeStatus` to the .NET side's `DescribeTaskListRequest` to accommodate that and added a parameter to the client corresponding method.  @johncburns1: You'll need to add support this this.

I've pushed these changes to **master** and **temporal**.

**Comment by johncburns1** [comment]
I am a bit confused about what exactly I would be asking them.  I guess one thing comes to mind is if you can define a TaskList with a specific name that is **sticky**, does this also mean that you can define a TaskList with the same name that is **normal**? If this is true then it makes sense why you would want that filter.  If not, then it does not really.  The same question goes for `TaskListType`.  Specifying a type somewhat implies that you can define 2 TaskLists with the same name in the same namespace, but different types.  I could see this being useful if you wanted to configure Activity workers differently than Decision workers (different logging, policies, stickiness, etc.).

**Comment by johncburns1** [comment]
I think this might be what you are getting at, but what does it even mean for a TaskList to be **sticky** vs **normal**? Does this mean if a TaskList is sticky, only workers that have sticky execution turned on can poll that TaskList?

I think that I may be on my way to verifying your conjecture about the `TaskListKind` being unnecessary.  It is not even used in the internal `DescribeTaskList` client call, and it's not like you can explicitly create a TaskList and specify the `TaskListKind`.  So when does this ever get used?

**Comment by johncburns1** [comment]
It looks like for now, we can omit both the `TaskListKind` and `IncludeTaskListStatus` values from the `DescribeTaskListRequest`.  `DescribeTaskListRequest` is a relic and with the front-facing workflow client, is not even used in the `DescribeTaskList` client call.  This is my fault, I just assumed that the request is what was getting passed to the client, but they have changed this, I did not change the wrapper on the proxy side though.  i am going to do some more digging on this.  There is some strange stuff going on here.

**Comment by johncburns1** [comment]
So I think I got to the bottom of this client business.  So earlier there was some confusion on my end about the public workflow `Client` and `NamepaceClient` and the internal `WorkflowServiceClient`.  It seems like we are doing the correct thing now using the public workflow and namespace clients.  Behind the scenes, both of these are backed by a `WorkflowServiceClient`.  The `WorkflowServiceClient` is what actually establishes the connection and makes the GRPC calls to the Temporal server.  Each one of the `WorkflowServiceClient` calls takes a `***Request` and returns the corresponding `***Reply`.  When you make a call to the public workflow and namespace clients, the input parameter values are used to create these `***Request` that are then sent to the Temporal server over the wire via the `WorkflowServiceClient`.

**Comment by jefflill** [comment]
Yeah, that’s how the Java client works too.  I don’t really like the
pattern so I didn’t follow it for .NET.  I think they went this way because
GOLANG and Java doesn’t support method parameters with default values like
C# does.

**Comment by jefflill** [comment]
We discussed having the **temporal-proxy** messages use the .NET class definitions for structures like this rather than having the .NET side have to implement the GOLANG types.

I'm closing this and we'll track these issues via #800
