### ISSUE TITLE
DescribeNamespaceResponse deserialization

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#843]
With the Temporal updates, the property `DescribeNamespaceResponse.NamespaceInfo.Status` (type of `enum NamespaceStatus`) cannot deserialize a `string` value.  It requires an `int32` value to be passed in order to deserialize correctly on the golang side. 

`NamespaceConfiguration.EmitMetric` is no longer a `bool` value.  The have replaced this with a struct called `BoolValue`.  The definition is:
```
BoolValue struct {
    // The bool value.
    Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}
```

We might need to match this on the .NET side to be able to serialize/deserialize the `DescribeNamespaceResponse` properly.

**Comment by jefflill** [comment]
@johncburns1: What in heaven do those other fields even do???   Seems really weird.

**Comment by jefflill** [comment]
This is a mess, we may need to define our own JSON schema for this.  It'll probably be better to decouple from low-level protocol stuff anyway.

**Comment by johncburns1** [comment]
Yeah it looks like it is for some GRPC proto stuff.  It's very odd.  There is an identical struct for `Int` as well.

**Comment by jefflill** [comment]
We discussed having the **temporal-proxy** messages use the .NET class definitions for structures like this rather than having the .NET side have to implement the GOLANG types.

I'm closing this and we'll track these issues via #800
