### ISSUE TITLE
How To register an activity method in GO Cadence and call it from GO

### ISSUE THREAD

**Issue by kaiverge** [nforgeio/neonKUBE#850]
Hi, will you please tell me the best scenario of doing the following:

GO cadence server is running.
With Neon.Cadence, I am registering an activity with GO Cadence server.
When GO Cadence executes an activity from step 2, the activity runs a specific c# function that returns a text or an error.
How do I implement it.

Currently I do this, will it be enough?

```
[ActivityInterface(TaskList = "hello-tasks")]
   public interface IHelloActivity : IActivity
   {
       [ActivityMethod]
       Task<string> HelloAsync(string name);
   }

   [Activity(AutoRegister = true)]
   public class HelloActivity : ActivityBase, IHelloActivity
   {
       public async Task<string> HelloAsync(string name)
       {
           return await Task.FromResult($"Hello {name}!");
       }
   }

public static async Task Main(string[] args)
       {
           try
           {
               var settings = new CadenceSettings("cadence://localhost:7933")
               {
                   DefaultDomain = "test-domain",
                   CreateDomain  = true
               };

               using (var client = await CadenceClient.ConnectAsync(settings))
               {
                   await client.RegisterActivityAsync<HelloActivity>();
                   await client.StartWorkerAsync("my-tasks");
                }
            }
         }
```

if its the right way to register a method, how do I call it from GO now? Thank you.

**Comment by jefflill** [comment]
You'll have to include the error information in your result type definition, perhaps something like:
```
public class ResultBase
{
   public string Error { get; set; }
}

public class TextResult : ResultBase
{
   public string Text { get; set; }
}
 
[Activity(AutoRegister = true)]
public class HelloActivity : ActivityBase, IHelloActivity
{
    public async Task<string> HelloAsync(string name)
    {
        if (name == "" || name == null)
        {
            await Task.FromResult(new TextResult() { Error = "emptyargument" );
        }

        return await Task.FromResult(new TextResult() { Text = $"Hello {name}!" );
    }
}
```
So essentially, you'll have to encode the error in the result and then have the calling client (written in GOLANG) in your case check the error after each call.  It might be worth adding some wrapper functions on the GOLANG side that perform this check and then convert the error string (or whatever) into a native GOLANG error.

Cross language workflows are possible of course, but they won't be seamless.  Sometimes you'll have to account for language differences.  For example, C# strings can be `null`.

---

PS: I'm in process of moving and will be offline for a few days.  I'm going to be shutting my computers down this afternoon and am having the movers do their thing tomorrow.

**Comment by kaiverge** [comment]
Thanks,

To run it, .net core console project will do? That executes and finishes.

or

.met core web app project might be required?

**Comment by jefflill** [comment]
Neon.Cadence is compatible with .NET Core and .NET Framework Console, ASPNET/Core, WinForms, and WPF but only for 64-bit Intel/AMD binaries.  We are not compatible with Xamarin (for cellphones) or UWP (Microsoft’s somewhat crippled platform for simple windows apps).  We also support Windows, Linux, and OS/X.

We’ve been targeting .NET Core console apps deployed on Linux in production for several months now and we also do our development and debugging in Visual Studio, running both the workers and clients as Windows binaries.

**Comment by kaiverge** [comment]
Hi Jeff,

Using neon cadence registering an activity and starting worker:

```
  var client = await CadenceClient.ConnectAsync(new CadenceSettings()
                {
                    DefaultDomain = _configuration.GetValue<string>("AppSettings:CadenceDefaultDomain"),
                    Servers = new List<string>() { _configuration.GetValue<string>("AppSettings:CadenceServer") },
                });
                if (client != null)
                {
                    await client.RegisterActivityAsync<Cn1ToCsvActivity>();
                    WorkerOptions workerOtions = new WorkerOptions();
                    workerOtions.Identity = "cn1ToCsv-Activity: " + Guid.NewGuid().ToString();
                    await client.StartWorkerAsync(taskList: "Cn1ToCSVGroup", options: workerOtions);
                }
```
after it runs, when i look at GO cadence Pollers I see: **Pollers identity Unknown.**

What sets Pollers identity?

Thanks you.

P.S. Now all settled in the new place?

**Comment by jefflill** [comment]
The **WorkerOptions.Identity** property should have done that.  I noticed
last week that the Temporal team has removed this property from their
GOLANG client and I believe the identity will be inferred from the client
settings.

I’ll have to take a look at this.  One thing you can try in the meantime is
setting **CadenceSettings.Identity** and passing that when you connect your
client.

Moving is going well.  I got my Internet back online last night.  I have a
few things to move and need to clean the old place tomorrow and have to
unpack and set up the new place.  Should be back online by Monday.

—Jeff

**Comment by kaiverge** [comment]
CadenceSettings    - ClientIdentity    did the trick, thank you.

**Comment by kaiverge** [comment]
Hi Jeff, the move is over?

Im registering an activity, but than, i cannot run it with a workflow, looks like it cannot find it:

 ```
[ActivityInterface(TaskList = "ActivityGroup")]
    public interface IMyActivity: IActivity
    {
        [ActivityMethod]
        Task<string> RunIt(string name);
    }

    [Activity(AutoRegister = true, Name = "MyActivity")]
    public class MyActivity: ActivityBase, IMyActivity
    {
        public async Task<string> RunIt(string name)
        {
            if (name == "" || name == null)
            {
                await Task.FromResult(new TextResult() { Error = "empty argument" }.Error);
            }

            try
            {
                return "Hello" + name;
            }
            catch (Exception e)
            {
                await Task.FromResult(new TextResult() { Error = e.Message }.Error);
            }

            return null;
        }
}

 [WorkflowInterface(TaskList = "ActivityGroup")]
    public interface IActivityWorkflow: IWorkflow
    {
        [WorkflowMethod]
        Task<string> RunIt(string name);
    }
    [Workflow(AutoRegister = true)]
    public class ActivityWorkflow: WorkflowBase, IMyActivity
    {
        public async Task<string> RunIt(string name)
        {
            var stub = Workflow.NewActivityStub<IMyActivity>();

            return await stub.RunIt(name);
        }
    }

        public async Task RegisterActivity()
        {
            try
            {
                //using (
                var identity = "MyActivity: " + Guid.NewGuid().ToString();

                var client = await CadenceClient.ConnectAsync({connection params});
                if (client != null)
                {
                    await client.RegisterActivityAsync<MyActivity>();
                    WorkerOptions workerOtions = new WorkerOptions();
                    workerOtions.Identity = identity;
                    await client.StartWorkerAsync(taskList: "Cn1ToCSVGroup", options: workerOtions);
                }
                else
                {
                    throw new Exception("cannot connect to server");
                }
                //}
            }
            catch (Exception err)
            {
                throw new Exception($"There is a problem with calling CsvToCn1: {err.Message}", err);
            }
        }

        public async Task RunIt()
        {
            try
            {
                var identity = "cn1ToCsv-Workflow: " + Guid.NewGuid().ToString();

                var client = await CadenceClient.ConnectAsync(new CadenceSettings()
                {
                    DefaultDomain = _configuration.GetValue<string>("AppSettings:CadenceDefaultDomain"),
                    Servers = new List<string>() { _configuration.GetValue<string>("AppSettings:CadenceServer") },
                    ClientIdentity = identity,
                });
                if (client != null)
                {
                    //await client.RegisterAssemblyAsync(Assembly.GetExecutingAssembly());
                    await client.StartWorkerAsync(taskList: "ActivityGroup");

                    var stub = client.NewWorkflowStub<IActivityWorkflow>();
                    var result = await stub.RunIt("Sally");

                    Console.WriteLine($"RESULT: {result}");
                }
                else
                {
                    throw new Exception("cannot connect to server");
                }
                //}
            }
            catch (Exception err)
            {
                throw new Exception($"There is a problem: {err.Message}", err);
            }
        }
```


as you can see, registeractivity() function registers activity, and RunIt() function, supposed to run it.

RunIt() doesnt work, when it gets to    var result = await stub.RunIt("Sally");, it runs forever, and in cadence we can see that workflow is running and never finishes.

The same happens when trying to run the activity from GO, workflow is constantly running, feels like it cannot find the activity.

Can you give me a glitch on whats going on? Thanks.

**Comment by jefflill** [comment]
I'm going to remove the `WorkerOptions.Identity` property: #855
