### ISSUE TITLE
Neon cadence activity dependency injection

### ISSUE THREAD

**Issue by kaiverge** [nforgeio/neonKUBE#852]
Hi Jeff,

the activity method shall hold dependency injection to be able to run functionality of other c# library.

Here is the activity class:
```
 public class InjectionServiceActivity: ActivityBase, IInjectionService
    {
        InjectionService _injectionService;
        public InjectionServiceActivity(InjectionService injectionService)
        {
            _InjectionService = InjectionService;
        }
         .......................
    }
```

whenever the activity method is called, im getting dependecy injection error
Exception thrown: 'System.InvalidOperationException' in Microsoft.Extensions.DependencyInjection.Abstractions.dll

**Comment by jefflill** [comment]
Hi Kai,

Sorry, my Internet has been delayed.  I’m doing a bit of house rewiring
today and should be back in line by tomorrow.

In the meantime, here’s a link a bit of documentation for activity
dependency injection.

https://doc.neonkube.com/Neon.Cadence-Activity-DendencyInjection.htm

Your activity will need to derive from IActivity, implement your activity
interface along with a constructor that accepts a parameter with the type
being injected and then register the injected value before you start the
worker.

—Jeff

**Comment by kaiverge** [comment]
Thanks for the link, however when I add

    NeonHelper.ServiceContainer.AddSingleton(typeof(InjectionService));

it still throughs dependency injection exception if in activity class I have a constructor with injection.
