### ISSUE TITLE
Docker Swarm init bug

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#854]
@jefflill you may have fixed this for the upcoming release by switching to `docker-compose` so I am not sure how relevant this is.  In the latest `Neon.Cadence` version (`2.1.0`), Temporal is attempting to spin up its fixture using `docker stack` and throws an error if your local docker is not initialized as a swarm node.  When I initialized my local docker as a swarm node, Temporal dev image spun up fine, but notified me that the stack was empty.

It is also interesting that the Temporal dev image is starting as well.  I am not sure where this is happening.  I admittedly did not look too far into this.

**Comment by jefflill** [comment]
I believe this is fixed, but will check tomorrow.  I’m just finishing
running some coax to my home office so I can get the Internet set up.

—Jeff

**Comment by jefflill** [comment]
Looks like this will be fixed for v2.2.0.  We switched to `docker-compose`.  The v2.1.0 release probably was still configured to use `temporal-dev` since Temporal is still very much a work in progress.
