### ISSUE TITLE
M3DB shards

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#859]
This is currently set to 256 which was the default. Having this many shards is not necessary in many cases, and causes M3 initialization to [take quite some time](https://github.com/m3db/m3/issues/1969).

Configuration guidelines are documented [here](https://m3db.github.io/m3/operational_guide/placement_configuration/), and number of shards should be calculated using these during cluster setup.

**Comment by jefflill** [comment]
We should probably close this, huh? (now that we're doing Cortex)
