### ISSUE TITLE
M3 needs containerResources

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#862]
This is just a [ResourceRequirements](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#resourcerequirements-v1-core). Needs to be set or the cluster will keep taking memory until it blows up and reboots. It needs to be set during cluster setup based on the M3 node resources.

**Comment by jefflill** [comment]
We should probably close this, huh? (now that we're doing Cortex)
