### ISSUE TITLE
JACK: Cadence issues

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#865]
We're seeing a few Cadence related issues in both the **release-1.3.0** and master **branches**.  Note that I'm continuing to publish Neon releases 1.x until Loopie has a chance to upgrade to Temporal and Neon 2.x.

I noticed that you were having trouble with passing a nullable `TimeSpan` to a workflow when you were messing with one of the 2.x releases a week or so ago.  **release-1.3.0** and the upcoming **2.2.0** releases will fix this.  We're also changing the default workflow ID reuse policy to **AllowDuplicate** from **AllowDuplicateFailedOnly** for both Cadence and Temporal going forward.  I've made these changes on the .NET side but we're seeing some unit test failures.  I believe that **cadence-proxy** may not be parsing related messages correctly.  You'd need to fix this in the **release-1.3.0** and **master** branches if that's actually the problem.  Here are the failing tests:

- [x] `Test_EndToEnd.Workflow_ChildIdReuseViaAttribute`
- [x] `Test_EndToEnd.Workflow_ChildIdReuseViaOptions`
- [x] `Test_EndToEnd.Workflow_ExternalIdReuseViaAttribute`
- [x] `Test_EndToEnd.Workflow_ExternalIdReuseViaOptions`
- [x] `Test_Messages.Test_WorkflowSignalWithStartRequest`

Here are a couple other unrelated test failures:

- [x] `Test_EndToEnd.Activity_ExternalErrorById`
- [x] `Test_EndToEnd.Activity_ExternalErrorByToken`

The problem here is that I'm seeing errors reported as being **generic** rather than **custom**.  I looked that this a few weeks back and I believe the .NET side was passing **custom** errors back to the proxy in these cases but that the proxy was ignoring that and returning a **generic** error to Cadence.  I'm seeing this in both the **master** and **release-1.3.0** branches.

This is likely a problem for **temporal-proxy**.

**Comment by johncburns1** [comment]
I have been looking into the `WorkflowIDReusePolicy` issue and it appears that the reuses policies along with some other options are not being serialized properly by the `ProxyMessage.SetJsonProperty()` method in **Neon.Cadence** before being sent to the **cadence-proxy**.  For example, as it stands these are the only 2 `StartWorkflowOptions` that are received by **cadence-proxy** at the moment: 
```
{"TaskList":"tests","ExecutionStartToCloseTimeout":86400000000000}
```

This seems to have something to do with the `InternalStartWorkflowOptions` class.  I noticed that all of the `StartWorkflowOptions` that were making it over to the **cadence-proxy** were the properties not tagged with the `[DefaultValue()` attribute.  I removed this from `InternalStartWorkflowOptions.WorkflowIdReusePolicy` and `WorkflowIdReusePolicy` was received in the `StartWorkflowOptions` by the **cadence-proxy**.  The resulting JSON is what was received by the **cadence-proxy** after removing the `DefaultValue` attribute:
```
{"TaskList":"tests","ExecutionStartToCloseTimeout":86400000000000,"WorkflowIdReusePolicy":1}
```

The original not working code in `Neon.Cadence.Internal.InternalStartWorkflowOptions`:
```
/// <summary>
/// WorkflowIDReusePolicy - Whether server allow reuse of workflow ID, can be useful
/// for dedup logic if set to WorkflowIdReusePolicyRejectDuplicate.
/// Optional: defaulted to WorkflowIDReusePolicyAllowDuplicate.
/// </summary>
[JsonProperty(PropertyName = "WorkflowIdReusePolicy", DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate)]
[DefaultValue(Cadence.WorkflowIdReusePolicy.AllowDuplicate)]
public int WorkflowIdReusePolicy { get; set; } = (int)Cadence.WorkflowIdReusePolicy.AllowDuplicate;
```

The working code:
```
/// <summary>
/// WorkflowIDReusePolicy - Whether server allow reuse of workflow ID, can be useful
/// for dedup logic if set to WorkflowIdReusePolicyRejectDuplicate.
/// Optional: defaulted to WorkflowIDReusePolicyAllowDuplicate.
/// </summary>
[JsonProperty(PropertyName = "WorkflowIdReusePolicy", DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate)]
public int WorkflowIdReusePolicy { get; set; } = (int)Cadence.WorkflowIdReusePolicy.AllowDuplicate;
```

**Comment by johncburns1** [comment]
I removed all `[DefaultValue()]` attributes from the `InternalStartWorkflowOptions` and `InternalChildWorkflowOptions` and the tests are now passing.

**Comment by johncburns1** [comment]
I am going to look into the `CadenceError` issue though.  I think this might be a separate issue but I am not sure where it is happening yet.

**Comment by johncburns1** [comment]
I am working through the `CadenceError` issue right now and noticed that I did the errors originally in a really stupid way so I am reworking them entirely.  Should not be a huge change, but 2 of the above tests are failing now because of the change.  The failing tests are:

- [ ] Test_EndToEnd.Activity_ExternalErrorById
- [ ] Test_EndToEnd.Activity_ExternalErrorByToken

**Comment by johncburns1** [comment]
All **Message** and **End_To_End** test passing on 1.3.0-release.  I need to make the changes in master branch now.

**Comment by johncburns1** [comment]
Changes have been made to **Master** branch as well.  There are 2 failing tests as a result of issue #880.  Once we get these resolved, all tests should be passing and issue will be resolved.

**Comment by jefflill** [comment]
I'm going to go ahead and close this one.  We'll track #880 separately.
