### ISSUE TITLE
Unify log retention

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#872]
Currently `cluster-manager` will purge old logs from elasticsearch based on the user specified log retention period. 

The problem is that the rest of the logging stack does not honor this. So if `neon-log-host` is restarted on a node for any reason, and that node still contains logs outside the retention period that maybe haven’t been rotated yet, they will be put back into elasticsearch again, only to be purged right away.

Rotated log files older than the retention period should be removed if they aren’t already, that might be enough here. We can also have `cluster-manager` configure the rest of the logging stack to throw out old entries.

**Comment by jefflill** [comment]
It looks like **kublet** writes it's logs to **systemd/journald**[ by default](https://serverfault.com/questions/900016/kubernetes-kubelet-logging-to-files-and-logrotate).

So **journald** appears to be configured to use a maximum of 10% of disk space by default and will always try to keep at least 15% of the disk free for other things:

https://www.thegeeksearch.com/how-to-rotate-systemd-journald-log-in-centos-rhel-7/

The **journalctl** command also includes the `--vacuum-time` and `vacuum-size` options so we could deploy a CRON job to vaccuum the logs periodically.    Better yet, we could set the `MaxRetentionSec` in **journald.conf** (this is disabled by default):

https://www.freedesktop.org/software/systemd/man/journald.conf.html#MaxRetentionSec=

**Comment by jefflill** [comment]
After some investigation, we've determined that CRI-O handles pod log file rotation and that it defaults to retaining up to 5 log files of 10MB max each.  That means that a pod can have 50MB of logs each so 100 pods on a node will max out at a collective 5GB of logs on a node.  This seems OK.

The hope is that **promtail** will be able to keep up with these logs and git them over to Loki to be persisted,
