### ISSUE TITLE
CadenceError.ToException() conversion method strips error message.

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#880]
The converter `CadenceError.ToException()` method is deconstructing the `CadenceError`, but when constructing the resulting `Exception`, the error message in the most deeply nested "{ }" gets dropped.

Example:

**Original Error Message**: `System.Exception{external activity failed}`
**One Conversion**: `{System.Exception}`
**Two Conversions**: `{}`

This is causing 2 tests to fail in **Master**:

- [x] Test_EndToEnd.ActivityExternalErrorById,
- [x] Test_EndToEnd.ActivityExternalErrorByToken.

**Comment by jefflill** [comment]
This is basically tracking the same issue as #662.  I'm going to close this and finish up there.
