### ISSUE TITLE
XenServer/XCP-ng hosts allow LAN port customization

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#885]
XenServer/XCP-ng defaults new VMs to use the first LAN port on the host machine by default.  @marcusbooyah's home machine has a bad first port so he's connected to the network via another port and cluster VMs don't have network connectivity.

We probably need a way to specify which host LAN port the VMs will use in the cluster definition.

**Comment by marcusbooyah** [comment]
You can list the networks using the `xe network-list` command.

Looks like unless the names are changed by the user, the `name-label` will be some default that doesn't reflect the actual 'name' that the user may specify.

Below I renamed NIC 0 to "Network 0", the others have a default name "Pool-wide network associated with ethx", even though their name in XCP-ng Center is "Network x" (which I assume will be what the user will specify).

Example:

> [16:52 xcp-ng ~]# xe network-list
uuid ( RO)                : edbd017c-5934-d552-8027-609c9b348095
          name-label ( RW): Pool-wide network associated with eth3
    name-description ( RW):
              bridge ( RO): xenbr3
uuid ( RO)                : a9048cbf-5a1b-4bad-273e-b3792234d555
          name-label ( RW): Pool-wide network associated with eth1
    name-description ( RW):
              bridge ( RO): xenbr1
uuid ( RO)                : 91d724ab-52f5-369f-2cb4-684d41e6d9b9
          name-label ( RW): Network 0
    name-description ( RW):
              bridge ( RO): xenbr0
uuid ( RO)                : 8e20b964-da9c-d64d-ea9e-63a2c899283a
          name-label ( RW): Host internal management network
    name-description ( RW): Network on which guests will be assigned a private link-local IP address which can be used to talk XenAPI
              bridge ( RO): xenapi
uuid ( RO)                : 5444f1a9-d50c-ff2a-db4e-72167671861a
          name-label ( RW): Pool-wide network associated with eth2
    name-description ( RW):
              bridge ( RO): xenbr2

**Comment by jefflill** [comment]
@marcusbooyah: So this is a XenServer/XCP-ng configuration thing:

https://docs.citrix.com/en-us/xencenter/7-1/hosts-nics.html
https://www.practicalxenserver.org/tutorials/scenario-2/tutorial-2/part-2/

You need to configure all of the physical NICs into a single **active-active bonded NIC**.  This will cause the host to load balance all network traffic for the VMs as well as the host itself across the physical NICs and traffic will be automatically routed through the remaining good NICs when any NIC fails.

We should probably configure our production XCP-ng hosts with bonded NICs.  This would be useful even if we don't connect all NICs to the switch because if we lost a NIC, we could simply plug in to another port without having to do any configuration.

**NOTE:** I had to reboot XCP-ng after creating the bonded NIC to get this to work.

I tried this on my home box by creating the bonded NIC, moving the network cable to the second physical NIC and it worked OK.

This is something we'll want to document as a neonKUBE best practice.  I've created an issue to start tracking these doc issues: #886
