### ISSUE TITLE
Kube config not working

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#888]
We are currently copying the kube config from one of the masters to the dev workstation during setup. Since adding the local load balancer for the k8s masters, the DNS that’s being used will not work on developer workstations. There are at least a couple options here which we will discuss.

**Comment by marcusbooyah** [comment]
We are going to have `neon-desktop` proxy requests to the Kubernetes API service. This means that the kubeconfig will need to be modified to point to a loopback address on dev workstations, and `neon-desktop` will need to have this service added to the proxy entries.

**Comment by marcusbooyah** [comment]
Closing. We will revisit when we revamp neonDESKTOP.

**Comment by jefflill** [comment]
Related issues:

#962 
#430
