### ISSUE TITLE
neon base images vs. external ones?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#894]
While cleaning up some Docker images in #893, I noticed that some of the new images like **neon-log-collector** are based on external images (that we don't control).

In the past, we frowned on doing this because that meant that an external player could potentially break our stuff by publishing new bits or more likely they decide to delete an image (as as happened in the past Elasticsearch if I remember correctly).

We should think about this and potentially refresh our policy.

**Comment by johncburns1** [comment]
This applies to the cadence-dev image.  Should we keep this image as is or just use the official docker-compose like we are doing with temporal?

**Comment by jefflill** [comment]
It would be nice to convert that to docker-compose too, if that's easy.

Although, we will hopefully be depreciating Cadence soon, we may want to maintain it for several months and it would be nice to not have the screw around with random build issues.  You're call.

**Comment by johncburns1** [comment]
I think it would probably be better to go with the compose.  It is easier to maintain.  We have already had issues with packages being deprecated (i.e. open source java jdk) in the cadence-dev image.  We are also doing this for temporal.  But low priority at this point.

**Comment by jefflill** [comment]
After thinking about this, I think we should relax requiring our base Docker images to be standalone.  That's probably too much trouble for what we'll get out of it.  It does make sense to have our own base images like **alpine**, **aspnet**, **dotnet** etc. where we include some common packages and configuration.
