### ISSUE TITLE
Standardize neonKUBE service names like: neon-*

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#896]
Let's standardize neonKUBE service names to be prefixed by **"neon-"**.  This will help identify what code belongs to us and potentially avoid naming conflicts with other other services.

I noticed that we're deploying the **cluster-manager** service.  We should change this to **neon-cluster-manager**.

@marcusbooyah: Can you handle this?

You'll need to:

- [x] Rename the `$/Services/cluster-manager` folder to `$/Services/neon-cluster-manager`
- [x] Update `NeonServices.ClusterManager` to return **"neon-cluster-manager"**
- [x] Rename the `$/Images/cluster-manager` folder to `$Images\neon-cluster-manager`
- [x] Update the `$/Images/publish.ps1` script
- [x] Update the `$/Images/neon-cluster-manager/publish.ps1` script to:
```
change:

$registry = GetRegistry "cluster-manager"

to:

$registry = GetRegistry "neon-cluster-manager"
```
- [x] Goto DockerHub and remove **nkubedev/cluster-manager** and **nkubeio/cluster-manager**
- [ ] Manually create the **nkubeio/neon-cluster-manager** repo and paste the image's **README.MD** file as the description.
- [x] Make any required changes to your Helm charts.

We'll also need to discuss Helm chart versioning (I believe we have another issue for this).  Ideally, we'll want only release versions of neonKUBE to deploy using images from **nkubeio** and all other builds to deploy from **nkubedev**,  optionally using images tagged with the current GitHub branch.

**Comment by jefflill** [comment]
#685: Helm chart versions

**Comment by marcusbooyah** [comment]
DONE
