### ISSUE TITLE
[cadence-dev] container Cassandra memory limits

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#932]
@johncburns1: I wonder if it might be possible to modify the settings in the `cadence-dev` container image to reduce the memory footprint of this thing?

There's two levels of settings, one for Cassandra itself and then one for the JVM that runs it.  I'd bet we'd have more luck with the JVM settings:

https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/operations/opsTuneJVM.html

Might be worth a quick look.

**Comment by marcusbooyah** [comment]
Looks like it is Java/Cassandra lots of memory, Cadence not so much:
![image](https://user-images.githubusercontent.com/11889627/88422900-c95c8780-cd9f-11ea-8904-c9c3b877a76a.png)

**Comment by marcusbooyah** [comment]
It looks like Cassandra is calculating the available memory based on what's available to the Docker host VM and not the container it's running in. We'll need to calculate and set memory limits manually.

To get available memory inside a container: `cat /sys/fs/cgroup/memory/memory.limit_in_bytes`

**Comment by jefflill** [comment]
@marcusbooyah: Are you ready to close this one?

**Comment by marcusbooyah** [comment]
Yeah we are good here now.
