### ISSUE TITLE
Tasklist and Namespace properties in WorkerOptions

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#946]
Right now the `WorkerOptions` include **Tasklist** and **Namespace** properties.  These are not included in the `Temporal.WorkerOptions` and so they get lost when they are sent to the proxy.  We still need both **Tasklist** and **Namespace** in the `NewWorkerRequest` message but they maybe should exist as separate properties instead as part of the `WorkerOptions`.

**Comment by johncburns1** [comment]
What I have done for the moment (and I will not push this change unless I get the Ok) is to keep the **Tasklist** and **Namespace** properties in `WorkerOptions`, and include them as individual properties in the `NewWorkerRequest` message.  This way nothing changes from the user perspective (the worker is entirely configured using the `WorkerOptions`) and the properties that are not found in the `Temporal.WorkerOptions` on the Go side are just going to be omitted when the message is processed.  The `NewWorkerRequest` **Tasklist** and **Namespace** properties get set in in the `TemporalClient.NewWorkerAsync()` method:

```
options = options ?? new WorkerOptions();

if (string.IsNullOrEmpty(options.Namespace))
{
    options.Namespace = Settings.Namespace;
}

if (string.IsNullOrEmpty(options.TaskList))
{
    options.TaskList = Settings.DefaultTaskList;

    if (string.IsNullOrEmpty(options.TaskList))
    {
        throw new ArgumentException("Worker cannot be started without a task list.  Please specify this via [WorkerOptions.TaskList] or [TemporalSettings.DefaultTaskList].");
    }
}

var reply = (NewWorkerReply)(await CallProxyAsync(
new NewWorkerRequest()
{
    Namespace = options.Namespace,
    TaskList  = options.TaskList,
    Options   = options
}));
```

**Comment by jefflill** [comment]
Go ahead and push this change and then we’ll need to see how the Java API
handles this and do the same.  Perhaps they just rely on the defaults
specified by the connection settings.  If that’s the case, we’d just use
the values from the connection settings too and removed these properties
from WorkflowOptions.

...might break done unit tests.

—Jeff

**Comment by johncburns1** [comment]
Ok will do.
