### ISSUE TITLE
Workflow with default argument value not working?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#973]
@granth7 reported that a workflow with a default parameter isn't working.

**Comment by jefflill** [comment]
This is interesting: Default arguments are not working as expected for both **external workflows** and **child workflows**, but they do work for **activities**.

I implemented a workflow method that accepts a string parameter that defaults to **"default"** and the method just returns the parameter.  Then I:

1. Call the workflow without passing a parameter then then verify that the result is **"default"**.  **This works!**

2. Then I call the workflow passing **"test"**.  The result comes back incorrectly as **"default"**.

The interesting thing is that **this works correctly for activities**.  I'll have to compare the code generated for workflow vs. activity stubs.  Apparently, I got this right at least once :)

**Comment by jefflill** [comment]
@marcusbooyah: I should be able to fix this for workflows, rather than detecting default arguments and throwing an exception saying something to the effect that default arguments aren't allowed.  It's best avoid arbitrary limits like this that users will encounter and wastes their time.

**Comment by jefflill** [comment]
@granth7: It turns out that I had a bug in my unit test and that default arguments appear to be working fine for Cadence in the latest code.

What was the behavior you were seeing?

**Comment by jefflill** [comment]
@granth7: Where did you assign the default argument?  I'll bet you did this in the workflow implementation, not in its interface definition.  When the C# compiler calls an interface method, it doesn't (really can't) take the implementation class method default argument values into account.  The compiler uses only default values defined by the interface.

This makes logical sense, because interfaces can be used to reference multiple class implementations, and each of those could assign a different value.  So which one would should the compiler use?  The answer is: the value defined by the interface.

For Cadence/Temporal, you create a stub that implements the workflow/activity interface.  I actually generate these stubs at runtime by generating C# source code for the implementing class and then compiling it.  So in this case, the implementing class doesn't even exist yet when C# compiles your program.

So here's how C# works:

* If you call a class method directly, the default arguments defined by the class method will be used.
* If you call an interface method, the default arguments defined by the interface will be used and the class method's default arguments will be ignored.

Here's an example:
```
using System;

namespace Test
{
    public interface IFoo
    {
        void Bar(string label, string value = "default");
    }

    public class Foo : IFoo
    {
        public void Bar(string label, string value = "WTF???")
        {
            Console.WriteLine($"{label}: {value}");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Foo foo = new Foo();

            foo.Bar("class");

            IFoo ifoo = new Foo();

            ifoo.Bar("interface");
        }
    }
}
```
This will print:
```
class: WTF???
interface: default
```
Is this what was happening to you, Grant?

**Comment by granth7** [comment]
In my interface I had `Task Foo(DateTime? expiration = null);`,
but then in my implementation I again had `Task Foo(DateTime? expiration = null);`.

So, the compiler should have defined the value from the interface, but the argument should be null in both cases.
I'd be happy to replicate the problem if you need more information.

**Comment by jefflill** [comment]
OK, that helps a bit.  Perhaps it has something to do with the billable
TimeSpan.

**Comment by jefflill** [comment]
@granth7: So I finally poked around on this some more this evening and realized that you were passing a `DateTime?` not a `TimeSpan?` which I incorrectly thought you were doing.  So, I modified my unit tests to match what I believe is your scenario for both the **master** branch as well as the **release-1.4.1** branch which will be the next Loopie release branch.

I test passing the default (null) value to workflows, child workflows, and activities as well as non-null `DateTime` to values to these as well.  I have the workflows and activities return the value passed and I verify the results against the parameters I passed explicitly or implicitly via the default value.  The unit tests are all passing in both branches.  

Do you remember the behavior you were seeing when you reported this?  We're you always seeing `null` parameter values even when you passed a non-null argument?

I still can't replicate this.  If you have time, could you look at my unit tests for this:

https://github.com/nforgeio/neonKUBE/blob/master/Test/Test.Neon.Cadence/Test_EndToEnd.Activity.cs
https://github.com/nforgeio/neonKUBE/blob/master/Test/Test.Neon.Cadence/Test_EndToEnd.Workflow.cs

The releated tests are at the very bottom of both of these files.

**Comment by jefflill** [comment]
Closing this; I was never able to repro the problem.
