### ISSUE TITLE
Log filtering

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#989]
It would be nice to be able to configure logging rules to drop certain log types. We can actually do this at the container level with [k8s annotations](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-annotations), but it's all or nothing. It would be better if we could add some other filtering for example maybe we would like to drop all 2XX access logs, but keep 5XX etc.

I have already removed Envoy logs in the monitoring namespace [(commit)](https://github.com/nforgeio/neonKUBE/commit/02c578350b1d803394a060a60eca4e08cacff096)

**Comment by jefflill** [comment]
We can live without access logs as especially now that we'll have Prometheus network metrics.
