### ISSUE TITLE
OpenEBS cStore provisioning

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#993]
- [x] **JEFF:** Create an additional block device for OpenEBS **cStore** for nodes within cluster.
     - [x] neonKUBE clusters will require at least one node having a cStore block device,  We'll allow the user to optionally label nodes with **"openebs"** to specify this, otherwise we'll automatically try try to select the nodes automatically.  We'll try to configure up to 3 cStore nodes, favoring workers when we can.
     - [x] The cStore block device size and type will be specified in the hosting options for the specific environment: `VmOptions`, `VmNodeOptions, `AwsOptions`, `AwsNodeOptions`, `AzureOptions`, `AzureNodeOptions`,... like we do for the main OS drive with a default cStore drive size/type that can be overridden for specific nodes.
     - [x] **Machine** implementation: This hosting manager will work a bit differently.  The user will need to have an unpartitioned physical block device on at least one of the node machines.  The hosting manager will scan the cluster nodes looking for nodes with unpartitioned devices and assume that those will be the cStore nodes.
     - [x] **AWS** implementation
     - [x] **Azure** implementation
     - [x] **Local Hyper-V** implementation
     - [x] **XenServer** implementation
     - [x] Testing
          - [x] AWS
          - [x] Azure
          - [x] Local Hyper-V
          - [x] XenServer
&nbsp;
- [ ] **MARCUS:** Switch from [Local PV HostPath](https://docs.openebs.io/docs/next/uglocalpv-hostpath.html) to [Local PV Device](https://docs.openebs.io/docs/next/uglocalpv-device.html) once we get block devices.

**Comment by jefflill** [comment]
I'm calling creating the cStore disks done.  I've tested Hyper-V (local), XenServer, and Azure.  AWS is coded but I'll test that after I finish with the public/private subnet changes and we'll do comprehensive Machine hosting manager testing later.

@marcusbooyah: You can let OpenEBS scan for the unpartitioned drives like we discussed.  Alternatively, `SshProxy<T>.ListUnpartitionedDisks() returns the names of the unpartitioned block devices on a node.

**Comment by jefflill** [comment]
cStore provisioning for AWS is complete now as well.
